import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { threatIntelApi } from '../../api/threatIntel';
import { PageHeader, PageShell, SectionCard } from '../../components/ui';
import { FormField, inputClass } from './shared';

export function AddIndicatorPage() { const navigate = useNavigate(); const [form,setForm]=useState({type:'domain',value:'',title:'',description:'',severity:'medium',confidence:'50',tlp:'amber',tags:''}); const [busy,setBusy]=useState(false); const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value})); const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const result=await threatIntelApi.create<{indicator:{id:number};duplicate:boolean}>('indicators',{...form,confidence:Number(form.confidence),tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)});toast[result.duplicate?'info':'success'](result.duplicate?'Existing normalized indicator returned':'Indicator created');navigate(`/threat-intelligence/indicators/${result.indicator.id}`);}catch{toast.error('Indicator validation failed');}finally{setBusy(false);}}; return <PageShell className="max-w-3xl"><PageHeader title="Add indicator" subtitle="Normalization and validation are performed by the backend. Lifecycle flags cannot be injected."/><SectionCard><form onSubmit={event=>void submit(event)} className="grid gap-4 sm:grid-cols-2"><FormField label="Type"><select className={inputClass} value={form.type} onChange={e=>set('type',e.target.value)}>{['ipv4','ipv6','cidr','domain','hostname','url','email','sha256','sha1','md5','file_name','user_agent','vulnerability_id','custom'].map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Value"><input required maxLength={2048} className={inputClass} value={form.value} onChange={e=>set('value',e.target.value)}/></FormField><FormField label="Title"><input maxLength={240} className={inputClass} value={form.title} onChange={e=>set('title',e.target.value)}/></FormField><FormField label="Severity"><select className={inputClass} value={form.severity} onChange={e=>set('severity',e.target.value)}>{['info','low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Confidence"><input type="number" min="0" max="100" className={inputClass} value={form.confidence} onChange={e=>set('confidence',e.target.value)}/></FormField><FormField label="TLP"><select className={inputClass} value={form.tlp} onChange={e=>set('tlp',e.target.value)}>{['clear','green','amber','amber+strict','red'].map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Tags (comma separated)"><input className={inputClass} value={form.tags} onChange={e=>set('tags',e.target.value)}/></FormField><FormField label="Description"><textarea maxLength={4000} className={inputClass} value={form.description} onChange={e=>set('description',e.target.value)}/></FormField><button disabled={busy} className="rounded bg-primary px-4 py-2 sm:col-span-2 disabled:opacity-50">Create inert IOC record</button></form></SectionCard></PageShell>; }

