import { useState, type ReactNode } from 'react';
import clsx from 'clsx';

const badge = 'inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold capitalize';
export function IndicatorTypeBadge({ type }: { type: string }) { return <span className={`${badge} border-cyan-500/40 bg-cyan-500/10 text-cyan-200`}>{type.replaceAll('_', ' ')}</span>; }
export function IndicatorSeverityBadge({ severity }: { severity: string }) { const color = severity === 'critical' ? 'border-red-500/50 text-red-200' : severity === 'high' ? 'border-orange-500/50 text-orange-200' : severity === 'medium' ? 'border-amber-500/50 text-amber-100' : 'border-blue-500/40 text-blue-200'; return <span className={clsx(badge, color)}>{severity}</span>; }
export function ConfidenceMeter({ value }: { value: number }) { return <div className="min-w-24" aria-label={`Confidence ${value} percent`}><div className="mb-1 text-xs text-muted-foreground">{value}%</div><div className="h-2 rounded bg-muted"><div className="h-full rounded bg-cyan-400" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div></div>; }
export function TlpBadge({ value }: { value: string }) { const color = value === 'red' ? 'bg-red-500/20 text-red-100' : value.startsWith('amber') ? 'bg-amber-500/20 text-amber-100' : value === 'green' ? 'bg-emerald-500/20 text-emerald-100' : 'bg-slate-500/20'; return <span className={clsx(badge, color)}>TLP:{value}</span>; }
export function IndicatorValueDisplay({ value, rawValue }: { value: string; rawValue?: string }) { const [raw, setRaw] = useState(false); const shown = raw && rawValue ? rawValue : value; return <div className="flex min-w-0 items-center gap-2"><code className="break-all rounded bg-muted px-2 py-1 text-xs">{shown}</code>{rawValue && <button className="rounded border px-2 py-1 text-xs" onClick={() => setRaw(current => !current)}>{raw ? 'Defang' : 'Raw'}</button>}<button className="rounded border px-2 py-1 text-xs" onClick={() => void navigator.clipboard.writeText(shown)}>Copy</button></div>; }
export function IndicatorStatusBadge({ active, revoked, expired, falsePositive = false }: { active: boolean; revoked: boolean; expired?: boolean; falsePositive?: boolean }) { const label = falsePositive ? 'false positive' : revoked ? 'revoked' : expired ? 'expired' : active ? 'active' : 'inactive'; return <span className={`${badge} border-border bg-muted`}>{label}</span>; }
export function MatchRiskBadge({ score }: { score: number }) { const label = score >= 80 ? 'critical' : score >= 60 ? 'high' : score >= 40 ? 'medium' : score >= 20 ? 'low' : 'informational'; return <span className={`${badge} border-orange-500/40`}>{score.toFixed(1)} · {label}</span>; }
export function SourceReliabilityBadge({ value }: { value: number }) { return <span className={`${badge} border-violet-500/40`}>Reliability {value}%</span>; }
export function SightingModuleBadge({ module }: { module: string }) { return <span className={`${badge} border-emerald-500/40`}>{module.replaceAll('_', ' ')}</span>; }
export function ImportSummaryCard({ item }: { item: Record<string, unknown> }) { return <div className="grid gap-3 rounded border p-4 sm:grid-cols-5">{['total_records','accepted_records','duplicate_records','rejected_records','warning_count'].map(key => <div key={key}><div className="text-xs text-muted-foreground">{key.replaceAll('_',' ')}</div><div className="text-xl font-semibold">{String(item[key] ?? 0)}</div></div>)}</div>; }
export function WatchlistSelector({ watchlists, onAdd }: { watchlists: Array<{ id: number; name: string }>; onAdd: (id: number) => void }) { const [id, setId] = useState(''); return <div className="flex gap-2"><select value={id} onChange={event => setId(event.target.value)} className="rounded border bg-background px-3 py-2"><option value="">Select watchlist</option>{watchlists.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!id} onClick={() => onAdd(Number(id))} className="rounded bg-primary px-3 py-2 disabled:opacity-50">Add</button></div>; }
export function CampaignIndicatorGraph({ indicators, relationships = [] }: { indicators: Array<Record<string, unknown>>; relationships?: Array<Record<string, unknown>> }) { return <div className="rounded border p-4" aria-label="Data-only campaign indicator graph"><div className="flex flex-wrap gap-3">{indicators.map(item => <div key={String(item.id)} className="rounded border bg-muted p-3 text-xs">IOC #{String(item.id)}<br />{String(item.display_value ?? item.indicator_type ?? '')}</div>)}</div><p className="mt-3 text-xs text-muted-foreground">{relationships.length} analyst-defined relationships. This graph makes no automatic causal claim.</p></div>; }
export function MatchDispositionDialog({ onSubmit, children }: { onSubmit: (status: string, note: string) => Promise<void>; children?: ReactNode }) { const [status, setStatus] = useState('reviewing'); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); return <div className="space-y-3 rounded border p-4"><h3 className="font-semibold">Analyst disposition</h3><select value={status} onChange={event => setStatus(event.target.value)} className="w-full rounded border bg-background p-2">{['reviewing','confirmed','false_positive','accepted_risk'].map(value => <option key={value}>{value}</option>)}</select><textarea value={note} onChange={event => setNote(event.target.value)} maxLength={4000} className="min-h-24 w-full rounded border bg-background p-2" placeholder="Bounded analyst note" />{children}<button disabled={busy} onClick={() => { setBusy(true); void onSubmit(status, note).finally(() => setBusy(false)); }} className="rounded bg-primary px-3 py-2 disabled:opacity-50">Save disposition</button></div>; }

