import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { threatIntelApi } from '../../api/threatIntel';
import { PageHeader, PageShell, SectionCard } from '../../components/ui';
import { ImportSummaryCard } from './components';
import { ResourceTable, inputClass, useThreatPage } from './shared';

export function ImportsPage(){const {data,error,load}=useThreatPage('imports');const [sources,setSources]=useState<Array<{id:number;name:string}>>([]);const [sourceId,setSourceId]=useState('');const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);useEffect(()=>{void threatIntelApi.list<{id:number;name:string}>('sources',{enabled:true}).then(x=>setSources(x.items));},[]);const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!file||!sourceId)return;setBusy(true);try{const result=await threatIntelApi.importFile(Number(sourceId),file);toast.success('Bounded import completed');setFile(null);await load();if(result.warning_count||result.rejected_records)toast.warning('Import completed with warnings');}finally{setBusy(false);}};return <PageShell><PageHeader title="IOC imports" subtitle="CSV, JSON, bounded STIX bundles, and typed plain-text lists. Files are parsed in memory and are not retained."/>{error&&<p className="text-destructive">{error}</p>}<SectionCard title="Import local IOC data"><form onSubmit={e=>void submit(e)} className="grid gap-3 sm:grid-cols-3"><select required className={inputClass} value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Select source</option>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required type="file" accept=".csv,.json,.txt,application/json,text/csv,text/plain" className={inputClass} onChange={e=>setFile(e.target.files?.[0]??null)}/><button disabled={busy} className="rounded bg-primary px-3 py-2 disabled:opacity-50">Import (2 MiB / 5,000 records max)</button></form></SectionCard>{data?.items[0]&&<ImportSummaryCard item={data.items[0] as Record<string,unknown>}/>}<ResourceTable title="Import manifests" items={(data?.items??[]) as Record<string,unknown>[]} detailBase="/threat-intelligence/imports" columns={[["id","ID"],["filename","Safe filename"],["format","Format"],["status","Status"],["accepted_records","Accepted"],["duplicate_records","Duplicates"],["rejected_records","Rejected"]]}/></PageShell>}

