import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { threatIntelApi, type ThreatIndicator } from '../../api/threatIntel';
import { PageHeader, PageShell, SectionCard } from '../../components/ui';
import { CampaignIndicatorGraph, ConfidenceMeter, IndicatorSeverityBadge, IndicatorStatusBadge, IndicatorTypeBadge, IndicatorValueDisplay, TlpBadge, WatchlistSelector } from './components';

export function IndicatorDetailsPage() { const {indicatorId=''}=useParams(); const [item,setItem]=useState<ThreatIndicator|null>(null); const [watchlists,setWatchlists]=useState<Array<{id:number;name:string}>>([]); const load=()=>threatIntelApi.get<ThreatIndicator>('indicators',indicatorId).then(setItem); useEffect(()=>{void load();void threatIntelApi.list<{id:number;name:string}>('watchlists').then(x=>setWatchlists(x.items));},[indicatorId]); if(!item)return <PageShell>Loading indicator…</PageShell>; const lifecycle=async(action:'revoke'|'restore')=>{await threatIntelApi.create(`indicators/${item.id}/${action}`,{});toast.success(`Indicator ${action}d`);await load();}; const addWatchlist=async(id:number)=>{await threatIntelApi.create(`watchlists/${id}/entries`,{indicator_id:item.id});toast.success('Added to watchlist');await load();}; return <PageShell><PageHeader title={item.title||`Indicator #${item.id}`} subtitle="Safe IOC details and stored-data timeline." actions={<button className="rounded border px-3 py-2" onClick={()=>void lifecycle(item.revoked?'restore':'revoke')}>{item.revoked?'Restore explicitly':'Revoke'}</button>} /><SectionCard title="Indicator identity"><div className="space-y-4"><div className="flex flex-wrap gap-2"><IndicatorTypeBadge type={item.indicator_type}/><IndicatorSeverityBadge severity={item.severity}/><TlpBadge value={item.tlp}/><IndicatorStatusBadge active={item.active} revoked={item.revoked} expired={item.expired} falsePositive={item.false_positive}/></div><IndicatorValueDisplay value={item.display_value} rawValue={item.normalized_value}/><ConfidenceMeter value={item.confidence}/><div className="text-sm text-muted-foreground">Original submitted value is retained as inert text: <code className="break-all">{item.value}</code></div><div className="flex flex-wrap gap-2">{item.tags.map(tag=><span key={tag} className="rounded bg-muted px-2 py-1 text-xs">{tag}</span>)}</div><WatchlistSelector watchlists={watchlists} onAdd={id=>void addWatchlist(id)}/></div></SectionCard><div className="grid gap-4 lg:grid-cols-2"><SectionCard title="Sightings"><Records items={item.sightings}/></SectionCard><SectionCard title="Matches"><Records items={item.matches}/></SectionCard><SectionCard title="Watchlists"><Records items={item.watchlists}/></SectionCard><SectionCard title="Campaigns and relationships"><CampaignIndicatorGraph indicators={item.campaigns??[]} relationships={item.relationships??[]}/></SectionCard></div></PageShell>; }
function Records({items=[]}:{items?:Record<string,unknown>[]}){return items.length?<div className="space-y-2">{items.map((x,index)=><pre key={String(x.id??index)} className="overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(x,null,2)}</pre>)}</div>:<p className="text-sm text-muted-foreground">No records.</p>}

