import { useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, PageShell } from '../../components/ui';
import { ConfidenceMeter, IndicatorSeverityBadge, IndicatorStatusBadge, IndicatorTypeBadge, IndicatorValueDisplay, TlpBadge } from './components';
import { ResourceTable, inputClass, useThreatPage } from './shared';

export function IndicatorsPage() {
  const [filters, setFilters] = useState({ q: '', indicator_type: '', severity: '', tlp: '', min_confidence: '', max_confidence: '', revoked: '', expired: '', sort: 'updated_at', direction: 'desc', page: 1, page_size: 25 });
  const params = Object.fromEntries(Object.entries(filters).filter(([,value]) => value !== ''));
  const { data, error } = useThreatPage('indicators', params);
  const update = (key: string, value: string) => setFilters(current => ({ ...current, [key]: value, page: 1 }));
  return <PageShell><PageHeader title="Indicators" subtitle="Normalized IOC inventory. Values are defanged and never linked automatically." actions={<Link className="rounded bg-primary px-3 py-2" to="/threat-intelligence/indicators/new">Add indicator</Link>} /><div className="grid gap-2 rounded border p-4 sm:grid-cols-2 lg:grid-cols-5"><input className={inputClass} placeholder="Search value, title, or tag" value={filters.q} onChange={event => update('q', event.target.value)} /><Select value={filters.indicator_type} onChange={value => update('indicator_type', value)} options={['ipv4','ipv6','cidr','domain','hostname','url','email','sha256','sha1','md5','file_name','user_agent','vulnerability_id','custom']} label="All types" /><Select value={filters.severity} onChange={value => update('severity', value)} options={['info','low','medium','high','critical']} label="All severities" /><Select value={filters.tlp} onChange={value => update('tlp', value)} options={['clear','green','amber','amber+strict','red']} label="All TLP" /><Select value={filters.revoked} onChange={value => update('revoked', value)} options={['false','true']} label="Active/revoked" /><input className={inputClass} type="number" min="0" max="100" placeholder="Min confidence" value={filters.min_confidence} onChange={event => update('min_confidence',event.target.value)} /><input className={inputClass} type="number" min="0" max="100" placeholder="Max confidence" value={filters.max_confidence} onChange={event => update('max_confidence',event.target.value)} /><Select value={filters.expired} onChange={value => update('expired', value)} options={['false','true']} label="Any expiration" /><Select value={filters.sort} onChange={value => update('sort', value)} options={['updated_at','created_at','confidence','severity','indicator_type']} label="Sort" /><Select value={filters.direction} onChange={value => update('direction', value)} options={['desc','asc']} label="Direction" /></div>{error && <p className="text-destructive">{error}</p>}<ResourceTable title={`${data?.total ?? 0} indicators`} items={(data?.items ?? []) as Array<Record<string, unknown>>} detailBase="/threat-intelligence/indicators" columns={[["indicator_type","Type", item => <IndicatorTypeBadge type={String(item.indicator_type)} />],["display_value","Value",item => <IndicatorValueDisplay value={String(item.display_value)} />],["severity","Severity",item => <IndicatorSeverityBadge severity={String(item.severity)} />],["confidence","Confidence",item => <ConfidenceMeter value={Number(item.confidence)} />],["tlp","TLP",item => <TlpBadge value={String(item.tlp)} />],["active","Status",item => <IndicatorStatusBadge active={Boolean(item.active)} revoked={Boolean(item.revoked)} expired={Boolean(item.expired)} falsePositive={Boolean(item.false_positive)} />]]} /></PageShell>;
}
function Select({ value, onChange, options, label }: { value: string; onChange: (value: string) => void; options: string[]; label: string }) { return <select className={inputClass} value={value} onChange={event => onChange(event.target.value)}><option value="">{label}</option>{options.map(option => <option key={option} value={option}>{option.replaceAll('_',' ')}</option>)}</select>; }

