import { Link, useLocation } from 'react-router-dom';
import { Shield, ShieldAlert, LayoutDashboard, Target, Activity, FileText, Settings, Network, Radar, ChevronDown, FileSearch, MailWarning, GitMerge, Scale, Users, KeyRound, ScrollText, User, Wrench, Workflow, Cable } from 'lucide-react';
import clsx from 'clsx';
import { useAuth } from '../../auth/useAuth';
import { useEffect, useState } from 'react';
import { apiClient } from '../../api/client';

export function Sidebar() {
  const location = useLocation();
  const { can } = useAuth();
  const [demoMode, setDemoMode] = useState(false);
  useEffect(() => { if (can('operations:view')) void apiClient.get('/operations/demo/status').then(r => setDemoMode(Boolean(r.data.demo_mode))).catch(() => setDemoMode(false)); }, [can]);

  const navItems = [
    { name: 'Dashboard', path: '/dashboard', icon: LayoutDashboard, permission: 'dashboard:view' },
    { name: 'Targets', path: '/targets', icon: Target, permission: 'web:read' },
    { name: 'Scans', path: '/scans', icon: Activity, permission: 'web:read' },
    { name: 'API Security', path: '/api-security', icon: Network, permission: 'api:read' },
    { name: 'Reports', path: '/reports', icon: FileText, permission: 'web:read' },
    { name: 'Policies', path: '/policies', icon: Shield, permission: 'web:read' },
  ].filter(item => can(item.permission));

  return (
    <aside className="hidden h-screen w-60 shrink-0 flex-col border-r border-sidebar-border bg-sidebar lg:flex">
      <div className="flex h-16 items-center gap-3 border-b border-sidebar-border px-5">
        <div className="rounded-md bg-sidebar-primary/15 p-2 text-sidebar-primary">
          <Shield className="h-5 w-5" />
        </div>
        <div>
          <span className="block text-base font-semibold tracking-wide text-sidebar-foreground">VulnScope</span>
          <span className="block text-xs text-sidebar-foreground/55">Security assessment</span>
        </div>
      </div>
      <nav className="flex-1 space-y-1.5 overflow-y-auto px-3 py-5">
        {navItems.map((item) => {
          const isActive = location.pathname.startsWith(item.path);
          return (
            <Link
              key={item.name}
              to={item.path}
              className={clsx(
                "flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-colors",
                isActive 
                  ? "bg-sidebar-primary/12 text-sidebar-primary shadow-[inset_3px_0_0_hsl(var(--sidebar-primary))]" 
                  : "text-sidebar-foreground/72 hover:bg-sidebar-accent/70 hover:text-sidebar-accent-foreground"
              )}
            >
              <item.icon className="h-4 w-4" />
              <span>{item.name}</span>
            </Link>
          );
        })}
        {can('soc:read') && <details className="group pt-1" open={location.pathname.startsWith('/soc')}>
          <summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium", location.pathname.startsWith('/soc') ? "bg-sidebar-primary/12 text-sidebar-primary" : "text-sidebar-foreground/72 hover:bg-sidebar-accent/70")}><Radar className="h-4 w-4"/><span className="flex-1">SOC Monitor</span><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180"/></summary>
          <div className="ml-5 mt-1 space-y-0.5 border-l border-sidebar-border pl-2">
            {[['Overview','/soc','soc:read'],['Sources','/soc/sources','soc:read'],['Events','/soc/events','soc:read'],['Alerts','/soc/alerts','soc:read'],['Rules','/soc/rules','soc:manage_rules'],['Simulator','/soc/simulator','soc:simulate'],['Blocklist','/soc/blocklist','soc:manage_watchlist'],['Reports','/soc/reports','soc:read']].filter(([, , permission])=>can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs", location.pathname===path||path!=='/soc'&&location.pathname.startsWith(`${path}/`) ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:text-foreground')}>{name}</Link>)}
          </div>
        </details>}
        {can('document:read') && <details className="group pt-1" open={location.pathname.startsWith('/document-threats')}>
          <summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium", location.pathname.startsWith('/document-threats') ? "bg-sidebar-primary/12 text-sidebar-primary" : "text-sidebar-foreground/72 hover:bg-sidebar-accent/70")}><FileSearch className="h-4 w-4"/><span className="flex-1">Document Threats</span><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180"/></summary>
          <div className="ml-5 mt-1 space-y-0.5 border-l border-sidebar-border pl-2">{[['Overview','/document-threats','document:read'],['Analyze PDF','/document-threats/analyze','document:analyze'],['Analyses','/document-threats/analyses','document:read'],['Reports','/document-threats/reports','document:read']].filter(([, , permission])=>can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/document-threats'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div>
        </details>}
        {can('phishing:read') && <details className="group pt-1" open={location.pathname.startsWith('/phishing-defense')}>
          <summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/phishing-defense')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><MailWarning className="h-4 w-4"/><span className="flex-1">Phishing Defense</span><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180"/></summary>
          <div className="ml-5 mt-1 space-y-0.5 border-l border-sidebar-border pl-2">{[['Overview','/phishing-defense','phishing:read'],['Analyze','/phishing-defense/analyze','phishing:analyze'],['Analyses','/phishing-defense/analyses','phishing:read'],['Watchlist','/phishing-defense/watchlist','phishing:read'],['Model','/phishing-defense/model','phishing:read'],['Reports','/phishing-defense/reports','phishing:read']].filter(([, , permission])=>can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/phishing-defense'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div>
        </details>}
        {(can('correlation:read') || can('cases:read')) && <details className="group pt-1" open={location.pathname.startsWith('/correlation')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/correlation')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><GitMerge className="h-4 w-4"/><span className="flex-1">Correlation & Cases</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/correlation'],['Entities','/correlation/entities'],['Matches','/correlation/matches'],['Cases','/correlation/cases'],['Reports','/correlation/reports']].filter(([,p])=>p.includes('/cases')?can('cases:read'):can('correlation:read')).map(([n,p])=><Link key={p} to={p} className="block rounded px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground">{n}</Link>)}</div></details>}
        {can('governance:read') && <details className="group pt-1" open={location.pathname.startsWith('/governance')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/governance')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><Scale className="h-4 w-4"/><span className="flex-1">Governance & Reporting</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/governance'],['Risk Register','/governance/risks'],['Frameworks','/governance/frameworks'],['Mapping Review','/governance/mappings'],['Treatments','/governance/treatments'],['Exceptions','/governance/exceptions'],['Evidence Packages','/governance/evidence'],['Governance Reviews','/governance/reviews'],['Reports','/governance/reports']].map(([n,p])=><Link key={p} to={p} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===p||p!=='/governance'&&location.pathname.startsWith(`${p}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{n}</Link>)}</div></details>}
        {can('threat_intel:view') && <details className="group pt-1" open={location.pathname.startsWith('/threat-intelligence')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/threat-intelligence')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><ShieldAlert className="h-4 w-4"/><span className="flex-1">Threat Intelligence</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/threat-intelligence'],['Indicators','/threat-intelligence/indicators'],['Sources','/threat-intelligence/sources'],['Imports','/threat-intelligence/imports'],['Watchlists','/threat-intelligence/watchlists'],['Campaigns','/threat-intelligence/campaigns'],['Sightings','/threat-intelligence/sightings'],['Matches','/threat-intelligence/matches'],['Reports','/threat-intelligence/reports']].filter(([,path])=>!path.endsWith('/imports')||can('threat_intel:import')).filter(([,path])=>!path.endsWith('/reports')||can('threat_intel:export')).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/threat-intelligence'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {can('detections:view') && <details className="group pt-1" open={location.pathname.startsWith('/detections')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/detections')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><Radar className="h-4 w-4"/><span className="flex-1">Detection Engineering</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/detections'],['Rules','/detections/rules'],['Sigma Import','/detections/import'],['Rule Packs','/detections/packs'],['ATT&CK Coverage','/detections/coverage'],['Executions','/detections/executions'],['Matches','/detections/matches'],['Suppressions','/detections/suppressions'],['Reports','/detections/reports']].filter(([,path])=>path!=='/detections/import'||can('detections:import')).filter(([,path])=>path!=='/detections/executions'||can('detections:execute')).filter(([,path])=>path!=='/detections/suppressions'||can('detections:manage')).filter(([,path])=>path!=='/detections/reports'||can('detections:export')).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/detections'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {(can('vulnerabilities:view') || can('vulnerabilities:aggregate')) && <details className="group pt-1" open={location.pathname.startsWith('/vulnerability-management')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/vulnerability-management')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><ShieldAlert className="h-4 w-4"/><span className="flex-1">Vulnerability Management</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/vulnerability-management','vulnerabilities:aggregate'],['Assets','/vulnerability-management/assets','assets:view'],['Vulnerabilities','/vulnerability-management/vulnerabilities','vulnerabilities:view'],['Remediation Plans','/vulnerability-management/plans','vulnerabilities:view'],['SLA Dashboard','/vulnerability-management/sla','vulnerabilities:view'],['Risk Acceptances','/vulnerability-management/risk-acceptances','vulnerabilities:view'],['Verification Queue','/vulnerability-management/verifications','vulnerabilities:view'],['Remediation Library','/vulnerability-management/library','vulnerabilities:view'],['Reports','/vulnerability-management/reports','vulnerabilities:export']].filter(([,path,permission])=>path==='/vulnerability-management'?can('vulnerabilities:view')||can(permission):can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/vulnerability-management'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {can('soar:view') && <details className="group pt-1" open={location.pathname.startsWith('/soar')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/soar')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><Workflow className="h-4 w-4"/><span className="flex-1">SOAR-Lite</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/soar','soar:view'],['Playbooks','/soar/playbooks','soar:view'],['Templates','/soar/templates','soar:view'],['Triggers','/soar/triggers','soar:view'],['Executions','/soar/executions','soar:view'],['Approvals','/soar/approvals','soar:view'],['Analyst Inputs','/soar/analyst-inputs','soar:view'],['Actions','/soar/actions','soar:view'],['Action Policies','/soar/action-policies','soar:action_policy_manage'],['Rollbacks','/soar/rollbacks','soar:view'],['Reports','/soar/reports','soar:export']].filter(([, , permission])=>can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/soar'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {can('integrations:view') && <details className="group pt-1" open={location.pathname.startsWith('/integrations')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/integrations')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><Cable className="h-4 w-4"/><span className="flex-1">Integration Hub</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[['Overview','/integrations','integrations:view'],['Catalog','/integrations/catalog','integrations:view'],['Connectors','/integrations/connectors','integrations:view'],['Subscriptions','/integrations/subscriptions','integrations:view'],['Mappings','/integrations/mappings','integrations:view'],['Outbox','/integrations/outbox','integrations:view'],['Deliveries','/integrations/deliveries','integrations:view'],['Dead Letters','/integrations/dead-letters','integrations:view'],['Inbound Endpoints','/integrations/inbound-endpoints','integrations:view'],['Inbound Events','/integrations/inbound-events','integrations:view'],['Health','/integrations/health','integrations:view'],['External References','/integrations/external-references','integrations:view'],['Reports','/integrations/reports','integrations:export']].filter(([, , permission])=>can(permission)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/integrations'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {can('operations:view') && <details className="group pt-1" open={location.pathname.startsWith('/operations')}><summary className={clsx("flex cursor-pointer list-none items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium",location.pathname.startsWith('/operations')?'bg-sidebar-primary/12 text-sidebar-primary':'text-sidebar-foreground/72 hover:bg-sidebar-accent/70')}><Wrench className="h-4 w-4"/><span className="flex-1">Operations</span><ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><div className="ml-5 mt-1 space-y-0.5 border-l pl-2">{[
          ['Overview','/operations','operations:view'],['Health','/operations/health','operations:diagnostics'],['Diagnostics','/operations/diagnostics','operations:diagnostics'],['Configuration','/operations/configuration','operations:diagnostics'],['Jobs','/operations/jobs','operations:maintenance'],['Backups','/operations/backups','operations:backup'],['Restores','/operations/restores','operations:restore'],['Exports','/operations/exports','operations:export'],['Retention','/operations/retention','operations:retention'],['Demo Environment','/operations/demo','operations:demo_manage'],['Software Inventory','/operations/inventory','operations:inventory'],['Releases','/operations/releases','operations:release']
        ].filter(([name, , permission])=>can(permission) && (name!=='Demo Environment'||demoMode)).map(([name,path])=><Link key={path} to={path} className={clsx("block rounded px-3 py-1.5 text-xs",location.pathname===path||path!=='/operations'&&location.pathname.startsWith(`${path}/`)?'bg-primary/10 text-primary':'text-muted-foreground hover:text-foreground')}>{name}</Link>)}</div></details>}
        {can('users:read') && <Link to="/admin/users" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent"><Users className="h-4 w-4"/>Users</Link>}
        {can('users:manage') && <Link to="/admin/registrations" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent"><User className="h-4 w-4"/>Registrations</Link>}
        {can('roles:read') && <Link to="/admin/roles" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent"><KeyRound className="h-4 w-4"/>Roles</Link>}
        {can('audit:read') && <Link to="/security-audit" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent"><ScrollText className="h-4 w-4"/>Security Audit</Link>}
      </nav>
      <div className="border-t border-border p-3">
        <Link to="/profile/security" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><User className="h-4 w-4"/>Security</Link>
        {can('system:manage') && <Link to="/settings" className={clsx("flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-colors", location.pathname === '/settings' ? 'bg-primary/15 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground')}>
          <Settings className="h-4 w-4" /><span>Settings</span>
        </Link>}
      </div>
    </aside>
  );
}
