import { useState, type FormEvent, type ReactNode } from 'react';

const badge=(value:string,tone='slate')=><span className={`inline-flex rounded-full border border-${tone}-400/30 bg-${tone}-500/10 px-2 py-0.5 text-xs uppercase tracking-wide`}>{value.replaceAll('_',' ')}</span>;
export const ConnectorStatusBadge=({status}:{status:string})=>badge(status,status==='active'?'emerald':status==='degraded'?'amber':'slate');
export const ConnectorHealthBadge=({status}:{status:string})=>badge(status,status==='healthy'?'emerald':status==='unhealthy'?'red':'amber');
export const ConnectorDirectionBadge=({direction}:{direction:string})=>badge(direction,'sky');
export const ConnectorTypeBadge=({type}:{type:string})=>badge(type,'violet');
export const CredentialStatusBadge=({configured}:{configured:boolean})=>badge(configured?'configured':'not configured',configured?'emerald':'amber');
export const NetworkScopeBadge=({scope}:{scope:string})=>badge(scope,scope==='approved_private'?'amber':'sky');
export const CircuitStateBadge=({state}:{state:string})=>badge(state,state==='open'?'red':'emerald');
export const DeliveryStatusBadge=({status}:{status:string})=>badge(status,status==='succeeded'?'emerald':status==='dead_letter'?'red':'amber');
export const InboundEventStatusBadge=({status}:{status:string})=>badge(status,status==='promoted'?'emerald':'amber');
export const SignatureStatusBadge=({status}:{status:string})=>badge(status,status==='valid'?'emerald':'red');
export const ReplayStatusBadge=({status}:{status:string})=>badge(status,status==='accepted'?'emerald':'red');
export const PayloadProfileBadge=({profile}:{profile:string})=>badge(profile,profile==='extended'?'amber':'sky');

export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-xl border border-border bg-card p-4"><h2 className="mb-3 font-semibold">{title}</h2>{children}</section>}
export const JsonView=({value}:{value:unknown})=><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-muted p-3 text-xs">{JSON.stringify(value,null,2)}</pre>;
const input="w-full rounded-md border border-border bg-background px-3 py-2 text-sm";
const button="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50";

export function ConnectorConfigurationForm({initial={},onSubmit}:{initial?:Record<string,unknown>;onSubmit:(value:Record<string,unknown>)=>void}){const [name,setName]=useState(String(initial.name||''));const [configuration,setConfiguration]=useState(JSON.stringify(initial.configuration||{},null,2));const submit=(e:FormEvent)=>{e.preventDefault();onSubmit({name,configuration:JSON.parse(configuration||'{}')})};return <form className="space-y-3" onSubmit={submit}><label className="block text-sm">Name<input className={input} value={name} maxLength={160} required onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">Bounded configuration JSON<textarea className={`${input} min-h-40 font-mono`} value={configuration} onChange={e=>setConfiguration(e.target.value)}/></label><button className={button}>Save disabled draft</button></form>}
export function ConnectorCredentialForm({onSubmit}:{onSubmit:(secret:string)=>void}){const [secret,setSecret]=useState('');return <form className="space-y-3" onSubmit={e=>{e.preventDefault();onSubmit(secret);setSecret('')}}><SecretWarningPanel/><label className="block text-sm">Write-only secret<input className={input} type="password" autoComplete="new-password" value={secret} minLength={16} required onChange={e=>setSecret(e.target.value)}/></label><button className={button}>Store encrypted credential</button></form>}
export function CredentialRotationDialog({onRotate}:{onRotate:(secret:string)=>void}){const [secret,setSecret]=useState('');return <Panel title="Rotate credential"><input aria-label="Replacement secret" className={input} type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)}/><button className={`${button} mt-2`} disabled={secret.length<16} onClick={()=>{onRotate(secret);setSecret('')}}>Confirm rotation</button></Panel>}
export function NetworkPolicyForm({value,onSubmit}:{value:Record<string,unknown>;onSubmit:(v:Record<string,unknown>)=>void}){const [host,setHost]=useState(String((value.allowed_hosts as string[]|undefined)?.[0]||''));const [scope,setScope]=useState(String(value.network_scope||'public_https'));return <form className="space-y-3" onSubmit={e=>{e.preventDefault();onSubmit({network_scope:scope,allowed_hosts:host?[host]:[],allowed_ports:[443],allowed_cidrs:[],redirect_policy:'deny',maximum_request_bytes:262144,maximum_response_bytes:524288,reason:scope==='approved_private'?'Administrator-approved private integration':undefined,confirmation:scope==='approved_private'?'APPROVE PRIVATE EGRESS':undefined})}}><SSRFWarningPanel/><select className={input} value={scope} onChange={e=>setScope(e.target.value)}><option value="public_https">Public HTTPS</option><option value="approved_private">Approved private</option></select><input className={input} placeholder="Exact hostname; wildcards prohibited" value={host} onChange={e=>setHost(e.target.value)}/><button className={button}>Save and require retest</button></form>}
export function ConnectorTestPanel({result,onTest}:{result?:unknown;onTest:()=>void}){return <Panel title="Bounded connector test"><p className="mb-2 text-sm text-muted-foreground">Tests configuration, credential availability, DNS policy, TLS requirements, and capability without exposing secrets.</p><button className={button} onClick={onTest}>Run safe test</button>{Boolean(result)&&<JsonView value={result}/>}</Panel>}
export function HealthCheckTimeline({items}:{items:Record<string,unknown>[]}){return <Panel title="Health check timeline">{items.length?items.map((x,i)=><div key={String(x.id||i)} className="border-b py-2 text-sm"><ConnectorHealthBadge status={String(x.status||'unknown')}/> {String(x.summary||'')}</div>):<p className="text-sm text-muted-foreground">No health checks yet.</p>}</Panel>}
export function SubscriptionFilterBuilder({onChange}:{onChange:(v:Record<string,unknown>)=>void}){const [severity,setSeverity]=useState('high');return <label className="block text-sm">Minimum severity<select className={input} value={severity} onChange={e=>{setSeverity(e.target.value);onChange({minimum_severity:e.target.value})}}>{['info','low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label>}
export function MappingEditor({onChange}:{onChange:(v:Record<string,unknown>[])=>void}){const [text,setText]=useState('[{"target":"title","source":"title","transform":"truncate","length":240}]');return <textarea aria-label="Declarative mapping" className={`${input} min-h-48 font-mono`} value={text} onChange={e=>{setText(e.target.value);try{onChange(JSON.parse(e.target.value))}catch{/* server validation remains authoritative */}}}/>}
export const MappingPreviewPanel=({value}:{value:unknown})=><Panel title="Mapping preview"><JsonView value={value||{message:'Preview a declarative mapping; no code or network is executed.'}}/></Panel>;
export function DeliveryTimeline({delivery,attempts}:{delivery:Record<string,unknown>;attempts:Record<string,unknown>[]}){return <Panel title="Delivery timeline"><DeliveryStatusBadge status={String(delivery.status||'queued')}/>{attempts.map((x,i)=><div className="mt-2 border-t pt-2 text-sm" key={String(x.id||i)}>Attempt {String(x.attempt_number||i+1)} — {String(x.status)}</div>)}</Panel>}
export const DeliveryAttemptPanel=({attempt}:{attempt?:Record<string,unknown>})=><Panel title="Latest safe attempt"><JsonView value={attempt||{message:'No attempt recorded'}}/></Panel>;
export function DeadLetterReplayDialog({onReplay}:{onReplay:(reason:string)=>void}){const [reason,setReason]=useState('');return <Panel title="Manual dead-letter replay"><textarea className={input} placeholder="Required replay reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className={`${button} mt-2`} disabled={reason.trim().length<3} onClick={()=>onReplay(reason)}>Revalidate and create new delivery</button></Panel>}
export const InboundEventPreview=({event}:{event:Record<string,unknown>})=><Panel title="Quarantined inbound preview"><div className="mb-2 flex gap-2"><InboundEventStatusBadge status={String(event.status||'quarantined')}/><SignatureStatusBadge status={String(event.signature_status||'unknown')}/><ReplayStatusBadge status={String(event.replay_status||'unknown')}/></div><JsonView value={event.raw_payload_redacted||{}}/></Panel>;
export function InboundPromotionDialog({onPromote}:{onPromote:(target:string)=>void}){const [target,setTarget]=useState('analyst_review_task');return <Panel title="Explicit inbound promotion"><select className={input} value={target} onChange={e=>setTarget(e.target.value)}>{['soc_alert','threat_intelligence','case_evidence_proposal','vulnerability_evidence_proposal','analyst_review_task'].map(x=><option key={x}>{x}</option>)}</select><button className={`${button} mt-2`} onClick={()=>onPromote(target)}>Confirm safe promotion</button></Panel>}
export const DataEgressSummary=({profile='minimal'}:{profile?:string})=><Panel title="Data egress"><PayloadProfileBadge profile={profile}/><p className="mt-2 text-sm text-muted-foreground">Redacted canonical fields only. Credentials, sessions, MFA material, raw files, hostile HTML, and unbounded evidence are always excluded.</p></Panel>;
export const SSRFWarningPanel=()=> <div className="rounded-md border border-amber-500/40 bg-amber-500/10 p-3 text-sm">Public HTTPS and port 443 are the default. DNS answers are revalidated; localhost, metadata, loopback, link-local, reserved, and private addresses are blocked unless narrowly approved.</div>;
export const SecretWarningPanel=()=> <div className="rounded-md border border-red-500/40 bg-red-500/10 p-3 text-sm">Secrets are write-only, encrypted by the server, never prepopulated, logged, reported, or stored in browser storage.</div>;
export const ExternalReferencePanel=({item}:{item?:Record<string,unknown>})=><Panel title="External reference">{item?<p className="break-all text-sm">{String(item.external_system_type)} · {String(item.external_reference_id)} (navigation requires host validation)</p>:<p className="text-sm text-muted-foreground">No external reference.</p>}</Panel>;
export const ConnectorMetricsPanel=({metrics}:{metrics:Record<string,unknown>})=><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(metrics).slice(0,20).map(([k,v])=><div key={k} className="rounded-lg border border-border bg-card p-3"><div className="text-xs uppercase text-muted-foreground">{k.replaceAll('_',' ')}</div><div className="mt-1 text-2xl font-semibold">{v===null?'not available':String(v)}</div></div>)}</div>;
