import { useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../auth/useAuth';
import { integrationsApi, type IntegrationRecord } from '../../api/integrations';
import { CircuitStateBadge, ConnectorConfigurationForm, ConnectorCredentialForm, ConnectorDirectionBadge, ConnectorHealthBadge, ConnectorMetricsPanel, ConnectorStatusBadge, ConnectorTestPanel, ConnectorTypeBadge, CredentialRotationDialog, CredentialStatusBadge, DataEgressSummary, DeadLetterReplayDialog, DeliveryAttemptPanel, DeliveryStatusBadge, DeliveryTimeline, ExternalReferencePanel, HealthCheckTimeline, InboundEventPreview, InboundEventStatusBadge, InboundPromotionDialog, JsonView, MappingEditor, MappingPreviewPanel, NetworkPolicyForm, NetworkScopeBadge, Panel, PayloadProfileBadge, ReplayStatusBadge, SSRFWarningPanel, SecretWarningPanel, SignatureStatusBadge, SubscriptionFilterBuilder } from './components';

const button='rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50';
function Layout({title,subtitle,actions,children}:{title:string;subtitle:string;actions?:ReactNode;children:ReactNode}){return <main className="mx-auto max-w-7xl space-y-5 p-4 md:p-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{subtitle}</p></div>{actions}</header>{children}</main>}
function State({loading,error,empty}:{loading:boolean;error:string;empty?:boolean}){if(loading)return <div role="status" className="rounded-lg border p-6">Loading integration data…</div>;if(error)return <div role="alert" className="rounded-lg border border-red-500/40 p-6">{error}</div>;if(empty)return <div className="rounded-lg border border-dashed p-8 text-center text-muted-foreground">No authorized integration records found.</div>;return null}
function useLoad<T>(loader:()=>Promise<T>,deps:unknown[]=[]){const [data,setData]=useState<T>();const [loading,setLoading]=useState(true);const [error,setError]=useState('');const refresh=async()=>{setLoading(true);setError('');try{setData(await loader())}catch(e){setError(e instanceof Error?e.message:'Unable to load integration data')}finally{setLoading(false)}};useEffect(()=>{void refresh()},deps);return{data,loading,error,refresh}}
function Table({items,base}:{items:IntegrationRecord[];base?:string}){return <div className="overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr><th className="p-3">Record</th><th className="p-3">Status</th><th className="p-3">Details</th></tr></thead><tbody>{items.map(x=><tr className="border-t" key={x.id}><td className="p-3">{String(x.name||x.title||x.delivery_uuid||x.inbound_event_uuid||x.report_uuid||`#${x.id}`)}</td><td className="p-3">{x.status?<DeliveryStatusBadge status={String(x.status)}/>:x.lifecycle_status?<ConnectorStatusBadge status={String(x.lifecycle_status)}/>:<span>configured</span>}</td><td className="p-3">{base?<Link className="text-primary underline" to={`${base}/${x.id}`}>Open</Link>:<span className="text-muted-foreground">Safe summary</span>}</td></tr>)}</tbody></table></div>}
const list=(value:unknown)=>(value as {items?:IntegrationRecord[]}|undefined)?.items||[];

export function IntegrationsOverviewPage(){const q=useLoad(()=>integrationsApi.overview(),[]);return <Layout title="Integration Hub" subtitle="Safe-by-default connectors, signed inbound events, transactional delivery, retries, circuits, dead letters, and encrypted write-only credentials."><State loading={q.loading} error={q.error}/>{q.data&&<><ConnectorMetricsPanel metrics={q.data}/><div className="grid gap-4 lg:grid-cols-2"><DataEgressSummary/><SSRFWarningPanel/></div></>}</Layout>}
export function ConnectorCatalogPage(){const q=useLoad(()=>integrationsApi.catalog(),[]);return <Layout title="Server-owned connector catalog" subtitle="Immutable backend definitions only; arbitrary connector code, containment, SQL, scripts, and custom REST paths are prohibited."><State loading={q.loading} error={q.error} empty={!q.data?.items.length}/><div className="grid gap-4 md:grid-cols-2">{q.data?.items.map(x=><Panel key={x.connector_type} title={x.display_name}><div className="flex flex-wrap gap-2"><ConnectorTypeBadge type={x.connector_type}/><ConnectorDirectionBadge direction={x.direction}/></div><p className="mt-3 text-sm text-muted-foreground">{x.description}</p>{x.warning_message&&<p className="mt-2 text-sm text-amber-200">{x.warning_message}</p>}</Panel>)}</div></Layout>}
export function ConnectorsPage(){const q=useLoad(()=>integrationsApi.connectors(),[]);const {can}=useAuth();return <Layout title="Connectors" subtitle="Lifecycle, health, egress, and circuit state remain backend-authoritative." actions={can('integrations:manage')?<Link className={button} to="/integrations/connectors/new">Create connector</Link>:undefined}><State loading={q.loading} error={q.error} empty={!q.data?.items.length}/>{q.data&&<Table items={q.data.items} base="/integrations/connectors"/>}</Layout>}
export function ConnectorCreatePage(){const catalog=useLoad(()=>integrationsApi.catalog(),[]);const navigate=useNavigate();const [type,setType]=useState('local_test_sink');const [error,setError]=useState('');return <Layout title="Create connector" subtitle="Wizard: type, service, network, authentication, data egress, validation, test, then explicit activation."><State loading={catalog.loading} error={catalog.error}/><Panel title="1. Select server-owned type"><select className="w-full rounded border bg-background p-2" value={type} onChange={e=>setType(e.target.value)}>{catalog.data?.items.map(x=><option key={x.connector_type} value={x.connector_type}>{x.display_name}</option>)}</select></Panel><Panel title="2–7. Disabled draft configuration"><ConnectorConfigurationForm onSubmit={v=>void integrationsApi.createConnector({connector_type:type,name:v.name,configuration:v.configuration,payload_profile:'minimal'}).then(x=>navigate(`/integrations/connectors/${x.id}`)).catch(e=>setError(String(e)))}/>{error&&<p role="alert">{error}</p>}<DataEgressSummary/></Panel></Layout>}
export function ConnectorDetailsPage(){const {connectorId}=useParams();const q=useLoad(()=>integrationsApi.connector(connectorId||''),[connectorId]);const health=useLoad(()=>integrationsApi.connectorHealthChecks(connectorId||''),[connectorId]);const [testResult,setTestResult]=useState<unknown>();const {can}=useAuth();const action=async(name:'move-to-testing'|'activate'|'disable'|'archive')=>{if(!q.data)return;await integrationsApi.lifecycle(q.data.id,name,q.data.optimistic_lock_version,'Explicit connector lifecycle review');await q.refresh()};return <Layout title={q.data?.name||'Connector details'} subtitle="Configuration contains no credentials. Secret status and network policy are isolated behind separate Administrator controls."><State loading={q.loading} error={q.error}/>{q.data&&<><div className="flex flex-wrap gap-2"><ConnectorTypeBadge type={q.data.connector_type}/><ConnectorDirectionBadge direction={q.data.direction}/><ConnectorStatusBadge status={q.data.lifecycle_status}/><ConnectorHealthBadge status={q.data.health_status}/><CircuitStateBadge state={q.data.circuit_state}/><PayloadProfileBadge profile={q.data.payload_profile}/></div><div className="flex flex-wrap gap-2">{can('integrations:manage')&&(['draft','disabled'].includes(q.data.lifecycle_status))&&<button className={button} onClick={()=>void action('move-to-testing')}>Move to testing</button>}{can('integrations:manage')&&['testing','disabled','degraded'].includes(q.data.lifecycle_status)&&<button className={button} onClick={()=>void action('activate')}>Activate after test</button>}{can('integrations:manage')&&['active','degraded'].includes(q.data.lifecycle_status)&&<button className={button} onClick={()=>void action('disable')}>Disable</button>}<Link className={button} to={`/integrations/connectors/${q.data.id}/edit`}>Edit</Link>{can('integrations:credentials_manage')&&<Link className={button} to={`/integrations/connectors/${q.data.id}/credentials`}>Credentials</Link>}{can('integrations:network_policy_manage')&&<Link className={button} to={`/integrations/connectors/${q.data.id}/network-policy`}>Network policy</Link>}</div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Safe configuration"><JsonView value={q.data.configuration}/></Panel><ConnectorTestPanel result={testResult} onTest={()=>void integrationsApi.testConnector(q.data!.id).then(setTestResult).then(q.refresh)}/><HealthCheckTimeline items={health.data?.items||[]}/><DataEgressSummary profile={q.data.payload_profile}/></div></>}</Layout>}
export function ConnectorEditPage(){const {connectorId}=useParams();const q=useLoad(()=>integrationsApi.connector(connectorId||''),[connectorId]);const navigate=useNavigate();return <Layout title="Edit connector" subtitle="Configuration changes invalidate prior health and require validation and retest."><State loading={q.loading} error={q.error}/>{q.data&&<ConnectorConfigurationForm initial={q.data} onSubmit={v=>void integrationsApi.updateConnector(q.data!.id,{...v,optimistic_lock_version:q.data!.optimistic_lock_version}).then(x=>navigate(`/integrations/connectors/${x.id}`))}/>}</Layout>}
export function ConnectorTestPage(){const {connectorId}=useParams();const [result,setResult]=useState<unknown>();return <Layout title="Connector test" subtitle="Bounded test results omit credentials, headers, response bodies, and DNS internals."><ConnectorTestPanel result={result} onTest={()=>void integrationsApi.testConnector(connectorId||'').then(setResult)}/></Layout>}
export function ConnectorCredentialsPage(){const {connectorId}=useParams();const q=useLoad(()=>integrationsApi.credentialStatus(connectorId||''),[connectorId]);return <Layout title="Write-only credentials" subtitle="Stored secrets are never returned, prepopulated, placed in routes, or cached in browser storage."><State loading={q.loading} error={q.error}/>{q.data&&<div className="space-y-4"><CredentialStatusBadge configured={q.data.configured}/><p>Version {q.data.version}; suffix {q.data.last_four||'not displayed'}; key {q.data.key_available?'available':'unavailable — operations fail closed'}.</p><ConnectorCredentialForm onSubmit={secret=>void integrationsApi.putCredential(connectorId||'',{credential_type:'hmac_signing',secret:{signing_secret:secret},confirmation:'STORE WRITE ONLY'}).then(q.refresh)}/><CredentialRotationDialog onRotate={secret=>void integrationsApi.rotateCredential(connectorId||'',{credential_type:'hmac_signing',secret:{signing_secret:secret},confirmation:'ROTATE WRITE ONLY'}).then(q.refresh)}/><SecretWarningPanel/></div>}</Layout>}
export function ConnectorNetworkPolicyPage(){const {connectorId}=useParams();const q=useLoad(()=>integrationsApi.networkPolicy(connectorId||''),[connectorId]);return <Layout title="Connector network policy" subtitle="Exact host and port allowlists, DNS answer validation, TLS verification, no metadata, and no redirects by default."><State loading={q.loading} error={q.error}/>{q.data&&<><NetworkScopeBadge scope={String(q.data.network_scope)}/><NetworkPolicyForm value={q.data} onSubmit={v=>void integrationsApi.updateNetworkPolicy(connectorId||'',v).then(q.refresh)}/></>}</Layout>}
export function SubscriptionsPage(){const q=useLoad(()=>integrationsApi.subscriptions(),[]);return <Layout title="Event subscriptions" subtitle="Declarative filters only; no Python, SQL, Jinja, JavaScript, or unbounded regex."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/><SubscriptionFilterBuilder onChange={()=>undefined}/>{q.data&&<Table items={q.data.items} base="/integrations/subscriptions"/>}</Layout>}
export function SubscriptionDetailsPage(){const {subscriptionId}=useParams();const q=useLoad(()=>integrationsApi.subscription(subscriptionId||''),[subscriptionId]);return <Layout title="Subscription details" subtitle="Event compatibility, delivery mode, mapping, and bounded filter."><State loading={q.loading} error={q.error}/>{q.data&&<JsonView value={q.data}/>}</Layout>}
export function MappingsPage(){const q=useLoad(()=>integrationsApi.mappings(),[]);return <Layout title="Field mappings" subtitle="Allowlisted declarative transforms with bounded path depth and count." actions={<Link className={button} to="/integrations/mappings/new">New mapping</Link>}><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/mappings"/>}</Layout>}
export function MappingEditorPage(){const {mappingId}=useParams();const [rules,setRules]=useState<Record<string,unknown>[]>([]);const [preview,setPreview]=useState<unknown>();const navigate=useNavigate();const existing=useLoad(()=>mappingId?integrationsApi.mapping(mappingId):Promise.resolve(undefined),[mappingId]);const save=()=>{const data={name:String(existing.data?.name||'Safe integration mapping'),direction:String(existing.data?.direction||'outbound'),source_schema:String(existing.data?.source_schema||'threatscope.integration.event.v1'),target_schema:String(existing.data?.target_schema||'connector.payload.v1'),mapping:rules};void (mappingId?integrationsApi.updateMapping(mappingId,data):integrationsApi.createMapping(data)).then(x=>navigate(`/integrations/mappings/${x.id}`))};return <Layout title="Declarative mapping editor" subtitle="Direct, constant, default, case, trim, truncate, concatenate, list, conversion, datetime, enum, severity, and bounded condition transforms only."><State loading={existing.loading} error={existing.error}/><MappingEditor onChange={setRules}/><div className="flex gap-2"><button className={button} onClick={save}>Validate and save</button>{mappingId&&<button className={button} onClick={()=>void integrationsApi.previewMapping(mappingId,{title:'Preview event',severity:'high'}).then(setPreview)}>Preview</button>}</div><MappingPreviewPanel value={preview}/></Layout>}
export function OutboxPage(){const q=useLoad(()=>integrationsApi.outbox(),[]);return <Layout title="Transactional outbox" subtitle="Redacted canonical events are append-only and delivered only after source transaction commit."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items}/>}</Layout>}
export function DeliveriesPage(){const q=useLoad(()=>integrationsApi.deliveries(),[]);return <Layout title="Outbound deliveries" subtitle="Bounded idempotent delivery, retry, circuit breaker, cancellation, and terminal history."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/deliveries"/>}</Layout>}
export function DeliveryDetailsPage(){const {deliveryId}=useParams();const q=useLoad(()=>integrationsApi.delivery(deliveryId||''),[deliveryId]);const attempts=useLoad(()=>integrationsApi.attempts(deliveryId||''),[deliveryId]);return <Layout title="Delivery details" subtitle="Safe payload and attempt metadata; authorization headers, credentials, and raw responses are never displayed."><State loading={q.loading||attempts.loading} error={q.error||attempts.error}/>{q.data&&<><DeliveryTimeline delivery={q.data} attempts={attempts.data||[]}/><DeliveryAttemptPanel attempt={attempts.data?.at(-1)}/><DataEgressSummary profile={q.data.payload_profile}/></>}</Layout>}
export function DeadLettersPage(){const q=useLoad(()=>integrationsApi.deadLetters(),[]);return <Layout title="Dead letters" subtitle="Terminal delivery records are immutable and never replay automatically."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/dead-letters"/>}</Layout>}
export function DeadLetterDetailsPage(){const {deadLetterId}=useParams();const q=useLoad(()=>integrationsApi.deadLetter(deadLetterId||''),[deadLetterId]);return <Layout title="Dead-letter details" subtitle="Replay revalidates configuration, credential, connector status, and creates a new delivery."><State loading={q.loading} error={q.error}/>{q.data&&<><JsonView value={q.data}/><DeadLetterReplayDialog onReplay={reason=>void integrationsApi.replayDeadLetter(q.data!.id,reason).then(q.refresh)}/></>}</Layout>}
export function InboundEndpointsPage(){const q=useLoad(()=>integrationsApi.inboundEndpoints(),[]);return <Layout title="Signed inbound endpoints" subtitle="Endpoint UUIDs are identifiers, not authentication. HMAC, timestamp, nonce, size, schema, and rate limits apply."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/inbound-endpoints"/>}</Layout>}
export function InboundEndpointDetailsPage(){const {endpointId}=useParams();const q=useLoad(()=>integrationsApi.inboundEndpoint(endpointId||''),[endpointId]);return <Layout title="Inbound endpoint" subtitle="Quarantine-first signed ingress with write-only secret rotation."><State loading={q.loading} error={q.error}/>{q.data&&<><JsonView value={q.data}/><SecretWarningPanel/></>}</Layout>}
export function InboundEventsPage(){const q=useLoad(()=>integrationsApi.inboundEvents(),[]);return <Layout title="Quarantined inbound events" subtitle="Signed external data cannot mutate protected domains until bounded mapping, trust, duplicate, and permission checks pass."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/inbound-events"/>}</Layout>}
export function InboundEventDetailsPage(){const {eventId}=useParams();const q=useLoad(()=>integrationsApi.inboundEvent(eventId||''),[eventId]);return <Layout title="Inbound event details" subtitle="Redacted payload, signature/replay state, normalized preview, and explicit promotion."><State loading={q.loading} error={q.error}/>{q.data&&<><InboundEventPreview event={q.data}/><InboundPromotionDialog onPromote={target=>void integrationsApi.promoteInbound(q.data!.id,target).then(q.refresh)}/></>}</Layout>}
export function HealthChecksPage(){const q=useLoad(()=>integrationsApi.healthChecks(),[]);return <Layout title="Connector health" subtitle="Configuration, credential, connectivity, authentication, and capability checks are bounded and secret-free."><State loading={q.loading} error={q.error}/><HealthCheckTimeline items={list(q.data)}/></Layout>}
export function ExternalReferencesPage(){const q=useLoad(()=>integrationsApi.externalReferences(),[]);return <Layout title="External ticket references" subtitle="Validated Jira and ServiceNow references link safely to cases without deletion or silent bidirectional overwrite."><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{list(q.data).map(x=><ExternalReferencePanel key={x.id} item={x}/>)}</Layout>}
export function IntegrationReportsPage(){const q=useLoad(()=>integrationsApi.reports(),[]);return <Layout title="Integration reports" subtitle="Static self-contained escaped HTML, 44 sections, no scripts, links, remote assets, secrets, raw responses, or containment claims." actions={<button className={button} onClick={()=>void integrationsApi.createReport({title:'ThreatScope Integration Hub Report',report_type:'integration_summary',filters:{}}).then(q.refresh)}>Generate report</button>}><State loading={q.loading} error={q.error} empty={!list(q.data).length}/>{q.data&&<Table items={q.data.items} base="/integrations/reports"/>}</Layout>}
export function IntegrationReportDetailsPage(){const {reportId}=useParams();const q=useLoad(()=>integrationsApi.report(reportId||''),[reportId]);const download=async()=>{const blob=await integrationsApi.downloadReport(reportId||'');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`integration-report-${reportId}.html`;a.click();URL.revokeObjectURL(url)};return <Layout title={String(q.data?.title||'Integration report')} subtitle="Report HTML is downloaded as a static artifact and never injected into the application DOM." actions={<button className={button} onClick={()=>void download()}>Download static HTML</button>}><State loading={q.loading} error={q.error}/>{q.data&&<JsonView value={q.data}/>}</Layout>}

// Exported badges remain visible in bounded detail pages and ensure status vocabularies are consistent.
export function IntegrationBadgeReference({record}:{record:Record<string,unknown>}){return <div className="flex flex-wrap gap-2"><ConnectorStatusBadge status={String(record.lifecycle_status||'draft')}/><ConnectorHealthBadge status={String(record.health_status||'unknown')}/><ConnectorDirectionBadge direction={String(record.direction||'outbound')}/><ConnectorTypeBadge type={String(record.connector_type||'local_test_sink')}/><CredentialStatusBadge configured={Boolean(record.credential_configured)}/><NetworkScopeBadge scope={String(record.network_scope||'public_https')}/><CircuitStateBadge state={String(record.circuit_state||'closed')}/><DeliveryStatusBadge status={String(record.status||'queued')}/><InboundEventStatusBadge status={String(record.inbound_status||'quarantined')}/><SignatureStatusBadge status={String(record.signature_status||'valid')}/><ReplayStatusBadge status={String(record.replay_status||'accepted')}/><PayloadProfileBadge profile={String(record.payload_profile||'minimal')}/></div>}
