import { useCallback, useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowLeft, Plus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import type { ApiBusinessFlow, ApiEndpoint } from '../../../types';
import { vulnscopeApi } from '../../../api/vulnscope';
import { PageHeader, PageShell, SectionCard } from '../../../components/ui';
import { FlowStepCard } from './FlowStepCard';

export function BusinessFlowEditor() {
  const flowId = Number(useParams().flowId);
  const [flow, setFlow] = useState<ApiBusinessFlow | null>(null); const [endpoints, setEndpoints] = useState<ApiEndpoint[]>([]);
  const [endpointId, setEndpointId] = useState<number | null>(null); const [action, setAction] = useState(''); const [actor, setActor] = useState(''); const [prerequisite, setPrerequisite] = useState(''); const [before, setBefore] = useState(''); const [after, setAfter] = useState(''); const [sensitive, setSensitive] = useState(false);
  const load = useCallback(async () => { const item = await vulnscopeApi.getBusinessFlow(flowId); setFlow(item); setEndpoints(await vulnscopeApi.listApiEndpoints(item.assessment_id)); }, [flowId]);
  useEffect(() => { void load().catch(() => toast.error('Flow editor could not be loaded.')); }, [load]);
  const add = async (event: FormEvent) => { event.preventDefault(); if (!flow) return; await vulnscopeApi.createBusinessFlowStep(flow.id, { step_order: flow.steps.length ? Math.max(...flow.steps.map(step => step.step_order)) + 1 : 1, endpoint_id: endpointId, action_name: action, expected_actor_role: actor || null, prerequisite_description: prerequisite || null, expected_state_before: before || null, expected_state_after: after || null, sensitive_operation: sensitive }); setAction(''); setPrerequisite(''); setBefore(''); setAfter(''); setSensitive(false); await load(); toast.success('Flow step added.'); };
  if (!flow) return <PageShell><p className="text-sm text-muted-foreground">Loading flow editor...</p></PageShell>;
  return <PageShell><PageHeader title={`Edit ${flow.name}`} subtitle="Ordered design metadata only. No imported endpoint is executed." actions={<Link to={`/api-security/business-flows/${flow.id}`} className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-4 text-sm font-semibold"><ArrowLeft className="h-4 w-4" />Flow details</Link>} />
    <div className="grid gap-6 xl:grid-cols-[400px_1fr]"><SectionCard title="Add Ordered Step"><form onSubmit={event => void add(event)} className="space-y-3"><label className="block text-xs font-semibold text-muted-foreground">Action name<input required value={action} onChange={event => setAction(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-muted-foreground">Imported endpoint<select value={endpointId || ''} onChange={event => setEndpointId(Number(event.target.value) || null)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm"><option value="">No endpoint</option>{endpoints.map(endpoint => <option key={endpoint.id} value={endpoint.id}>{endpoint.method} {endpoint.path}</option>)}</select></label><label className="block text-xs font-semibold text-muted-foreground">Expected actor role<input value={actor} onChange={event => setActor(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-muted-foreground">Prerequisite<textarea value={prerequisite} onChange={event => setPrerequisite(event.target.value)} rows={2} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label><div className="grid grid-cols-2 gap-2"><label className="block text-xs font-semibold text-muted-foreground">State before<input value={before} onChange={event => setBefore(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-muted-foreground">State after<input value={after} onChange={event => setAfter(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sensitive} onChange={event => setSensitive(event.target.checked)} />Sensitive operation</label><button className="inline-flex h-10 items-center gap-2 rounded-md bg-indigo-500 px-4 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Add step</button></form></SectionCard>
      <SectionCard title="Ordered Workflow" subtitle={`${flow.steps.length} step${flow.steps.length === 1 ? '' : 's'}`}><div className="space-y-5">{flow.steps.map(step => <FlowStepCard key={step.id} step={step} endpoint={endpoints.find(item => item.id === step.endpoint_id)} onDelete={() => void vulnscopeApi.deleteBusinessFlowStep(step.id).then(load)} />)}</div></SectionCard></div>
  </PageShell>;
}
