import hashlib, json
from pathlib import Path
RULES={r["rule_code"]:r for r in json.loads((Path(__file__).parent/"rules"/"phishing_rules.json").read_text())}
def build(source_hash,features,model_probability,watchlist_matches=0):
    codes=[];h=features["headers"];u=features["urls"];html=features["html"];t=features["text"];a=features["attachments"]
    for condition,code,evidence in [(h.get("reply_mismatch"),"PHISH-001","From and Reply-To domains differ."),(h.get("return_path_mismatch"),"PHISH-002","From and Return-Path domains differ."),(h.get("spf_failure"),"PHISH-003","Supplied header reports SPF failure; no live verification performed."),(h.get("dkim_failure"),"PHISH-004","Supplied header reports DKIM failure; cryptographic validity not verified."),(h.get("dmarc_failure"),"PHISH-005","Supplied Authentication-Results reports DMARC failure; no DNS verification performed."),(not h.get("authentication_results_present"),"PHISH-006","No authentication-result context was supplied; forwarded or pasted messages may omit it."),(any(x["score"]>=12 for x in u),"PHISH-007","One or more URLs contain suspicious lexical characteristics."),(any(x["flags"]["ip_literal"] for x in u),"PHISH-008","An IP-literal hostname was observed."),(any(x["flags"]["punycode"] or x["flags"]["lookalike"] for x in u),"PHISH-009","A local punycode or lookalike-domain indicator was observed."),(any(x["flags"]["shortener"] for x in u),"PHISH-010","A locally catalogued shortened-link domain was observed."),(any(x["flags"]["unsafe_scheme"] for x in u),"PHISH-011","An unsupported or unsafe URI scheme was supplied."),(bool(html.get("anchor_mismatches")),"PHISH-012","Displayed link text differs from the inert target value."),(any(x["flags"]["sensitive_query"] for x in u),"PHISH-013","A sensitive query key was present; its value was redacted."),(t.get("credential_request",0)>0,"PHISH-014","Credential-request language was observed."),(t.get("urgency",0)+t.get("fear_language",0)>0,"PHISH-015","Urgency or threat language was observed."),(t.get("payment_request",0)>0,"PHISH-016","Payment, invoice, or gift-card language was observed."),(t.get("enable_content",0)>0,"PHISH-017","An enable-content instruction was observed."),(any(x["risk_label"]!="low_observed_risk" for x in a),"PHISH-018","Suspicious attachment metadata was observed; content was not executed."),(any(x["double_extension"] for x in a),"PHISH-019","A double-extension attachment filename was observed."),(any(x.get("mime_mismatch") for x in a),"PHISH-020","Declared MIME family differs from the filename-derived type."),(html.get("form_present") or html.get("password_field"),"PHISH-021","Inert HTML contains a form or password-field indicator."),(html.get("hidden_content") or html.get("iframe"),"PHISH-022","Inert HTML contains hidden-content or iframe indicators."),(len(u)>8 and t.get("character_count",0)<500,"PHISH-023","Link concentration is high relative to bounded visible text."),(watchlist_matches>0,"PHISH-024","A local application watchlist entry matched."),(model_probability>=.55,"PHISH-025","The bundled local demonstration classifier produced an elevated risk indicator.")]:
        if condition:codes.append((code,evidence))
    out=[]
    for code,evidence in codes:
        rule=RULES[code];out.append({**{k:v for k,v in rule.items() if k!="score"},"evidence_summary":evidence[:500],"fingerprint":hashlib.sha256(f"{source_hash}:{code}:{evidence}".encode()).hexdigest(),"score":rule["score"]})
    return out
