import html,json
from app import models
from .model_service import DISCLAIMER
from .redaction import redact_text
TITLE="Phishing Risk Analysis Report"
SECTIONS=["Executive Summary","Analysis Scope","Message Identity","Sender and Header Review","Authentication Header Review","URL and Domain Analysis","HTML and Link Review","Attachment Metadata Review","Social-Engineering Language Review","Local Classifier Result","Explainable Risk Score","Detailed Findings","Indicators and Watchlist Matches","Recommended Analyst Actions","Methodology and Limitations","Safe Offline-Analysis Disclaimer"]
def esc(v):return html.escape(redact_text(v,4000))
def generate(db,analysis):
    findings="".join(f"<li><strong>{esc(x.rule_code)} — {esc(x.title)}</strong>: {esc(x.evidence_summary)}</li>" for x in analysis.findings) or "<li>No rule findings.</li>"
    indicators="".join(f"<li>{esc(x.indicator_type)}: {esc(x.display_value_redacted)}</li>" for x in analysis.indicators) or "<li>No stored indicators.</li>"
    values={"Executive Summary":f"Offline analysis score {analysis.final_risk_score}/100, classification {esc(analysis.classification)}, confidence {esc(analysis.confidence)}.","Analysis Scope":"Static local analysis only; no external resource was contacted.","Message Identity":f"Subject: {esc(analysis.subject_redacted or 'Not supplied')}<br>Sender: {esc(analysis.sender_address_redacted or 'Not supplied')}<br>Source hash: {esc(analysis.source_hash)}","Sender and Header Review":esc(analysis.header_summary_json),"Authentication Header Review":"Supplied header claims are reported only. No live DNS, SPF, DKIM cryptographic, or DMARC verification was performed.","URL and Domain Analysis":f"{analysis.url_count} sanitized URL indicators; none are clickable and none were contacted.","HTML and Link Review":"HTML was parsed as inert text and was never rendered.","Attachment Metadata Review":f"{analysis.attachment_count} attachments inspected in memory; bytes were not retained.","Social-Engineering Language Review":esc(analysis.feature_summary_json),"Local Classifier Result":f"Probability {analysis.model_probability}; {esc(DISCLAIMER)}","Explainable Risk Score":f"Heuristic {analysis.heuristic_score}; final {analysis.final_risk_score}/100.","Detailed Findings":f"<ul>{findings}</ul>","Indicators and Watchlist Matches":f"<ul>{indicators}</ul>","Recommended Analyst Actions":"Validate sender and requested actions through approved independent channels. Do not open links or attachments during triage.","Methodology and Limitations":esc(analysis.methodology),"Safe Offline-Analysis Disclaimer":"Offline phishing risk analysis only. This is not a definitive maliciousness verdict; links, domains, senders, and attachments were not contacted or executed."}
    body="".join(f"<section><h2>{html.escape(name)}</h2><div>{values[name]}</div></section>" for name in SECTIONS);doc=f"<!doctype html><html><head><meta charset='utf-8'><title>{TITLE}</title><style>body{{font:14px system-ui;max-width:900px;margin:30px auto;line-height:1.6}}section{{border-bottom:1px solid #ddd;padding:12px}}@media print{{body{{margin:0}}}}</style></head><body><h1>{TITLE}</h1>{body}</body></html>"
    item=models.PhishingReport(analysis_id=analysis.id,title=TITLE,html_content=doc,summary_json=json.dumps({"analysis_id":analysis.id,"score":analysis.final_risk_score,"classification":analysis.classification,"sections":SECTIONS}));db.add(item);db.flush();from .service import activity,notify;activity(db,"phishing_report_generated",f"Phishing report {item.id} generated.",analysis.id);notify(db,"Phishing Report Generated",f"Report for analysis {analysis.id} is ready.","success","phishing_report",item.id);db.commit();db.refresh(item);return item
