import html,json
from sqlalchemy.orm import Session
from app import models
from app.modules.document_threats.service import activity,notify
from app.modules.document_threats.redaction import redact_text

TITLE="Document Threat Analysis Report"
def esc(v): return html.escape(redact_text(v,500))
def generate(db:Session,analysis):
    findings=analysis.findings; indicators=analysis.indicators; artifacts=analysis.embedded_artifacts
    features=json.loads(analysis.feature_summary_json or "{}"); metadata=json.loads(analysis.metadata_json_redacted or "{}")
    finding_html="".join(f"<article><h3>{esc(f.rule_code)} — {esc(f.title)}</h3><p>{esc(f.severity)} / {esc(f.confidence)}</p><p>{esc(f.description)}</p><pre>{esc(f.evidence_summary)}</pre><p><strong>Remediation:</strong> {esc(f.remediation)}</p></article>" for f in findings) or "<p>No static findings.</p>"
    indicator_html="".join(f"<li>{esc(i.indicator_type)}: {esc(i.display_value_redacted)} — {esc(i.context)}</li>" for i in indicators[:500]) or "<li>No indicators.</li>"
    artifact_html="".join(f"<li>{esc(a.filename_sanitized)} · {esc(a.risk_label)} · sha256 {esc(a.sha256 or 'unavailable')}</li>" for a in artifacts) or "<li>No embedded artifacts.</li>"
    sections=[("Executive Summary",f"Static analysis assigned {analysis.classification} with score {analysis.risk_score}/100 and {analysis.confidence} confidence."),("File Identity and SHA-256",f"Filename: {esc(analysis.filename_sanitized)}<br>SHA-256: {esc(analysis.file_hash)}<br>Size: {analysis.file_size} bytes"),("Analysis Scope","Pure Python, read-only static inspection of in-memory PDF bytes. The original was not retained."),("Risk Classification",f"{esc(analysis.classification)} · {analysis.risk_score}/100 · {esc(analysis.confidence)} confidence"),("PDF Structure Summary",f"Version {esc(analysis.pdf_version)}; pages {analysis.page_count}; encrypted {analysis.is_encrypted}; annotations {analysis.annotation_count}; EOF markers {esc(features.get('eof_count'))}."),("Active Content Indicators",f"JavaScript={analysis.has_javascript}; OpenAction={analysis.has_open_action}; AdditionalActions={analysis.has_additional_actions}; Launch={analysis.has_launch_action}."),("External Link and URI Review",f"<p>{analysis.external_uri_count} URI indicators. No destination was contacted.</p><ul>{indicator_html}</ul>"),("Embedded Artifact Review",f"<p>{analysis.embedded_file_count} artifacts; bytes were never persisted or exposed.</p><ul>{artifact_html}</ul>"),("Forms and Action Review",f"AcroForm={analysis.has_acroform}; XFA={analysis.has_xfa}."),("Metadata and Structural Anomalies",f"<pre>{esc(json.dumps(metadata,sort_keys=True))}</pre>"),("Text-Based Risk Indicators",esc(json.dumps(features.get('text_features',{}),sort_keys=True))),("Detailed Findings",finding_html),("Recommended Analyst Actions","Keep the document isolated, validate provenance, and use an approved sandbox when deeper behavioral validation is authorized."),("Methodology and Limitations",esc(analysis.methodology)),("Safe Static-Analysis Disclaimer","Static analysis result — no document content was executed, and this is not a definitive malware verdict. Links were not opened; embedded files were not extracted.")]
    body="".join(f"<section><h2>{title}</h2>{content if content.startswith(('<p','<ul','<pre','<article')) else '<p>'+content+'</p>'}</section>" for title,content in sections)
    document=f"<!doctype html><html><head><meta charset='utf-8'><title>{TITLE}</title><style>body{{font:14px/1.6 system-ui;margin:40px;color:#172033}}h1{{color:#4338ca}}section{{margin:28px 0;break-inside:avoid}}pre{{white-space:pre-wrap;background:#f1f5f9;padding:12px}}@media print{{body{{margin:15mm}}}}</style></head><body><h1>{TITLE}</h1>{body}</body></html>"
    report=models.DocumentReport(analysis_id=analysis.id,title=TITLE,html_content=document,summary_json=json.dumps({"analysis_id":analysis.id,"risk_score":analysis.risk_score,"classification":analysis.classification,"findings":len(findings)},sort_keys=True));db.add(report);db.flush();activity(db,"document_report_generated",f"Document report {report.id} generated.",analysis.id);notify(db,"Document Report Generated",f"Report for {analysis.filename_sanitized} is ready.","success","document_report",report.id);db.commit();db.refresh(report);return report
