import json,os,socket,subprocess,unittest,webbrowser,smtplib,imaplib,poplib
from datetime import datetime,timedelta,timezone
from unittest.mock import patch
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from app import models
from app.database import Base,get_db
from app.main import app
from tests.access_helpers import authenticate_admin
from app.modules.governance.scoring import calculate


class GovernanceTests(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.engine=create_engine("sqlite://",connect_args={"check_same_thread":False},poolclass=StaticPool);cls.factory=sessionmaker(bind=cls.engine)
  def override():
   db=cls.factory()
   try:yield db
   finally:db.close()
  app.dependency_overrides[get_db]=override;cls.client=TestClient(app)
 @classmethod
 def tearDownClass(cls):cls.client.close();app.dependency_overrides.clear();cls.engine.dispose()
 def setUp(self):Base.metadata.drop_all(self.engine);Base.metadata.create_all(self.engine);authenticate_admin(self.client,self.factory)
 def seed_sources(self):
  now=datetime.now(timezone.utc)
  with self.factory() as db:
   target=models.Target(name="Governance target",base_url="https://example.com",domain="example.com",environment="test",authorization_confirmed=True);db.add(target);db.flush();scan=models.Scan(target_id=target.id,profile="safe",status="completed");db.add(scan);db.flush();web=models.Finding(scan_id=scan.id,target_id=target.id,title="Missing token=FAKE_WEB",category="headers",severity="high",confidence="high",evidence="password=FAKE_PASSWORD",description="Local",remediation="Review");db.add(web)
   assessment=models.ApiAssessment(name="Governance API",source_type="openapi");db.add(assessment);db.flush();endpoint=models.ApiEndpoint(assessment_id=assessment.id,path="/payments/{id}",method="GET");db.add(endpoint);db.flush();role=models.ApiRole(assessment_id=assessment.id,name="Reviewer");db.add(role);db.flush();db.add(models.ApiFinding(assessment_id=assessment.id,title="API authorization gap",description="Local",evidence="Bearer FAKE_JWT",impact="Review",remediation="Review",source="openapi",fingerprint="gov-api",severity="high",confidence="high"));db.add(models.AuthorizationReview(assessment_id=assessment.id,endpoint_id=endpoint.id,review_type="object_level",expected_behavior="Scoped",observed_metadata="Local",risk_indicator="Possible authorization gap",severity="high",confidence="high"));db.add(models.AuthorizationMatrixEntry(assessment_id=assessment.id,endpoint_id=endpoint.id,role_id=role.id,expected_access="conditional",review_status="needs_review"));db.add(models.ApiBusinessFlowRisk(flow_id=1,risk_type="abuse",title="Business flow abuse",severity="high",confidence="high",description="Local",evidence_summary="Bounded",remediation="Review",fingerprint="gov-flow"))
   db.add(models.SocAlert(rule_id=1,title="Unresolved alert",description="Local",severity="high",confidence="high",first_seen=now,last_seen=now,event_count=2,correlation_key="local",evidence_summary="token=FAKE_SOC",fingerprint="gov-soc",status="open"));db.add(models.DocumentFinding(analysis_id=1,rule_code="DOC-GOV",title="Active content",category="active_content",severity="high",confidence="high",description="Local",evidence_summary="password=FAKE_DOC",technical_impact="Review",possible_business_impact="Review",remediation="Review",fingerprint="gov-doc"));db.add(models.PhishingFinding(analysis_id=1,rule_code="PH-GOV",title="Credential lure",category="credential",severity="high",confidence="high",description="Local",evidence_summary="token=FAKE_PHISH",technical_impact="Review",possible_business_impact="Review",remediation="Review",fingerprint="gov-phish"));db.add(models.CorrelationMatch(rule_code="CORR-006",title="High local relationship",explanation="Bounded",severity="high",confidence="high",status="new",fingerprint="gov-corr",match_key="gov",source_modules_json="[]",observation_ids_json="[]"));db.add(models.IncidentCase(case_key="CASE-GOV",title="Open governance incident",summary="Bounded",severity="high",confidence="high",priority="P1",status="investigating",case_type="incident"));db.commit();return {"target":target.id,"web":web.id,"assessment":assessment.id}
 def manual_risk(self,title="Manual governance risk"):
  response=self.client.post("/api/governance/risks",json={"title":title,"description":"Local evidence only","category":"governance","likelihood":4,"impact":5,"residual_likelihood":3,"residual_impact":4,"confidence":"high"});self.assertEqual(response.status_code,200,response.text);return response.json()
 def test_framework_seeding_scoring_and_system_protection(self):
  empty=self.client.get("/api/governance/overview").json();self.assertEqual(empty["total_risks"],0);first=self.client.post("/api/governance/frameworks/seed").json();self.assertEqual(first["frameworks_created"],4);self.assertGreaterEqual(first["controls_created"],40);second=self.client.post("/api/governance/frameworks/seed").json();self.assertEqual(second["frameworks_created"],0);self.assertEqual(second["controls_created"],0)
  frameworks=self.client.get("/api/governance/frameworks").json();self.assertEqual({x["version"] for x in frameworks},{"2.0","2021","2023","2022"});self.assertTrue(all("does not perform certification" in x["disclaimer"] for x in frameworks));self.assertEqual(self.client.delete(f"/api/governance/frameworks/{frameworks[0]['id']}").status_code,422);self.assertEqual(self.client.patch(f"/api/governance/frameworks/{frameworks[0]['id']}",json={"enabled":False}).json()["enabled"],False)
  self.assertEqual(calculate(1,1)["inherent_score"],4);self.assertEqual(calculate(5,5)["inherent_score"],100);self.assertEqual(calculate(3,5)["residual_score"],60);self.assertEqual(calculate(3,5)["severity"],"high");self.assertEqual(calculate(3,5)["appetite_status"],"exceeds_appetite")
 def test_all_adapters_sync_idempotency_redaction_and_source_preservation(self):
  ids=self.seed_sources()
  with self.factory() as db:before=(db.query(models.Target).count(),db.query(models.ApiAssessment).count(),db.query(models.SocAlert).count(),db.query(models.IncidentCase).count())
  first=self.client.post("/api/governance/risks/sync").json();self.assertGreaterEqual(first["risks_created"],9);self.assertEqual(set(first["per_module_counts"]),{"web_exposure","api_security","soc_monitor","document_threat","phishing_defense","unified_correlation","incident_case"});second=self.client.post("/api/governance/risks/sync").json();self.assertEqual(second["risks_created"],0);self.assertEqual(second["sources_created"],0);self.assertGreater(second["sources_reused"],0)
  with self.factory() as db:
   after=(db.query(models.Target).count(),db.query(models.ApiAssessment).count(),db.query(models.SocAlert).count(),db.query(models.IncidentCase).count());serialized=json.dumps([(x.title,x.description,[(s.title_snapshot,s.evidence_snapshot) for s in x.sources]) for x in db.query(models.GovernanceRisk)])
  self.assertEqual(before,after);self.assertNotIn("FAKE_",serialized);filtered=self.client.get("/api/governance/risks",params={"source_module":"api_security","severity":"high","min_residual_score":40}).json();self.assertTrue(filtered["items"]);self.assertEqual(self.client.get("/api/governance/risks",params={"due_from":"2027-01-01T00:00:00Z","due_to":"2026-01-01T00:00:00Z"}).status_code,422)
 def test_risk_lifecycle_treatment_and_exception_controls(self):
  risk=self.manual_risk();rid=risk["id"];self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"residual_likelihood":2}).status_code,422);self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"status":"accepted"}).status_code,422);self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"status":"closed"}).status_code,422)
  treatment=self.client.post(f"/api/governance/risks/{rid}/treatments",json={"title":"Workflow plan","description":"No execution","strategy":"mitigate","expected_residual_likelihood":1,"expected_residual_impact":1}).json();self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}/treatments/{treatment['id']}",json={"status":"completed"}).status_code,422);before=self.client.get(f"/api/governance/risks/{rid}").json()["residual_score"];done=self.client.patch(f"/api/governance/risks/{rid}/treatments/{treatment['id']}",json={"status":"completed","completion_summary":"Analyst recorded completion"}).json();self.assertEqual(done["status"],"completed");self.assertEqual(self.client.get(f"/api/governance/risks/{rid}").json()["residual_score"],before)
  exc=self.client.post(f"/api/governance/risks/{rid}/exceptions",json={"justification":"Time-limited business decision"}).json();self.assertEqual(self.client.patch(f"/api/governance/exceptions/{exc['id']}",json={"status":"approved"}).status_code,422);future=(datetime.now(timezone.utc)+timedelta(days=5)).isoformat();self.assertEqual(self.client.patch(f"/api/governance/exceptions/{exc['id']}",json={"status":"approved","approver_name":"Risk owner","expires_at":future}).status_code,200);self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"status":"accepted"}).status_code,200)
  with self.factory() as db:x=db.query(models.RiskException).filter_by(id=exc["id"]).one();x.expires_at=datetime.now(timezone.utc)-timedelta(days=1);db.commit()
  first=self.client.post("/api/governance/exceptions/check-expired").json();self.assertEqual(first["newly_expired"],1);count=len([x for x in self.client.get("/api/notifications/").json() if x["title"]=="Governance Exception Expired"]);self.client.post("/api/governance/exceptions/check-expired");self.assertEqual(len([x for x in self.client.get("/api/notifications/").json() if x["title"]=="Governance Exception Expired"]),count);self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"status":"closed","resolution_summary":"Governance review completed"}).status_code,200);self.assertEqual(self.client.patch(f"/api/governance/risks/{rid}",json={"status":"under_review"}).json()["closed_at"],None)
 def test_mapping_coverage_evidence_reviews_snapshots_reports_and_integrations(self):
  self.client.post("/api/governance/frameworks/seed");risk=self.manual_risk();generated=self.client.post("/api/governance/mappings/generate").json();self.assertGreater(generated["candidates_created"],0);self.assertEqual(self.client.post("/api/governance/mappings/generate").json()["candidates_created"],0);mappings=self.client.get("/api/governance/mappings",params={"status":"candidate"}).json()["items"];framework_id=mappings[0]["framework"]["id"];control_id=mappings[0]["control_id"];before=self.client.get(f"/api/governance/controls/{control_id}/coverage").json();self.assertNotEqual(before["status"],"supported");self.client.patch(f"/api/governance/mappings/{mappings[0]['id']}",json={"mapping_status":"confirmed","analyst_notes":"Evidence reviewed"});self.assertEqual(self.client.patch(f"/api/governance/mappings/{mappings[1]['id']}",json={"mapping_status":"not_applicable"}).status_code,422);self.client.patch(f"/api/governance/mappings/{mappings[1]['id']}",json={"mapping_status":"rejected","analyst_notes":"Relationship not supported"})
  package=self.client.post("/api/governance/evidence-packages",json={"title":"Local evidence package","description":"Safe snapshots","framework_id":framework_id}).json();item=self.client.post(f"/api/governance/evidence-packages/{package['id']}/items",json={"source_module":"governance","source_record_type":"risk","source_record_id":risk["id"],"risk_id":risk["id"],"control_id":control_id,"evidence_strength":"strong"}).json();self.assertTrue(item["created"]);self.assertFalse(self.client.post(f"/api/governance/evidence-packages/{package['id']}/items",json={"source_module":"governance","source_record_type":"risk","source_record_id":risk["id"],"risk_id":risk["id"],"control_id":control_id}).json()["created"]);self.assertEqual(self.client.get(f"/api/governance/controls/{control_id}/coverage").json()["status"],"supported")
  start=(datetime.now(timezone.utc)-timedelta(days=30)).isoformat();end=datetime.now(timezone.utc).isoformat();review=self.client.post("/api/governance/reviews",json={"title":"Quarterly governance review","review_type":"executive","period_start":start,"period_end":end,"scope_summary":"Local evidence"}).json();self.assertEqual(self.client.post(f"/api/governance/reviews/{review['id']}/complete",json={}).status_code,422);complete=self.client.post(f"/api/governance/reviews/{review['id']}/complete",json={"conclusions":"Management review required"}).json();self.assertTrue(complete["snapshot_created"]);self.assertEqual(self.client.patch(f"/api/governance/reviews/{review['id']}",json={"title":"Changed"}).status_code,422);snap=self.client.post("/api/governance/snapshots/capture",json={"label":"manual"}).json();self.assertTrue(snap["created"])
  reports=[self.client.post("/api/governance/reports/executive").json(),self.client.post("/api/governance/reports/risk-register").json(),self.client.post(f"/api/governance/frameworks/{framework_id}/reports").json(),self.client.post(f"/api/governance/evidence-packages/{package['id']}/reports").json()];self.assertTrue(all("does not perform certification" in x["html_content"] for x in reports));self.assertTrue(all("<a " not in x["html_content"] for x in reports));self.assertEqual(self.client.get(f"/api/governance/reports/{reports[0]['id']}/download").status_code,200);self.assertGreater(self.client.get("/api/dashboard/summary").json()["governance_open_risks"],0);self.assertTrue(self.client.get("/api/search/",params={"q":"Quarterly"}).json()["governance_reviews"])
 def test_workflow_date_validation_and_exception_traceability(self):
  risk=self.manual_risk("Date validation risk");rid=risk["id"];self.assertEqual(self.client.post(f"/api/governance/risks/{rid}/treatments",json={"title":"Invalid date","description":"Local","strategy":"monitor","target_date":"not-a-date"}).status_code,422);exc=self.client.post(f"/api/governance/risks/{rid}/exceptions",json={"justification":"Bounded decision"}).json();future=(datetime.now(timezone.utc)+timedelta(days=2)).isoformat();self.client.patch(f"/api/governance/exceptions/{exc['id']}",json={"status":"approved","approver_name":"Owner","expires_at":future});accepted=self.client.patch(f"/api/governance/risks/{rid}",json={"status":"accepted"}).json();self.assertIn(exc["exception_key"],accepted["acceptance_justification"])
 def test_populated_overview_handles_optional_dates(self):
  self.manual_risk("Risk without optional dates");response=self.client.get("/api/governance/overview");self.assertEqual(response.status_code,200,response.text);self.assertEqual(response.json()["total_risks"],1)
 def test_governance_operations_are_offline(self):
  fail=RuntimeError("external interface forbidden")
  with patch("socket.create_connection",side_effect=fail),patch("socket.getaddrinfo",side_effect=fail),patch("subprocess.run",side_effect=fail),patch("subprocess.Popen",side_effect=fail),patch("os.system",side_effect=fail),patch("webbrowser.open",side_effect=fail),patch("httpx.get",side_effect=fail),patch("httpx.post",side_effect=fail),patch("urllib.request.urlopen",side_effect=fail),patch("smtplib.SMTP",side_effect=fail),patch("imaplib.IMAP4",side_effect=fail),patch("poplib.POP3",side_effect=fail):
   self.assertEqual(self.client.post("/api/governance/frameworks/seed").status_code,200);risk=self.manual_risk("Offline governance risk");self.assertEqual(self.client.post("/api/governance/risks/sync").status_code,200);self.assertEqual(self.client.post("/api/governance/mappings/generate").status_code,200);self.assertEqual(self.client.get("/api/governance/coverage/summary").status_code,200);self.assertEqual(self.client.post("/api/governance/snapshots/capture").status_code,200);self.assertEqual(self.client.post("/api/governance/reports/executive").status_code,200);self.assertEqual(self.client.get("/api/dashboard/summary").status_code,200);self.assertEqual(self.client.get("/api/search/",params={"q":"Offline"}).status_code,200)


if __name__=="__main__":unittest.main()
