import os,socket,subprocess,unittest,webbrowser,smtplib,imaplib,poplib,json
from datetime import datetime,timedelta,timezone
from pathlib import Path
from unittest.mock import patch
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from app import models
from app.database import Base,get_db
from app.main import app
from tests.access_helpers import authenticate_admin
from app.modules.unified_correlation.normalization import normalize
from app.modules.unified_correlation import service
FIX=Path(__file__).parent/"fixtures"/"api_security"
class UnifiedCorrelationTests(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.engine=create_engine("sqlite://",connect_args={"check_same_thread":False},poolclass=StaticPool);cls.factory=sessionmaker(bind=cls.engine)
  def override():
   db=cls.factory()
   try:yield db
   finally:db.close()
  app.dependency_overrides[get_db]=override;cls.client=TestClient(app)
 @classmethod
 def tearDownClass(cls):cls.client.close();app.dependency_overrides.clear();cls.engine.dispose()
 def setUp(self):Base.metadata.drop_all(self.engine);Base.metadata.create_all(self.engine);authenticate_admin(self.client,self.factory)
 def seed(self):
  with self.factory() as db:
   db.add(models.Target(name="Safe Target",base_url="https://example.com",domain="example.com",environment="test",authorization_confirmed=True));a=models.ApiAssessment(name="Safe API",description="local",source_type="openapi",status="completed",base_url="https://example.com",endpoint_count=0);db.add(a);db.commit()
 def test_normalization(self):
  self.assertEqual(normalize("domain","Example.COM.")[0],"example.com");self.assertEqual(normalize("ip_address","2001:0db8::1")[0],"2001:db8::1");self.assertEqual(normalize("email_address","User@Example.COM")[1],"Us***@example.com");u=normalize("url","https://user:pass@example.com/a?token=FAKE");self.assertEqual(len(u[0]),64);self.assertNotIn("user:pass",u[1]);self.assertNotIn("FAKE",u[1]);self.assertEqual(normalize("api_endpoint","get /users/{id}?token=x")[0],"GET /users/{id}")
  with self.assertRaises(ValueError):normalize("ip_address","not-ip")
 def test_sync_correlation_case_report_and_preservation(self):
  self.seed();first=self.client.post("/api/correlation/entities/sync").json();self.assertGreater(first["observations_created"],0);second=self.client.post("/api/correlation/entities/sync").json();self.assertEqual(second["observations_created"],0);self.assertGreater(second["observations_reused"],0)
  entities=self.client.get("/api/correlation/entities").json();entity=next(x for x in entities["items"] if x["entity_type"]=="domain");self.assertEqual(entity["source_module_count"],2);run=self.client.post("/api/correlation/matches/run").json();self.assertGreater(run["matches_created"],0);rerun=self.client.post("/api/correlation/matches/run").json();self.assertEqual(rerun["matches_created"],0)
  match=self.client.get("/api/correlation/matches").json()[0];case=self.client.post(f"/api/correlation/matches/{match['id']}/create-case").json();same=self.client.post(f"/api/correlation/matches/{match['id']}/create-case").json();self.assertEqual(case["id"],same["id"]);cid=case["id"]
  note=self.client.post(f"/api/correlation/cases/{cid}/notes",json={"note_text":"token=FAKE_SECRET","author_label":"Analyst"}).json();self.assertNotIn("FAKE_SECRET",note["note_text"]);action=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"Review related records"});self.assertEqual(action.status_code,200)
  self.client.patch(f"/api/correlation/cases/{cid}",json={"priority":"P1","status":"investigating"});report=self.client.post(f"/api/correlation/cases/{cid}/reports").json();self.assertEqual(len(report["summary"]["sections"]),17);self.assertNotIn("<a ",report["html_content"]);self.assertIn("no indicators",report["html_content"])
  self.assertEqual(self.client.patch(f"/api/correlation/cases/{cid}",json={"status":"resolved"}).status_code,422);self.assertEqual(self.client.patch(f"/api/correlation/cases/{cid}",json={"status":"resolved","resolution_summary":"Validated local relationship"}).status_code,200);self.assertEqual(self.client.patch(f"/api/correlation/cases/{cid}",json={"status":"investigating"}).status_code,200);timeline=self.client.get(f"/api/correlation/cases/{cid}/timeline").json();self.assertGreaterEqual(len(timeline),7)
  before=self.client.get("/api/targets/").json();self.client.delete(f"/api/correlation/cases/{cid}");self.assertEqual(self.client.get("/api/targets/").json(),before);dash=self.client.get("/api/dashboard/summary").json();self.assertGreaterEqual(dash["multi_module_entities"],1);self.assertEqual(self.client.get("/api/search/",params={"q":"example"}).status_code,200)
 def test_empty_and_safety_interfaces(self):
  self.assertEqual(self.client.get("/api/correlation/overview").json()["total_entities"],0);fail=RuntimeError("forbidden")
  with patch("socket.create_connection",side_effect=fail),patch("socket.getaddrinfo",side_effect=fail),patch("subprocess.run",side_effect=fail),patch("subprocess.Popen",side_effect=fail),patch("os.system",side_effect=fail),patch("webbrowser.open",side_effect=fail),patch("httpx.get",side_effect=fail),patch("httpx.post",side_effect=fail),patch("urllib.request.urlopen",side_effect=fail),patch("smtplib.SMTP",side_effect=fail),patch("imaplib.IMAP4",side_effect=fail),patch("poplib.POP3",side_effect=fail):
   self.seed();self.assertEqual(self.client.post("/api/correlation/entities/sync").status_code,200);self.assertEqual(self.client.post("/api/correlation/matches/run").status_code,200);self.assertEqual(self.client.get("/api/dashboard/summary").status_code,200);self.assertEqual(self.client.get("/api/search/",params={"q":"example"}).status_code,200)
 def make_window_entity(self,times_modules):
  with self.factory() as db:
   e=models.UnifiedEntity(entity_type="domain",normalized_value="window.example",value_hash="a"*64,display_value_redacted="window.example");db.add(e);db.flush()
   for index,(stamp,module) in enumerate(times_modules):db.add(models.EntityObservation(entity_id=e.id,source_module=module,source_record_type="test",source_record_id=index+1,title_snapshot="Safe",evidence_snapshot="Bounded",severity="medium",confidence="high",observed_at=stamp,observation_fingerprint=f"window-{index}"))
   db.commit();return e.id
 def test_corr010_real_rolling_window_boundary_disable_and_rerun(self):
  base=datetime(2026,1,1,tzinfo=timezone.utc);eid=self.make_window_entity([(base,"web_exposure"),(base+timedelta(hours=24),"api_security"),(base+timedelta(hours=24),"api_security")]);first=self.client.post("/api/correlation/matches/run").json();matches=[m for m in self.client.get("/api/correlation/matches",params={"rule_code":"CORR-010"}).json() if m["primary_entity_id"]==eid];self.assertEqual(len(matches),1);self.assertIn("24 hours",matches[0]["explanation"]);self.assertIn("2 distinct source modules",matches[0]["explanation"]);self.assertEqual(len(matches[0]["observation_ids"]),3);self.assertEqual(self.client.post("/api/correlation/matches/run").json()["matches_created"],0)
  Base.metadata.drop_all(self.engine);Base.metadata.create_all(self.engine);authenticate_admin(self.client,self.factory);eid=self.make_window_entity([(base,"web_exposure"),(base+timedelta(hours=24,seconds=1),"api_security")]);self.client.post("/api/correlation/matches/run");self.assertFalse(any(m["rule_code"]=="CORR-010" for m in self.client.get("/api/correlation/matches").json()))
  Base.metadata.drop_all(self.engine);Base.metadata.create_all(self.engine);authenticate_admin(self.client,self.factory);self.make_window_entity([(base,"web_exposure"),(base+timedelta(hours=1),"web_exposure")]);self.client.post("/api/correlation/matches/run");self.assertFalse(any(m["rule_code"]=="CORR-010" for m in self.client.get("/api/correlation/matches").json()))
  with self.factory() as db:service.seed(db);r=db.query(models.CorrelationRule).filter_by(code="CORR-010").one();r.enabled=False;db.commit()
  self.assertEqual(self.client.post("/api/correlation/matches/run").status_code,200);self.assertFalse(any(m["rule_code"]=="CORR-010" for m in self.client.get("/api/correlation/matches").json()))
 def test_overdue_action_lifecycle_notifications(self):
  case=self.client.post("/api/correlation/cases",json={"title":"Overdue lifecycle","summary":"Local"}).json();cid=case["id"];past=(datetime.now(timezone.utc)-timedelta(days=1)).isoformat();future=(datetime.now(timezone.utc)+timedelta(days=1)).isoformat();future_action=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"Future","due_at":future}).json();open_action=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"token=FAKE_OVERDUE","due_at":past}).json();progress=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"Progress","due_at":past}).json();self.client.patch(f"/api/correlation/cases/{cid}/actions/{progress['id']}",json={"status":"in_progress"});completed=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"Done","due_at":past}).json();self.client.patch(f"/api/correlation/cases/{cid}/actions/{completed['id']}",json={"status":"completed"});cancelled=self.client.post(f"/api/correlation/cases/{cid}/actions",json={"title":"Cancelled","due_at":past}).json();self.client.patch(f"/api/correlation/cases/{cid}/actions/{cancelled['id']}",json={"status":"cancelled"});first=self.client.post("/api/correlation/actions/check-overdue").json();self.assertEqual(first["overdue_actions_found"],2);self.assertEqual(first["notifications_created"],2);second=self.client.post("/api/correlation/actions/check-overdue").json();self.assertEqual(second["notifications_created"],0);self.assertEqual(second["notifications_reused"],2);notifications=self.client.get("/api/notifications/").json();overdue=[n for n in notifications if n["title"].startswith("Overdue")];self.assertTrue(all(n["entity_type"]=="incident_case" and n["entity_id"]==cid for n in overdue));self.assertNotIn("FAKE_OVERDUE",json.dumps(overdue));new_due=(datetime.now(timezone.utc)-timedelta(hours=2)).isoformat();self.client.patch(f"/api/correlation/cases/{cid}/actions/{open_action['id']}",json={"due_at":new_due});self.assertEqual(self.client.post("/api/correlation/actions/check-overdue").json()["notifications_created"],1);self.client.patch(f"/api/correlation/cases/{cid}/actions/{open_action['id']}",json={"status":"completed"});self.assertEqual(self.client.post("/api/correlation/actions/check-overdue").json()["notifications_created"],0)
 def test_combined_filters_and_date_validation(self):
  self.seed();self.client.post("/api/correlation/entities/sync");self.client.post("/api/correlation/matches/run");entity=self.client.get("/api/correlation/entities").json()["items"][0];entities=self.client.get("/api/correlation/entities",params={"entity_type":entity["entity_type"],"severity":entity["severity"],"confidence":entity["confidence"],"min_risk":entity["risk_score"],"source_module":"web_exposure"});self.assertEqual(entities.status_code,200);self.assertTrue(entities.json()["items"]);match=self.client.get("/api/correlation/matches").json()[0];self.assertTrue(self.client.get("/api/correlation/matches",params={"rule_code":match["rule_code"],"status":match["status"],"severity":match["severity"],"confidence":match["confidence"],"min_score":match["match_score"]}).json());case=self.client.post(f"/api/correlation/matches/{match['id']}/create-case").json();self.assertTrue(self.client.get("/api/correlation/cases",params={"status":case["status"],"priority":case["priority"],"severity":case["severity"],"confidence":case["confidence"],"case_type":case["case_type"],"entity_id":case["primary_entity_id"]}).json());self.assertEqual(self.client.get("/api/correlation/entities",params={"first_seen_from":"2026-02-01T00:00:00Z","first_seen_to":"2026-01-01T00:00:00Z"}).status_code,422);self.assertEqual(self.client.get("/api/correlation/matches",params={"min_score":101}).status_code,422);self.assertEqual(self.client.get("/api/correlation/cases",params={"date_from":"2026-02-01T00:00:00Z","date_to":"2026-01-01T00:00:00Z"}).status_code,422)
 def test_expanded_api_authorization_and_flow_adapter_idempotency(self):
  assessment=self.client.post("/api/api-security/assessments",json={"name":"Correlation API","source_type":"openapi"}).json();imp=self.client.post(f"/api/api-security/assessments/{assessment['id']}/import/openapi",files={"file":("authorization_flow_openapi.json",(FIX/"authorization_flow_openapi.json").read_bytes(),"application/json")});self.assertEqual(imp.status_code,200);endpoints=self.client.get(f"/api/api-security/assessments/{assessment['id']}/endpoints").json();role=self.client.post(f"/api/api-security/assessments/{assessment['id']}/roles",json={"name":"Reviewer token=FAKE_ROLE_SECRET","privilege_level":"user"}).json();matrix=self.client.post(f"/api/api-security/assessments/{assessment['id']}/authorization-matrix",json={"endpoint_id":endpoints[0]["id"],"role_id":role["id"],"expected_access":"conditional","object_scope":"own"});self.assertEqual(matrix.status_code,200);self.client.post(f"/api/api-security/assessments/{assessment['id']}/authorization-review/generate");flow=self.client.post(f"/api/api-security/assessments/{assessment['id']}/business-flows",json={"name":"Payment flow","description":"Review payment","actor_roles":["Reviewer"]}).json();self.client.post(f"/api/api-security/business-flows/{flow['id']}/steps",json={"step_order":1,"endpoint_id":endpoints[0]["id"],"action_name":"Submit payment","sensitive_operation":True});self.client.post(f"/api/api-security/business-flows/{flow['id']}/analyze");first=self.client.post("/api/correlation/entities/sync",params={"source_module":"api_security"}).json();self.assertGreater(first["per_record_type_counts"].get("authorization_matrix",0),0);self.assertGreater(first["per_record_type_counts"].get("authorization_review",0),0);self.assertGreater(first["per_record_type_counts"].get("business_flow_risk",0),0);second=self.client.post("/api/correlation/entities/sync",params={"source_module":"api_security"}).json();self.assertEqual(second["observations_created"],0);serialized=json.dumps(self.client.get("/api/correlation/entities").json());self.assertNotIn("FAKE_ROLE_SECRET",serialized)
 def test_corr010_duplicate_objects_do_not_count_twice(self):
  base=datetime(2026,1,1,tzinfo=timezone.utc);self.make_window_entity([(base,"web_exposure"),(base+timedelta(hours=1),"api_security")])
  with self.factory() as db:
   observations=db.query(models.EntityObservation).order_by(models.EntityObservation.id).all();qualifying=service.qualifying_window([observations[0],observations[1],observations[1]],24,2)
   self.assertEqual(len(qualifying),2);self.assertEqual(len({item.observation_fingerprint for item in qualifying}),2)
 def test_overdue_failure_creates_no_success_notification(self):
  case=self.client.post("/api/correlation/cases",json={"title":"Failure-safe overdue check","summary":"Local"}).json();past=(datetime.now(timezone.utc)-timedelta(days=1)).isoformat();self.client.post(f"/api/correlation/cases/{case['id']}/actions",json={"title":"Local action","due_at":past});before=len(self.client.get("/api/notifications/").json())
  with patch("app.modules.unified_correlation.service.notify",side_effect=RuntimeError("local notification failure")):
   result=self.client.post("/api/correlation/actions/check-overdue").json()
  self.assertEqual(result["notifications_created"],0);self.assertEqual(len(result["errors"]),1);self.assertEqual(len(self.client.get("/api/notifications/").json()),before)
 def test_new_filter_and_overdue_operations_make_no_external_contact(self):
  case=self.client.post("/api/correlation/cases",json={"title":"Offline operations","summary":"Local"}).json();past=(datetime.now(timezone.utc)-timedelta(hours=1)).isoformat();self.client.post(f"/api/correlation/cases/{case['id']}/actions",json={"title":"Offline action","due_at":past});fail=RuntimeError("external contact forbidden")
  with patch("socket.create_connection",side_effect=fail),patch("socket.getaddrinfo",side_effect=fail),patch("subprocess.run",side_effect=fail),patch("subprocess.Popen",side_effect=fail),patch("os.system",side_effect=fail),patch("webbrowser.open",side_effect=fail),patch("httpx.get",side_effect=fail),patch("httpx.post",side_effect=fail),patch("urllib.request.urlopen",side_effect=fail),patch("smtplib.SMTP",side_effect=fail),patch("imaplib.IMAP4",side_effect=fail),patch("poplib.POP3",side_effect=fail):
   self.assertEqual(self.client.post("/api/correlation/actions/check-overdue").status_code,200);self.assertEqual(self.client.get("/api/correlation/entities",params={"source_module":"api_security"}).status_code,200);self.assertEqual(self.client.get("/api/correlation/matches",params={"source_module":"api_security"}).status_code,200);self.assertEqual(self.client.get("/api/correlation/cases",params={"source_module":"api_security"}).status_code,200)
 def test_api_adapter_redacts_observations_without_mutating_sources(self):
  with self.factory() as db:
   assessment=models.ApiAssessment(name="Adapter source",source_type="manual",status="draft");db.add(assessment);db.flush();role=models.ApiRole(assessment_id=assessment.id,name="Operator token=FAKE_ADAPTER_SECRET",privilege_level="user");db.add(role);db.commit();role_id=role.id;snapshot=(role.name,role.privilege_level,role.assessment_id)
  result=self.client.post("/api/correlation/entities/sync",params={"source_module":"api_security"}).json();self.assertEqual(result["per_record_type_counts"].get("api_role"),1)
  with self.factory() as db:
   role=db.query(models.ApiRole).filter_by(id=role_id).one();self.assertEqual((role.name,role.privilege_level,role.assessment_id),snapshot);observations=db.query(models.EntityObservation).filter_by(source_record_type="api_role").all();self.assertEqual(len(observations),1);self.assertNotIn("FAKE_ADAPTER_SECRET",json.dumps([(x.title_snapshot,x.evidence_snapshot) for x in observations]))
if __name__=="__main__":unittest.main()
