import { apiClient } from './client';

export type ConnectorLifecycle='draft'|'testing'|'active'|'degraded'|'disabled'|'archived';
export type ConnectorHealth='unknown'|'healthy'|'degraded'|'unhealthy'|'disabled';
export type DeliveryStatus='queued'|'waiting_retry'|'delivering'|'succeeded'|'succeeded_with_warnings'|'failed'|'dead_letter'|'cancelled';
export interface Page<T>{items:T[];page:number;page_size:number;total:number;pages:number}
export interface ConnectorDefinition{connector_type:string;display_name:string;category:string;direction:'inbound'|'outbound'|'bidirectional'|'import';description:string;supported_capabilities:string[];configuration_schema:Record<string,unknown>;credential_schema:Record<string,unknown>;supported_authentication_methods:string[];supported_event_types:string[];supported_payload_profiles:string[];supports_test:boolean;supports_health_check:boolean;supports_delivery:boolean;supports_pull:boolean;supports_inbound_webhook:boolean;warning_message:string|null}
export interface Connector{id:number;connector_uuid:string;connector_type:string;name:string;description?:string;direction:string;lifecycle_status:ConnectorLifecycle;health_status:ConnectorHealth;configuration:Record<string,unknown>;payload_profile:string;timeout_seconds:number;retry_limit:number;enabled:boolean;last_test_status?:string;circuit_state:string;optimistic_lock_version:number;[key:string]:unknown}
export interface CredentialStatus{configured:boolean;credential_type:string|null;last_four:string|null;created_at:string|null;rotated_at:string|null;version:number;key_version?:string;key_available:boolean}
export interface IntegrationRecord{id:number;name?:string;title?:string;status?:string;[key:string]:unknown}
export interface Delivery extends IntegrationRecord{delivery_uuid:string;connector_id:number;event_type:string;external_operation:string;payload:Record<string,unknown>;payload_profile:string;status:DeliveryStatus;attempt_count:number;maximum_attempts:number;error_code?:string;error_summary?:string}

const get=<T>(url:string,params?:Record<string,unknown>)=>apiClient.get<T>(url,{params}).then(r=>r.data);
const post=<T>(url:string,data:unknown={})=>apiClient.post<T>(url,data).then(r=>r.data);
const patch=<T>(url:string,data:unknown)=>apiClient.patch<T>(url,data).then(r=>r.data);

export const integrationsApi={
  overview:()=>get<Record<string,unknown>>('/integrations/overview'),catalog:()=>get<{items:ConnectorDefinition[];immutable:boolean;server_owned:boolean}>('/integrations/catalog'),
  connectors:(params?:Record<string,unknown>)=>get<Page<Connector>>('/integrations/connectors',params),createConnector:(data:Record<string,unknown>)=>post<Connector>('/integrations/connectors',data),connector:(id:string|number)=>get<Connector>(`/integrations/connectors/${id}`),updateConnector:(id:string|number,data:Record<string,unknown>)=>patch<Connector>(`/integrations/connectors/${id}`,data),validateConnector:(id:string|number)=>post<Record<string,unknown>>(`/integrations/connectors/${id}/validate`),
  lifecycle:(id:string|number,action:'move-to-testing'|'activate'|'disable'|'archive',lock:number,reason?:string)=>post<Connector>(`/integrations/connectors/${id}/${action}`,{optimistic_lock_version:lock,reason}),testConnector:(id:string|number)=>post<Record<string,unknown>>(`/integrations/connectors/${id}/test`),sendTest:(id:string|number)=>post<Record<string,unknown>>(`/integrations/connectors/${id}/send-test`),resetCircuit:(id:string|number,reason:string)=>post<Connector>(`/integrations/connectors/${id}/reset-circuit`,{reason}),
  credentialStatus:(id:string|number)=>get<CredentialStatus>(`/integrations/connectors/${id}/credential-status`),putCredential:(id:string|number,data:Record<string,unknown>)=>apiClient.put<CredentialStatus>(`/integrations/connectors/${id}/credentials`,data).then(r=>r.data),rotateCredential:(id:string|number,data:Record<string,unknown>)=>post<CredentialStatus>(`/integrations/connectors/${id}/credentials/rotate`,data),removeCredential:(id:string|number)=>apiClient.delete(`/integrations/connectors/${id}/credentials`,{data:{confirmation:'REMOVE AND DISABLE'}}).then(r=>r.data),
  networkPolicy:(id:string|number)=>get<IntegrationRecord>(`/integrations/connectors/${id}/network-policy`),updateNetworkPolicy:(id:string|number,data:Record<string,unknown>)=>patch<IntegrationRecord>(`/integrations/connectors/${id}/network-policy`,data),
  subscriptions:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/subscriptions',params),subscription:(id:string|number)=>get<IntegrationRecord>(`/integrations/subscriptions/${id}`),createSubscription:(data:Record<string,unknown>)=>post<IntegrationRecord>('/integrations/subscriptions',data),updateSubscription:(id:string|number,data:Record<string,unknown>)=>patch<IntegrationRecord>(`/integrations/subscriptions/${id}`,data),deleteSubscription:(id:string|number)=>apiClient.delete(`/integrations/subscriptions/${id}`).then(r=>r.data),
  mappings:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/mappings',params),mapping:(id:string|number)=>get<IntegrationRecord>(`/integrations/mappings/${id}`),createMapping:(data:Record<string,unknown>)=>post<IntegrationRecord>('/integrations/mappings',data),updateMapping:(id:string|number,data:Record<string,unknown>)=>patch<IntegrationRecord>(`/integrations/mappings/${id}`,data),validateMapping:(id:string|number)=>post<Record<string,unknown>>(`/integrations/mappings/${id}/validate`),previewMapping:(id:string|number,source:Record<string,unknown>)=>post<Record<string,unknown>>(`/integrations/mappings/${id}/preview`,source),deleteMapping:(id:string|number)=>apiClient.delete(`/integrations/mappings/${id}`).then(r=>r.data),
  outbox:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/outbox',params),outboxEvent:(id:string|number)=>get<IntegrationRecord>(`/integrations/outbox/${id}`),
  deliveries:(params?:Record<string,unknown>)=>get<Page<Delivery>>('/integrations/deliveries',params),delivery:(id:string|number)=>get<Delivery>(`/integrations/deliveries/${id}`),createDelivery:(data:Record<string,unknown>)=>post<Delivery>('/integrations/deliveries',data),attempts:(id:string|number)=>get<IntegrationRecord[]>(`/integrations/deliveries/${id}/attempts`),retryDelivery:(id:string|number,reason:string)=>post<Delivery>(`/integrations/deliveries/${id}/retry`,{reason}),cancelDelivery:(id:string|number,reason:string)=>post<Delivery>(`/integrations/deliveries/${id}/cancel`,{reason}),
  deadLetters:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/dead-letters',params),deadLetter:(id:string|number)=>get<IntegrationRecord>(`/integrations/dead-letters/${id}`),replayDeadLetter:(id:string|number,reason:string)=>post<Delivery>(`/integrations/dead-letters/${id}/replay`,{reason}),cancelDeadLetter:(id:string|number,reason:string)=>post<IntegrationRecord>(`/integrations/dead-letters/${id}/cancel`,{reason}),
  inboundEndpoints:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/inbound-endpoints',params),inboundEndpoint:(id:string|number)=>get<IntegrationRecord>(`/integrations/inbound-endpoints/${id}`),createInboundEndpoint:(data:Record<string,unknown>)=>post<IntegrationRecord>('/integrations/inbound-endpoints',data),updateInboundEndpoint:(id:string|number,data:Record<string,unknown>)=>patch<IntegrationRecord>(`/integrations/inbound-endpoints/${id}`,data),rotateInboundSecret:(id:string|number,data:Record<string,unknown>)=>post<CredentialStatus>(`/integrations/inbound-endpoints/${id}/rotate-secret`,data),disableInboundEndpoint:(id:string|number)=>post<IntegrationRecord>(`/integrations/inbound-endpoints/${id}/disable`),
  inboundEvents:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/inbound-events',params),inboundEvent:(id:string|number)=>get<IntegrationRecord>(`/integrations/inbound-events/${id}`),promoteInbound:(id:string|number,target_type:string)=>post<IntegrationRecord>(`/integrations/inbound-events/${id}/promote`,{target_type,confirmation:'PROMOTE QUARANTINED EVENT'}),rejectInbound:(id:string|number,reason:string)=>post<IntegrationRecord>(`/integrations/inbound-events/${id}/reject`,{reason}),
  stixPreview:(bundle:Record<string,unknown>)=>post<IntegrationRecord>('/integrations/stix/import/preview',bundle),stixPromote:(id:number)=>post<IntegrationRecord>('/integrations/stix/import/promote',{import_run_id:id}),stixRuns:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/stix/import-runs',params),stixRun:(id:string|number)=>get<IntegrationRecord>(`/integrations/stix/import-runs/${id}`),taxiiPull:(id:string|number)=>post<Record<string,unknown>>(`/integrations/connectors/${id}/taxii/pull`),taxiiStatus:(id:string|number)=>get<IntegrationRecord>(`/integrations/connectors/${id}/taxii/sync-status`),
  healthChecks:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/health-checks',params),connectorHealthChecks:(id:string|number)=>get<Page<IntegrationRecord>>(`/integrations/connectors/${id}/health-checks`),runHealthChecks:(batch_size=25)=>post<Record<string,unknown>>('/integrations/health-checks/run',{batch_size}),externalReferences:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/external-references',params),externalReference:(id:string|number)=>get<IntegrationRecord>(`/integrations/external-references/${id}`),processDue:(batch_size=100)=>post<Record<string,unknown>>('/integrations/process-due',{batch_size}),
  reports:(params?:Record<string,unknown>)=>get<Page<IntegrationRecord>>('/integrations/reports',params),createReport:(data:Record<string,unknown>)=>post<IntegrationRecord>('/integrations/reports',data),report:(id:string|number)=>get<IntegrationRecord>(`/integrations/reports/${id}`),downloadReport:(id:string|number)=>apiClient.get(`/integrations/reports/${id}/download`,{responseType:'blob'}).then(r=>r.data as Blob),
};
