import { apiClient } from './client';

export type SafetyClassification='read_only'|'harmless_local'|'controlled_local'|'sensitive_local'|'simulation_only';
export type ExecutionMode='dry_run'|'simulation'|'live_local';
export interface Page<T>{items:T[];page:number;page_size:number;total:number;pages:number}
export interface ActionDefinition{action_key:string;display_name:string;category:string;description:string;safety_classification:SafetyClassification;allowed_execution_modes:ExecutionMode[];required_permission:string;approval_requirement:string;administrator_approval_required:boolean;requester_approver_separation_required:boolean;timeout_seconds:number;maximum_retries:number;supports_compensation:boolean;compensating_action_key:string|null;simulation_only:boolean;automatic_local_eligible:boolean;warning_message:string|null;policy?:Record<string,unknown>}
export interface Playbook{id:number;playbook_uuid:string;name:string;description:string;category:string;lifecycle_status:string;trigger_mode:string;current_version:number;optimistic_lock_version:number;system_owned:boolean;validation?:Validation;definition?:PlaybookDefinition;[key:string]:unknown}
export interface PlaybookStep{key:string;type:string;name?:string;action_key?:string;position?:number;configuration?:Record<string,unknown>;condition?:Record<string,unknown>;on_success?:string;on_failure?:string;on_timeout?:string;max_retries?:number;retry_delay_seconds?:number}
export interface PlaybookDefinition{start_step:string;variables:Record<string,unknown>;constants?:Record<string,unknown>;steps:PlaybookStep[]}
export interface Validation{valid:boolean;errors:Array<{code:string;message:string;step_key?:string;path?:string}>;warnings:Array<{code:string;message:string;step_key?:string}>;complexity_score:number;safety_summary:Record<string,unknown>;approval_requirements:unknown[];simulation_only_actions:string[];automatic_local_eligible:boolean;content_sha256:string}
export interface Execution{id:number;execution_uuid:string;playbook_id:number;playbook_version:number;mode:ExecutionMode;status:string;current_step_key?:string;events?:Record<string,unknown>[];steps?:Record<string,unknown>[];approvals?:Record<string,unknown>[];analyst_inputs?:Record<string,unknown>[];evidence?:Record<string,unknown>[];rollbacks?:Record<string,unknown>[];[key:string]:unknown}
export type SoarRecord={id:number;status?:string;title?:string;name?:string;[key:string]:unknown};

const get=<T>(url:string,params?:Record<string,unknown>)=>apiClient.get<T>(url,{params}).then(r=>r.data);
const post=<T>(url:string,data:unknown={})=>apiClient.post<T>(url,data).then(r=>r.data);
const patch=<T>(url:string,data:unknown)=>apiClient.patch<T>(url,data).then(r=>r.data);

export const soarApi={
  overview:()=>get<Record<string,unknown>>('/soar/overview'),actions:()=>get<ActionDefinition[]>('/soar/actions'),actionPolicies:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/action-policies',params),updateActionPolicy:(key:string,data:Record<string,unknown>)=>patch<SoarRecord>(`/soar/action-policies/${encodeURIComponent(key)}`,data),
  playbooks:(params?:Record<string,unknown>)=>get<Page<Playbook>>('/soar/playbooks',params),createPlaybook:(data:Record<string,unknown>)=>post<Playbook>('/soar/playbooks',data),playbook:(id:string|number)=>get<Playbook>(`/soar/playbooks/${id}`),updatePlaybook:(id:string|number,data:Record<string,unknown>)=>patch<Playbook>(`/soar/playbooks/${id}`,data),validate:(id:string|number)=>post<Validation>(`/soar/playbooks/${id}/validate`),moveToTesting:(id:string|number,lock:number)=>post<Playbook>(`/soar/playbooks/${id}/move-to-testing`,{optimistic_lock_version:lock}),activate:(id:string|number,lock:number)=>post<Playbook>(`/soar/playbooks/${id}/activate`,{optimistic_lock_version:lock}),disable:(id:string|number,lock:number)=>post<Playbook>(`/soar/playbooks/${id}/disable`,{optimistic_lock_version:lock}),archive:(id:string|number,lock:number)=>post<Playbook>(`/soar/playbooks/${id}/archive`,{optimistic_lock_version:lock}),clone:(id:string|number,name:string)=>post<Playbook>(`/soar/playbooks/${id}/clone`,{name,change_summary:'Cloned through the SOAR editor'}),
  versions:(id:string|number)=>get<SoarRecord[]>(`/soar/playbooks/${id}/versions`),version:(id:string|number,v:number)=>get<SoarRecord>(`/soar/playbooks/${id}/versions/${v}`),compare:(id:string|number,a:number,b:number)=>get<Record<string,unknown>>(`/soar/playbooks/${id}/versions/${a}/compare/${b}`),rollbackVersion:(id:string|number,data:Record<string,unknown>)=>post<Playbook>(`/soar/playbooks/${id}/rollback-version`,data),
  triggers:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/triggers',params),createTrigger:(data:Record<string,unknown>)=>post<SoarRecord>('/soar/triggers',data),trigger:(id:string|number)=>get<SoarRecord>(`/soar/triggers/${id}`),updateTrigger:(id:string|number,data:Record<string,unknown>)=>patch<SoarRecord>(`/soar/triggers/${id}`,data),deleteTrigger:(id:string|number)=>apiClient.delete(`/soar/triggers/${id}`).then(r=>r.data),evaluateTriggers:(data:Record<string,unknown>)=>post<SoarRecord>('/soar/triggers/evaluate',data),evaluationRuns:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/triggers/evaluation-runs',params),evaluationRun:(id:string|number)=>get<SoarRecord>(`/soar/triggers/evaluation-runs/${id}`),
  executions:(params?:Record<string,unknown>)=>get<Page<Execution>>('/soar/executions',params),createExecution:(data:Record<string,unknown>)=>post<Execution>('/soar/executions',data),execution:(id:string|number)=>get<Execution>(`/soar/executions/${id}`),events:(id:string|number)=>get<SoarRecord[]>(`/soar/executions/${id}/events`),steps:(id:string|number)=>get<SoarRecord[]>(`/soar/executions/${id}/steps`),resume:(id:string|number)=>post<Execution>(`/soar/executions/${id}/resume`),cancelExecution:(id:string|number,reason:string)=>post<Execution>(`/soar/executions/${id}/cancel`,{reason}),retry:(id:string|number,reason:string)=>post<Execution>(`/soar/executions/${id}/retry`,{reason}),requestRollback:(id:string|number,reason:string)=>post<SoarRecord[]>(`/soar/executions/${id}/request-rollback`,{reason}),processDue:(batch_size=25)=>post<Record<string,unknown>>('/soar/executions/process-due',{batch_size}),
  approvals:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/approvals',params),approval:(id:string|number)=>get<SoarRecord>(`/soar/approvals/${id}`),approve:(id:string|number,note:string)=>post<SoarRecord>(`/soar/approvals/${id}/approve`,{note}),reject:(id:string|number,note:string)=>post<SoarRecord>(`/soar/approvals/${id}/reject`,{note}),cancelApproval:(id:string|number,note:string)=>post<SoarRecord>(`/soar/approvals/${id}/cancel`,{note}),
  analystInputs:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/analyst-inputs',params),analystInput:(id:string|number)=>get<SoarRecord>(`/soar/analyst-inputs/${id}`),submitInput:(id:string|number,response:Record<string,unknown>)=>post<SoarRecord>(`/soar/analyst-inputs/${id}/submit`,{response}),cancelInput:(id:string|number,note:string)=>post<SoarRecord>(`/soar/analyst-inputs/${id}/cancel`,{note}),
  rollbacks:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/rollbacks',params),rollback:(id:string|number)=>get<SoarRecord>(`/soar/rollbacks/${id}`),approveRollback:(id:string|number,note:string)=>post<SoarRecord>(`/soar/rollbacks/${id}/approve`,{note}),executeRollback:(id:string|number)=>post<SoarRecord>(`/soar/rollbacks/${id}/execute`,{confirmation:'EXECUTE APPROVED ROLLBACK'}),cancelRollback:(id:string|number,note:string)=>post<SoarRecord>(`/soar/rollbacks/${id}/cancel`,{note}),
  templates:(params?:Record<string,unknown>)=>get<Page<Playbook>>('/soar/templates',params),template:(id:string|number)=>get<Playbook>(`/soar/templates/${id}`),cloneTemplate:(id:string|number,name:string)=>post<Playbook>(`/soar/templates/${id}/clone`,{name,change_summary:'Cloned protected demonstration template'}),
  reports:(params?:Record<string,unknown>)=>get<Page<SoarRecord>>('/soar/reports',params),createReport:(data:Record<string,unknown>)=>post<SoarRecord>('/soar/reports',data),report:(id:string|number)=>get<SoarRecord>(`/soar/reports/${id}`),downloadReport:(id:string|number)=>apiClient.get(`/soar/reports/${id}/download`,{responseType:'blob'}).then(r=>r.data as Blob),
};
