import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import type { SocAlertDetail, SocAlertStatus } from '../../types';
import { vulnscopeApi } from '../../api/vulnscope';
import { EmptyState, PageShell, SectionCard } from '../../components/ui';
import { AlertSeverityBadge } from './components/AlertSeverityBadge'; import { AlertStatusBadge } from './components/AlertStatusBadge'; import { ConfidenceBadge } from './components/ConfidenceBadge'; import { EventTimeline } from './components/EventTimeline'; import { EvidenceEventTable } from './components/EvidenceEventTable'; import { LocalSimulationNotice } from './components/LocalSimulationNotice'; import { ThreatIntelCard } from './components/ThreatIntelCard';

export function AlertDetails() {
  const { alertId } = useParams(); const [alert, setAlert] = useState<SocAlertDetail | null>(null); const [notes, setNotes] = useState(''); const [error, setError] = useState(false);
  const load = useCallback(async () => { try { const item = await vulnscopeApi.getSocAlert(Number(alertId)); setAlert(item); setNotes(item.analyst_notes || ''); } catch { setError(true); } }, [alertId]);
  useEffect(() => { void load(); }, [load]);
  const update = async (status?: SocAlertStatus) => { if (!alert) return; try { await vulnscopeApi.updateSocAlert(alert.id, { status, analyst_notes: notes }); toast.success('Alert updated.'); await load(); } catch { toast.error('Invalid status transition or save failed.'); } };
  const enrich = async () => { if (!alert?.source_ip) return toast.error('Alert has no source IP.'); try { await vulnscopeApi.enrichSocIndicator({ alert_id: alert.id, indicator_type: 'ip', indicator_value: alert.source_ip }); toast.success('Local mock enrichment complete.'); await load(); } catch { toast.error('Enrichment failed.'); } };
  const block = async () => { if (!alert?.source_ip) return toast.error('Alert has no source IP.'); try { await vulnscopeApi.createSocBlocklistEntry({ indicator_type: 'ip', indicator_value: alert.source_ip, reason: `Analyst simulation for alert #${alert.id}`, source_alert_id: alert.id }); toast.success('Added to local simulated blocklist.'); await load(); } catch { toast.error('Simulated blocklist update failed.'); } };
  if (error) return <PageShell><EmptyState title="Alert unavailable" description="The alert could not be loaded." /></PageShell>;
  if (!alert) return <PageShell>Loading alert...</PageShell>;
  return <PageShell><Link to="/soc/alerts" className="text-sm text-primary">← Alerts</Link><div><div className="flex flex-wrap items-center gap-2"><AlertSeverityBadge severity={alert.severity} /><AlertStatusBadge status={alert.status} /><ConfidenceBadge confidence={alert.confidence} /></div><h1 className="mt-3 text-3xl font-bold">{alert.title}</h1><p className="mt-2 text-muted-foreground">{alert.description}</p></div><LocalSimulationNotice /><div className="flex flex-wrap gap-2">{(['investigating', 'contained', 'resolved', 'false_positive'] as SocAlertStatus[]).map(status => <button key={status} onClick={() => void update(status)} className="rounded-md border border-border px-3 py-2 text-sm capitalize">Mark {status.replaceAll('_', ' ')}</button>)}<button onClick={() => void enrich()} className="rounded-md bg-indigo-600 px-3 py-2 text-sm text-white">Local mock enrichment</button><button onClick={() => void block()} className="rounded-md bg-amber-600 px-3 py-2 text-sm text-white">Add to simulated blocklist</button></div><div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Evidence Summary"><p className="text-sm text-muted-foreground">{alert.evidence_summary}</p><p className="mt-3 text-xs">Rule: {alert.rule_code} · {alert.rule_name}</p></SectionCard><SectionCard title="Event Timeline"><EventTimeline events={alert.events} /></SectionCard></div><SectionCard title="Correlated Events"><EvidenceEventTable events={alert.events} /></SectionCard><SectionCard title="Analyst Notes"><textarea value={notes} onChange={event => setNotes(event.target.value)} rows={5} className="w-full rounded-md border border-input bg-background p-3" /><button onClick={() => void update()} className="mt-3 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Save notes</button></SectionCard><SectionCard title="Local Threat Intelligence">{alert.enrichments.length ? <div className="space-y-3">{alert.enrichments.map(item => <ThreatIntelCard key={item.id} result={item} />)}</div> : <p className="text-sm text-muted-foreground">No local enrichment performed.</p>}</SectionCard></PageShell>;
}
