import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import type { SocLogSource } from '../../types';
import { vulnscopeApi } from '../../api/vulnscope';
import { EmptyState, PageHeader, PageShell, SectionCard } from '../../components/ui';
import { LogImportDropzone } from './components/LogImportDropzone';

const TYPES: SocLogSource['source_type'][] = ['simulator', 'jsonl', 'csv', 'access_log', 'auth_log', 'key_value'];

export function LogSources() {
  const [sources, setSources] = useState<SocLogSource[]>([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ name: '', source_type: 'jsonl' as SocLogSource['source_type'] }); const [uploading, setUploading] = useState<number | null>(null);
  const load = useCallback(async () => { try { setSources(await vulnscopeApi.listSocSources()); } catch { toast.error('Sources could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { await vulnscopeApi.createSocSource({ name: form.name, description: null, source_type: form.source_type, parser_type: form.source_type, enabled: true }); setForm({ ...form, name: '' }); toast.success('Log source created.'); await load(); } catch { toast.error('Source could not be created.'); } };
  const edit = async (source: SocLogSource) => { const name = prompt('Source name', source.name); const requestedType = prompt(`Parser/source type: ${TYPES.join(', ')}`, source.source_type) as SocLogSource['source_type'] | null; if (!name || !requestedType || !TYPES.includes(requestedType)) return; try { await vulnscopeApi.updateSocSource(source.id, { name, source_type: requestedType, parser_type: requestedType }); toast.success('Source updated.'); await load(); } catch { toast.error('Source update failed validation.'); } };
  const upload = async (source: SocLogSource, file: File) => { setUploading(source.id); try { const result = await vulnscopeApi.importSocLog(source.id, file); toast.success(`${result.accepted_events} events accepted.`); await load(); } catch { toast.error('Log import failed safety validation.'); } finally { setUploading(null); } };
  return <PageShell><PageHeader title="Log Sources" subtitle="Manage local text-log sources. Imported content is never executed." /><SectionCard title="Create Source"><form onSubmit={create} className="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input required minLength={2} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Source name" className="h-10 rounded-md border border-input bg-background px-3" /><select value={form.source_type} onChange={event => setForm({ ...form, source_type: event.target.value as SocLogSource['source_type'] })} className="h-10 rounded-md border border-input bg-background px-3">{TYPES.map(type => <option key={type}>{type}</option>)}</select><button className="h-10 rounded-md bg-primary px-4 font-semibold text-primary-foreground">Create</button></form></SectionCard>{loading ? <p>Loading sources...</p> : sources.length ? <div className="grid gap-4 xl:grid-cols-2">{sources.map(source => <SectionCard key={source.id} title={source.name} subtitle={`${source.source_type} · ${source.event_count} events`}><label className="mb-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={source.enabled} onChange={() => void vulnscopeApi.updateSocSource(source.id, { enabled: !source.enabled }).then(load)} className="accent-primary" />Enabled</label>{source.source_type !== 'simulator' && <LogImportDropzone disabled={uploading === source.id} onFile={file => void upload(source, file)} />}<div className="mt-4 flex gap-4"><button onClick={() => void edit(source)} className="text-xs text-primary">Edit source and parser</button><button onClick={() => { if (confirm(`Delete ${source.name}?`)) void vulnscopeApi.deleteSocSource(source.id).then(load).catch(() => toast.error('Sources with events/imports cannot be deleted.')); }} className="text-xs text-red-300">Delete source</button></div></SectionCard>)}</div> : <EmptyState title="No log sources" description="Create a source for simulation or safe local file import." />}</PageShell>;
}
