import { useState, type ReactNode } from 'react';
import clsx from 'clsx';

const badge='inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold capitalize';
export function DetectionRuleStatusBadge({status}:{status:string}){return <span className={`${badge} border-cyan-500/40 bg-cyan-500/10`}>{status}</span>}
export function DetectionSeverityBadge({severity}:{severity:string}){return <span className={clsx(badge,severity==='critical'?'border-red-500 text-red-200':severity==='high'?'border-orange-500 text-orange-200':'border-amber-500/50')}>{severity}</span>}
export function RuleQualityMeter({value}:{value:number}){return <div aria-label={`Rule quality ${value} percent`} className="min-w-28"><div className="text-xs">{value.toFixed(1)}%</div><div className="h-2 rounded bg-muted"><div className="h-full rounded bg-emerald-400" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
export function RuleVersionTimeline({versions}:{versions:Array<Record<string,unknown>>}){return <ol className="space-y-2 border-l pl-4">{versions.map(v=><li key={String(v.id)}><strong>Version {String(v.version_number)}</strong><div className="text-xs text-muted-foreground">{String(v.change_summary)} · {String(v.content_sha256).slice(0,12)}</div></li>)}</ol>}
export function RuleValidationPanel({validation}:{validation:Record<string,unknown>}){const errors=(validation.errors as unknown[]||[]);const warnings=(validation.warnings as unknown[]||[]);return <div className="rounded border p-4"><h3 className="font-semibold">Backend validation: {validation.valid?'valid':'invalid'}</h3><p className="text-sm text-muted-foreground">Complexity {String(validation.complexity_score??0)} · {String(validation.estimated_scan_scope??'bounded')}</p>{errors.map((x,i)=><p key={i} className="text-sm text-red-300">{String(x)}</p>)}{warnings.map((x,i)=><p key={i} className="text-sm text-amber-300">{String(x)}</p>)}</div>}
export function SigmaImportPreview({preview}:{preview:Record<string,unknown>|null}){if(!preview)return null;const items=preview.previews as Array<Record<string,unknown>>||[];return <div className="rounded border p-4"><h3 className="font-semibold">Safe import preview</h3>{items.map((x,i)=><div key={i} className="mt-2 rounded bg-muted p-2 text-sm">{String(x.title)} · {x.valid?'valid':'invalid'} · {((x.warnings as unknown[])||[]).length} warnings</div>)}</div>}
export function DetectionConditionBuilder({selections,condition,onChange}:{selections:string;condition:string;onChange:(s:string,c:string)=>void}){return <div className="grid gap-3"><label className="text-sm">Selections (JSON)<textarea className="mt-1 min-h-40 w-full rounded border bg-background p-3 font-mono text-xs" value={selections} onChange={e=>onChange(e.target.value,condition)}/></label><label className="text-sm">Bounded condition<input className="mt-1 w-full rounded border bg-background p-2" value={condition} onChange={e=>onChange(selections,e.target.value)}/></label></div>}
export function DetectionTestCaseEditor({onSubmit}:{onSubmit:(value:Record<string,unknown>)=>Promise<void>}){const [name,setName]=useState('Positive example');const [payload,setPayload]=useState('{"event.category":"authentication","event.outcome":"failure"}');const [expected,setExpected]=useState(true);return <div className="grid gap-2 rounded border p-4"><h3 className="font-semibold">Synthetic test case</h3><input className="rounded border bg-background p-2" value={name} onChange={e=>setName(e.target.value)}/><textarea className="min-h-24 rounded border bg-background p-2 font-mono text-xs" value={payload} onChange={e=>setPayload(e.target.value)}/><label><input type="checkbox" checked={expected} onChange={e=>setExpected(e.target.checked)}/> Expected match</label><button className="rounded bg-primary p-2" onClick={()=>onSubmit({name,event_payload:JSON.parse(payload),expected_match:expected,enabled:true})}>Add test</button></div>}
export function TestExecutionSummary({result}:{result:Record<string,unknown>|null}){if(!result)return null;return <div className="rounded border p-4"><strong>{result.passed?'All tests passed':'Tests require attention'}</strong><p>{String(result.passed_count??0)} / {String(result.total??0)} passed</p></div>}
export function AttackTechniqueBadge({id,name}:{id:string;name?:string}){return <span className={`${badge} border-violet-500/40`}>{id}{name?` · ${name}`:''}</span>}
export function AttackCoverageMatrix({items}:{items:Array<Record<string,unknown>>}){return <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Technique</th><th>Covered</th><th>Active rules</th><th>Quality</th><th>Matches</th></tr></thead><tbody>{items.map(x=><tr key={String(x.external_id)} className="border-t"><td className="p-2"><AttackTechniqueBadge id={String(x.external_id)} name={String(x.name)}/></td><td className="text-center">{x.covered?'Yes':'No'}</td><td className="text-center">{String(x.active_rule_count)}</td><td className="text-center">{String(x.average_quality)}</td><td className="text-center">{String(x.match_count)}</td></tr>)}</tbody></table></div>}
export function DetectionRiskBadge({score}:{score:number}){return <span className={`${badge} border-orange-500/50`}>{score.toFixed(1)} · {score>=80?'critical':score>=60?'high':score>=40?'medium':score>=20?'low':'informational'}</span>}
export function MatchDispositionDialog({onSubmit}:{onSubmit:(status:string,note:string)=>Promise<void>}){const [status,setStatus]=useState('reviewing');const [note,setNote]=useState('');return <div className="grid gap-2 rounded border p-4"><select className="rounded border bg-background p-2" value={status} onChange={e=>setStatus(e.target.value)}>{['reviewing','confirmed','false_positive','accepted_risk'].map(x=><option key={x}>{x}</option>)}</select><textarea className="rounded border bg-background p-2" value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/><button className="rounded bg-primary p-2" onClick={()=>void onSubmit(status,note)}>Save disposition</button></div>}
export function SuppressionEditor({onSubmit}:{onSubmit:(value:Record<string,unknown>)=>Promise<void>}){const [name,setName]=useState('Known benign event');const [field,setField]=useState('source.ip');const [value,setValue]=useState('192.0.2.1');return <div className="grid gap-2 rounded border p-4"><input className="rounded border bg-background p-2" value={name} onChange={e=>setName(e.target.value)}/><div className="flex gap-2"><input className="w-full rounded border bg-background p-2" value={field} onChange={e=>setField(e.target.value)}/><input className="w-full rounded border bg-background p-2" value={value} onChange={e=>setValue(e.target.value)}/></div><button className="rounded bg-primary p-2" onClick={()=>onSubmit({name,description:'Explicit analyst suppression for a known benign pattern.',field_conditions:{[field]:value},enabled:true})}>Create suppression</button></div>}
export function DetectionEvidencePanel({evidence,fields}:{evidence:string;fields?:Record<string,unknown>}){const [expanded,setExpanded]=useState(false);const shown=expanded?evidence:evidence.slice(0,500);return <div className="rounded border p-4"><h3 className="font-semibold">Escaped evidence</h3><pre className="mt-2 whitespace-pre-wrap break-all text-xs">{shown}</pre>{evidence.length>500&&<button className="text-xs text-primary" onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':'Expand'}</button>}<pre className="mt-2 whitespace-pre-wrap break-all text-xs">{JSON.stringify(fields??{},null,2)}</pre><p className="text-xs text-muted-foreground">URLs and command lines are displayed as text and never executed.</p></div>}
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>}
