/* oxlint-disable react/only-export-components */
import type {ReactNode} from 'react';
import type {ActionDefinition,PlaybookStep,Validation} from '../../api/soar';

const badge='inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold';
export const control='rounded-md border border-border bg-background px-3 py-2 text-sm';
export const button='rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50';
export function PlaybookStatusBadge({status}:{status:string}){return <span className={`${badge} border-cyan-400/40 bg-cyan-500/10 text-cyan-100`}>{status}</span>}
export function ExecutionStatusBadge({status}:{status:string}){return <span className={`${badge} ${status==='failed'||status==='rollback_failed'?'border-red-400/50 bg-red-500/10 text-red-200':status.startsWith('waiting')?'border-amber-400/50 bg-amber-500/10 text-amber-100':'border-emerald-400/40 bg-emerald-500/10 text-emerald-100'}`}>{status}</span>}
export function StepExecutionStatusBadge({status}:{status:string}){return <ExecutionStatusBadge status={status}/>}export function ApprovalStatusBadge({status}:{status:string}){return <ExecutionStatusBadge status={status}/>}export function TriggerSourceBadge({source}:{source:string}){return <span className={badge}>{source}</span>}
export function ActionSafetyBadge({classification}:{classification:string}){const warning=classification==='sensitive_local'||classification==='simulation_only';return <span className={`${badge} ${warning?'border-amber-400 bg-amber-500/15 text-amber-100':'border-blue-400/40 bg-blue-500/10 text-blue-100'}`}>{classification.replaceAll('_',' ')}</span>}
export function ExecutionModeBadge({mode}:{mode:string}){return <span className={`${badge} ${mode==='simulation'?'border-fuchsia-400/50 bg-fuchsia-500/10 text-fuchsia-100':'border-slate-400/40'}`}>{mode.replaceAll('_',' ')}</span>}
export function IdempotencyStatusBadge({value}:{value:string}){return <span className={badge} title={value}>deduplicated · {value.slice(0,10)}…</span>}
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-lg border border-border bg-card/80 p-4"><h2 className="font-semibold">{title}</h2><div className="mt-3">{children}</div></section>}
export function PlaybookStepCard({step,index,onMove}:{step:PlaybookStep;index:number;onMove?:(delta:number)=>void}){return <article className="rounded border p-3" tabIndex={0}><div className="flex items-center justify-between gap-3"><div><b>{index+1}. {step.name||step.key}</b><p className="text-xs text-muted-foreground">{step.key} · {step.type}</p></div>{onMove&&<div className="flex gap-1"><button className={control} aria-label={`Move ${step.key} up`} onClick={()=>onMove(-1)}>↑</button><button className={control} aria-label={`Move ${step.key} down`} onClick={()=>onMove(1)}>↓</button></div>}</div>{step.action_key&&<div className="mt-2 text-sm">Action: {step.action_key}</div>}<div className="mt-2 text-xs">Success: {step.on_success||'terminal'} · Failure: {step.on_failure||'not set'} · Timeout: {step.on_timeout||'not set'}</div></article>}
export function PlaybookFlowView({steps,current}:{steps:PlaybookStep[];current?:string}){return <Panel title="Bounded playbook flow"><ol className="space-y-2">{steps.slice(0,50).map((step,index)=><li key={step.key} aria-current={current===step.key?'step':undefined} className={current===step.key?'ring-2 ring-primary rounded':''}><PlaybookStepCard step={step} index={index}/></li>)}</ol><p className="sr-only">Each card lists labelled success, failure, and timeout routes.</p></Panel>}
export function PlaybookValidationPanel({validation}:{validation?:Validation}){if(!validation)return <Panel title="Validation"><p className="text-sm text-muted-foreground">Validation has not run for this view.</p></Panel>;return <Panel title={`Validation · ${validation.valid?'valid':'invalid'}`}><p className="text-sm">Complexity {validation.complexity_score}/100 · {validation.automatic_local_eligible?'automatic-local eligible':'manual/proposal processing'}</p>{validation.errors.map((x,i)=><p key={`e${i}`} className="mt-2 text-sm text-red-200">{x.step_key&&`${x.step_key}: `}{x.message}</p>)}{validation.warnings.map((x,i)=><p key={`w${i}`} className="mt-2 text-sm text-amber-100">{x.step_key&&`${x.step_key}: `}{x.message}</p>)}</Panel>}
export function PlaybookVersionTimeline({items}:{items:Array<Record<string,unknown>>}){return <Panel title="Immutable version timeline"><ol className="space-y-2">{items.map(x=><li key={String(x.id)} className="rounded border p-3">Version {String(x.version_number)} · {String(x.change_summary)} · SHA-256 {String(x.content_sha256).slice(0,16)}…</li>)}</ol></Panel>}
export function VersionComparisonPanel({data}:{data:Record<string,unknown>}){return <Panel title="Version comparison"><pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap text-xs">{Array.isArray(data.diff)?data.diff.join('\n'):'Choose two immutable versions.'}</pre></Panel>}
export function ExecutionTimeline({items}:{items:Array<Record<string,unknown>>}){return <Panel title="Append-only execution timeline"><ol className="space-y-3">{items.map(x=><li key={String(x.id)} className="border-l-2 pl-3"><b>{String(x.event_type)}</b><p className="text-sm text-muted-foreground">{String(x.summary)}</p><time className="text-xs">{String(x.created_at)}</time></li>)}</ol></Panel>}
export function StepExecutionPanel({items}:{items:Array<Record<string,unknown>>}){return <Panel title="Step attempts"><div className="space-y-2">{items.map(x=><div key={String(x.id)} className="rounded border p-3"><StepExecutionStatusBadge status={String(x.status)}/><b className="ml-2">{String(x.step_name)}</b><span className="ml-2 text-xs">attempt {String(x.attempt_number)} · {String(x.action_key||x.step_type)}</span></div>)}</div></Panel>}
export function ExecutionVariablePanel({value}:{value:unknown}){return <Panel title="Redacted execution variables"><pre className="max-h-72 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(value??{},null,2)}</pre></Panel>}
export function ApprovalDecisionDialog({onDecision,busy=false}:{onDecision:(decision:'approve'|'reject',note:string)=>void;busy?:boolean}){return <Panel title="Approval decision"><label className="text-sm">Decision note<input id="soar-approval-note" className={`${control} mt-1 w-full`} maxLength={2000}/></label><div className="mt-3 flex gap-2"><button className={button} disabled={busy} onClick={()=>onDecision('approve',(document.getElementById('soar-approval-note') as HTMLInputElement)?.value)}>Confirm approval</button><button className={control} disabled={busy} onClick={()=>onDecision('reject',(document.getElementById('soar-approval-note') as HTMLInputElement)?.value)}>Reject</button></div></Panel>}
export function AnalystInputDialog({fields,onSubmit}:{fields:Array<Record<string,unknown>>;onSubmit:(value:Record<string,unknown>)=>void}){return <Panel title="Analyst input"><div className="space-y-2">{fields.slice(0,20).map(field=><label key={String(field.name)} className="block text-sm">{String(field.label||field.name)}<input id={`field-${String(field.name)}`} className={`${control} mt-1 w-full`} maxLength={8000}/></label>)}</div><button className={`${button} mt-3`} onClick={()=>onSubmit(Object.fromEntries(fields.map(field=>[String(field.name),(document.getElementById(`field-${String(field.name)}`) as HTMLInputElement)?.value])))}>Submit once</button></Panel>}
export function DryRunSummary({execution}:{execution:Record<string,unknown>}){return <Panel title="Dry-run summary"><p className="text-sm">No case, task, notification, assignment, tag, session, or user mutation is performed. Status: {String(execution.status||'not started')}.</p></Panel>}
export function SimulationWarningPanel(){return <div className="rounded border-2 border-fuchsia-400 bg-fuchsia-500/10 p-4 font-semibold text-fuchsia-100" role="note">SIMULATION ONLY — NO EXTERNAL ACTION IS PERFORMED. ThreatScope never claims real containment.</div>}
export function RollbackRequestDialog({onRequest}:{onRequest:(reason:string)=>void}){return <Panel title="Request compensation"><textarea id="rollback-reason" className={`${control} min-h-24 w-full`} maxLength={2000} placeholder="Required reason"/><button className={`${button} mt-2`} onClick={()=>onRequest((document.getElementById('rollback-reason') as HTMLTextAreaElement)?.value)}>Request rollback records</button></Panel>}
export function RollbackResultPanel({record}:{record:Record<string,unknown>}){return <Panel title="Rollback result"><ExecutionStatusBadge status={String(record.status||'unknown')}/><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(record,null,2)}</pre></Panel>}
export function TriggerConditionBuilder({value,onChange}:{value:Record<string,unknown>;onChange:(v:Record<string,unknown>)=>void}){return <Panel title="Declarative trigger condition"><div className="grid gap-2 sm:grid-cols-3"><input className={control} value={String(value.left||'${trigger.severity}')} onChange={e=>onChange({...value,left:e.target.value})} aria-label="Allowed trigger field"/><select className={control} value={String(value.operator||'equals')} onChange={e=>onChange({...value,operator:e.target.value})}><option>equals</option><option>contains</option><option>greater_than_or_equal</option><option>exists</option></select><input className={control} value={String(value.right||'high')} onChange={e=>onChange({...value,right:e.target.value})} aria-label="Comparison value"/></div><p className="mt-2 text-xs text-muted-foreground">No regular expression, script, SQL, URL, or arbitrary expression support.</p></Panel>}
export function ActionConfigurationPanel({action,value,onChange}:{action?:ActionDefinition;value:string;onChange:(v:string)=>void}){return <Panel title="Allowlisted action configuration">{action&&<div className="mb-2 flex gap-2"><ActionSafetyBadge classification={action.safety_classification}/><span>{action.display_name}</span></div>}<textarea className={`${control} min-h-28 w-full font-mono`} value={value} onChange={e=>onChange(e.target.value)} aria-label="Bounded action JSON configuration"/><p className="mt-2 text-xs text-muted-foreground">Only schema-declared local fields are accepted. Commands, modules, SQL, URLs, and callable paths are rejected by the server.</p></Panel>}
export function ActionPolicyDialog({action,onSave}:{action:ActionDefinition;onSave:(data:Record<string,unknown>)=>void}){return <Panel title={`Policy · ${action.display_name}`}><label className="flex gap-2 text-sm"><input type="checkbox" defaultChecked={Boolean(action.policy?.enabled)} id={`policy-${action.action_key}`}/>Enabled</label><button className={`${button} mt-3`} onClick={()=>onSave({enabled:(document.getElementById(`policy-${action.action_key}`) as HTMLInputElement).checked})}>Save Administrator policy</button></Panel>}
export function EvidenceSnapshotPanel({items}:{items:Array<Record<string,unknown>>}){return <Panel title="Redacted evidence snapshots"><div className="space-y-2">{items.map(x=><div key={String(x.id)} className="rounded border p-3 text-sm">{String(x.summary)} · SHA-256 {String(x.content_sha256).slice(0,16)}…</div>)}</div></Panel>}
export function ExecutionErrorPanel({execution}:{execution:Record<string,unknown>}){if(!execution.error_code)return null;return <div role="alert" className="rounded border border-red-400 bg-red-500/10 p-4"><b>{String(execution.error_code)}</b><p>{String(execution.error_summary)}</p></div>}
