import type {
  CrawlNode,
  DashboardSummary,
  EvidenceArtifact,
  Finding,
  Notification,
  PostureDiff,
  Report,
  Scan,
  SearchResults,
  Target,
  UserProfile,
  AppSettings,
} from '../types';

export interface PolicyCheck {
  id: string;
  title: string;
  expected_state: string;
  severity_impact: string;
  related_finding_titles?: string[];
}

export interface PolicyPack {
  policy_id: string;
  title: string;
  description: string;
  checks: PolicyCheck[];
}

const now = Date.now();
const isoMinutesAgo = (minutesAgo: number) => new Date(now - minutesAgo * 60_000).toISOString();
const isoHoursAgo = (hoursAgo: number) => new Date(now - hoursAgo * 3_600_000).toISOString();
const isoDaysAgo = (daysAgo: number) => new Date(now - daysAgo * 86_400_000).toISOString();

let nextTargetId = 5;
let nextScanId = 5;
let nextFindingId = 9;
let nextCrawlNodeId = 7;
let nextEvidenceId = 5;
let nextDiffId = 3;
let nextReportId = 4;
let nextNotificationId = 5;

let demoProfile: UserProfile = {
  id: 1,
  full_name: 'Avery Chen',
  email: 'avery.chen@vulnscope.demo',
  organization: 'VulnScope Demo Lab',
  role: 'Security Analyst',
  avatar_initials: 'AC',
  created_at: isoDaysAgo(30),
  updated_at: isoDaysAgo(2),
};

let demoSettings: AppSettings = {
  id: 1,
  theme: 'dark',
  default_scan_profile: 'Standard Safe Scan',
  request_timeout_seconds: 10,
  max_pages_standard: 25,
  max_pages_full: 50,
  max_depth_standard: 2,
  max_depth_full: 3,
  rate_limit_delay_ms: 500,
  report_company_name: 'VulnScope Demo Lab',
  report_footer_text: 'Generated by VulnScope - Authorized Testing Only',
  auto_generate_report: true,
  created_at: isoDaysAgo(30),
  updated_at: isoHoursAgo(12),
};

const demoPolicies: PolicyPack[] = [
  {
    policy_id: 'web-baseline',
    title: 'Web Baseline',
    description: 'Minimum browser-facing security controls expected on public web applications.',
    checks: [
      { id: 'hsts', title: 'Strict-Transport-Security present', expected_state: 'All public pages should send HSTS with a long max-age.', severity_impact: 'high', related_finding_titles: ['Missing HSTS'] },
      { id: 'secure-cookies', title: 'Session cookies hardened', expected_state: 'Session cookies should be marked Secure, HttpOnly, and SameSite.', severity_impact: 'critical', related_finding_titles: ['Weak session cookie flags'] },
      { id: 'csp', title: 'Content Security Policy enforced', expected_state: 'Interactive pages should use a restrictive CSP.', severity_impact: 'high', related_finding_titles: ['Missing Content Security Policy'] },
    ],
  },
  {
    policy_id: 'browser-hardening',
    title: 'Browser Hardening',
    description: 'Controls that reduce client-side abuse, clickjacking, and disclosure risk.',
    checks: [
      { id: 'frame-ancestors', title: 'Clickjacking protection enabled', expected_state: 'Frame-ancestors or X-Frame-Options should prevent embedding.', severity_impact: 'medium', related_finding_titles: ['Missing frame protection'] },
      { id: 'referrer-policy', title: 'Sensitive referrer data suppressed', expected_state: 'Referrer-Policy should avoid leaking internal URLs.', severity_impact: 'low', related_finding_titles: ['Leaky referrer policy'] },
    ],
  },
  {
    policy_id: 'public-exposure',
    title: 'Public Exposure',
    description: 'Commonly exposed paths and files that should not be reachable from the public internet.',
    checks: [
      { id: 'git-exposure', title: 'Source control metadata not exposed', expected_state: 'Public endpoints should not expose .git or backups.', severity_impact: 'critical', related_finding_titles: ['Exposed .git directory'] },
      { id: 'backup-files', title: 'Backup files blocked', expected_state: 'Backup archives and stale config files should be inaccessible.', severity_impact: 'high', related_finding_titles: ['Exposed backup file'] },
    ],
  },
  {
    policy_id: 'auth-surface',
    title: 'Auth Surface',
    description: 'Login and session surface checks that affect authentication exposure.',
    checks: [
      { id: 'login-form', title: 'Password fields are protected', expected_state: 'Login forms should avoid autocomplete abuse.', severity_impact: 'medium', related_finding_titles: ['Password field missing autocomplete protection'] },
      { id: 'cors', title: 'CORS policy is narrow', expected_state: 'Wildcard CORS should not be used on sensitive endpoints.', severity_impact: 'high', related_finding_titles: ['Wildcard CORS on sensitive endpoint'] },
    ],
  },
];

let demoTargets: Target[] = [
  { id: 1, name: 'Orion Commerce Portal', base_url: 'https://portal.orion.demo', domain: 'portal.orion.demo', environment: 'production', authorization_confirmed: true, created_at: isoDaysAgo(10) },
  { id: 2, name: 'Northstar Support Hub', base_url: 'https://support.northstar.demo', domain: 'support.northstar.demo', environment: 'staging', authorization_confirmed: true, created_at: isoDaysAgo(8) },
  { id: 3, name: 'Atlas Marketing Site', base_url: 'https://marketing.atlas.demo', domain: 'marketing.atlas.demo', environment: 'public', authorization_confirmed: true, created_at: isoDaysAgo(6) },
  { id: 4, name: 'Demo Target Lab', base_url: 'http://demo-target:8080', domain: 'demo-target', environment: 'local', authorization_confirmed: true, created_at: isoDaysAgo(2) },
];

let demoScans: Scan[] = [
  { id: 1, target_id: 1, profile: 'Standard Safe Scan', status: 'completed', started_at: isoDaysAgo(5), completed_at: isoDaysAgo(5), total_findings: 3, risk_score: 5.8, overall_posture_score: 72, posture_transport_security: 78, posture_browser_defense: 70, posture_session_safety: 76, posture_exposure_hygiene: 68, posture_authentication_surface: 69, error_message: null },
  { id: 2, target_id: 2, profile: 'Passive Scan', status: 'completed', started_at: isoDaysAgo(3), completed_at: isoDaysAgo(3), total_findings: 1, risk_score: 3.4, overall_posture_score: 84, posture_transport_security: 86, posture_browser_defense: 82, posture_session_safety: 87, posture_exposure_hygiene: 80, posture_authentication_surface: 85, error_message: null },
  { id: 3, target_id: 3, profile: 'Full Safe Scan', status: 'completed', started_at: isoDaysAgo(1), completed_at: isoDaysAgo(1), total_findings: 2, risk_score: 4.9, overall_posture_score: 79, posture_transport_security: 80, posture_browser_defense: 77, posture_session_safety: 81, posture_exposure_hygiene: 75, posture_authentication_surface: 82, error_message: null },
  { id: 4, target_id: 1, profile: 'Full Safe Scan', status: 'completed', started_at: isoHoursAgo(4), completed_at: isoHoursAgo(4), total_findings: 4, risk_score: 6.9, overall_posture_score: 64, posture_transport_security: 70, posture_browser_defense: 60, posture_session_safety: 68, posture_exposure_hygiene: 61, posture_authentication_surface: 58, error_message: null },
];

let demoFindings: Finding[] = [
  { id: 1, scan_id: 1, target_id: 1, title: 'Missing Content Security Policy', severity: 'high', category: 'Browser Defenses', affected_url: 'https://portal.orion.demo/dashboard', description: 'The dashboard response does not set a Content Security Policy header.', evidence: 'Content-Security-Policy header missing from the response.', impact: 'Injected JavaScript would have a wider blast radius.', remediation: 'Add a restrictive CSP that limits script sources.', confidence: 'high', risk_score: 7.4, created_at: isoDaysAgo(5) },
  { id: 2, scan_id: 1, target_id: 1, title: 'Weak session cookie flags', severity: 'critical', category: 'Session Safety', affected_url: 'https://portal.orion.demo/login', description: 'The session cookie is missing one or more hardening attributes.', evidence: 'Set-Cookie header observed without Secure and SameSite flags.', impact: 'Session hijacking and cross-site request abuse become easier.', remediation: 'Set Secure, HttpOnly, and SameSite on session cookies.', confidence: 'high', risk_score: 9.1, created_at: isoDaysAgo(5) },
  { id: 3, scan_id: 1, target_id: 1, title: 'Leaky referrer policy', severity: 'low', category: 'Browser Defenses', affected_url: 'https://portal.orion.demo/account', description: 'The application uses a permissive referrer policy.', evidence: 'Referrer-Policy header not set.', impact: 'Sensitive URL paths can be exposed to third-party services.', remediation: 'Set a restrictive referrer policy.', confidence: 'medium', risk_score: 3.1, created_at: isoDaysAgo(5) },
  { id: 4, scan_id: 2, target_id: 2, title: 'Missing HSTS', severity: 'medium', category: 'Transport Security', affected_url: 'https://support.northstar.demo', description: 'The site does not instruct browsers to prefer HTTPS for future requests.', evidence: 'Strict-Transport-Security header missing.', impact: 'Users could be downgraded to insecure transport.', remediation: 'Enable HSTS with a long max-age.', confidence: 'high', risk_score: 5.0, created_at: isoDaysAgo(3) },
  { id: 5, scan_id: 3, target_id: 3, title: 'Exposed .git directory', severity: 'high', category: 'Public Exposure', affected_url: 'https://marketing.atlas.demo/.git/', description: 'A public request reaches repository metadata that should never be exposed.', evidence: 'Directory listing returned source control files.', impact: 'An attacker could recover source code or secrets.', remediation: 'Block access to VCS metadata.', confidence: 'high', risk_score: 7.8, created_at: isoDaysAgo(1) },
  { id: 6, scan_id: 4, target_id: 1, title: 'Wildcard CORS on sensitive endpoint', severity: 'high', category: 'Auth Surface', affected_url: 'https://portal.orion.demo/api/session', description: 'The endpoint responds with an overly permissive cross-origin policy.', evidence: 'Access-Control-Allow-Origin: *', impact: 'Cross-origin callers may reach sensitive responses.', remediation: 'Restrict CORS to the exact trusted origins.', confidence: 'high', risk_score: 7.1, created_at: isoHoursAgo(4) },
  { id: 7, scan_id: 4, target_id: 1, title: 'Password field missing autocomplete protection', severity: 'medium', category: 'Auth Surface', affected_url: 'https://portal.orion.demo/login', description: 'The login form exposes a password field without a defensive autocomplete configuration.', evidence: 'Password input observed without autocomplete="current-password".', impact: 'Credential handling becomes less predictable on shared devices.', remediation: 'Set appropriate autocomplete attributes.', confidence: 'medium', risk_score: 4.6, created_at: isoHoursAgo(4) },
  { id: 8, scan_id: 4, target_id: 1, title: 'Missing frame protection', severity: 'low', category: 'Browser Defenses', affected_url: 'https://portal.orion.demo', description: 'The site lacks an anti-framing control.', evidence: 'No frame-busting header observed.', impact: 'The site may be embedded in a hostile frame for clickjacking.', remediation: 'Add X-Frame-Options or a frame-ancestors CSP directive.', confidence: 'medium', risk_score: 3.7, created_at: isoHoursAgo(4) },
];

let demoCrawlNodes: CrawlNode[] = [
  { id: 1, scan_id: 1, target_id: 1, url: 'https://portal.orion.demo/', path: '/', status_code: 200, content_type: 'text/html', page_title: 'Orion Commerce Portal', depth: 0, parent_url: null, has_forms: false, has_password_field: false, finding_count: 0, created_at: isoDaysAgo(5) },
  { id: 2, scan_id: 1, target_id: 1, url: 'https://portal.orion.demo/login', path: '/login', status_code: 200, content_type: 'text/html', page_title: 'Sign in', depth: 1, parent_url: 'https://portal.orion.demo/', has_forms: true, has_password_field: true, finding_count: 2, created_at: isoDaysAgo(5) },
  { id: 3, scan_id: 2, target_id: 2, url: 'https://support.northstar.demo/', path: '/', status_code: 200, content_type: 'text/html', page_title: 'Northstar Support Hub', depth: 0, parent_url: null, has_forms: true, has_password_field: false, finding_count: 1, created_at: isoDaysAgo(3) },
  { id: 4, scan_id: 3, target_id: 3, url: 'https://marketing.atlas.demo/', path: '/', status_code: 200, content_type: 'text/html', page_title: 'Atlas Marketing', depth: 0, parent_url: null, has_forms: false, has_password_field: false, finding_count: 0, created_at: isoDaysAgo(1) },
  { id: 5, scan_id: 4, target_id: 1, url: 'https://portal.orion.demo/', path: '/', status_code: 200, content_type: 'text/html', page_title: 'Orion Commerce Portal', depth: 0, parent_url: null, has_forms: false, has_password_field: false, finding_count: 1, created_at: isoHoursAgo(4) },
  { id: 6, scan_id: 4, target_id: 1, url: 'https://portal.orion.demo/login', path: '/login', status_code: 200, content_type: 'text/html', page_title: 'Sign in', depth: 1, parent_url: 'https://portal.orion.demo/', has_forms: true, has_password_field: true, finding_count: 2, created_at: isoHoursAgo(4) },
];

let demoEvidence: EvidenceArtifact[] = [
  { id: 1, scan_id: 1, target_id: 1, artifact_type: 'header_snapshot', title: 'Missing CSP header snapshot', file_path: null, redacted_text: 'Content-Security-Policy: <missing>\nX-Content-Type-Options: nosniff', related_url: 'https://portal.orion.demo/dashboard', created_at: isoDaysAgo(5) },
  { id: 2, scan_id: 1, target_id: 1, artifact_type: 'html_snippet', title: 'Login form HTML snippet', file_path: null, redacted_text: '<form action="/login">\n  <input type="password" name="password">\n</form>', related_url: 'https://portal.orion.demo/login', created_at: isoDaysAgo(5) },
  { id: 3, scan_id: 3, target_id: 3, artifact_type: 'html_snippet', title: 'Exposed directory listing snippet', file_path: null, redacted_text: '<title>Index of /.git</title>', related_url: 'https://marketing.atlas.demo/.git/', created_at: isoDaysAgo(1) },
  { id: 4, scan_id: 4, target_id: 1, artifact_type: 'header_snapshot', title: 'Wildcard CORS header snapshot', file_path: null, redacted_text: 'Access-Control-Allow-Origin: *\nAccess-Control-Allow-Credentials: true', related_url: 'https://portal.orion.demo/api/session', created_at: isoHoursAgo(4) },
];

let demoDiffs: PostureDiff[] = [
  { id: 1, current_scan_id: 4, previous_scan_id: 1, target_id: 1, new_findings_count: 2, resolved_findings_count: 1, unchanged_findings_count: 2, risk_score_delta: 1.1, posture_score_delta: -8, summary: 'Posture degraded slightly after new auth-surface exposure was discovered.', created_at: isoHoursAgo(4) },
  { id: 2, current_scan_id: 3, previous_scan_id: 2, target_id: 3, new_findings_count: 1, resolved_findings_count: 0, unchanged_findings_count: 1, risk_score_delta: 1.5, posture_score_delta: -3, summary: 'Posture weakened as public exposure surfaced during the deeper crawl.', created_at: isoDaysAgo(1) },
];

let demoReports: Report[] = [
  { id: 1, scan_id: 1, target_id: 1, title: 'Orion Commerce Portal - Executive Assessment', executive_summary: 'A standard safe scan identified browser hardening and session safety gaps.', html_content: '<h1>Orion Commerce Portal</h1><p>Executive summary for scan #1.</p>', created_at: isoDaysAgo(5) },
  { id: 2, scan_id: 3, target_id: 3, title: 'Atlas Marketing Site - Public Exposure Review', executive_summary: 'A full safe scan found a public source-control exposure that warrants immediate remediation.', html_content: '<h1>Atlas Marketing Site</h1><p>Executive summary for scan #3.</p>', created_at: isoDaysAgo(1) },
  { id: 3, scan_id: 4, target_id: 1, title: 'Orion Commerce Portal - Drift Report', executive_summary: 'The latest scan shows new auth-surface issues and a posture regression relative to the prior baseline.', html_content: '<h1>Orion Commerce Portal Drift</h1><p>Executive summary for scan #4.</p>', created_at: isoHoursAgo(4) },
];

let demoNotifications: Notification[] = [
  { id: 1, title: 'Scan #4 completed', message: 'Orion Commerce Portal completed with 4 findings and a lower posture score.', type: 'warning', entity_type: 'scan', entity_id: 4, is_read: false, created_at: isoHoursAgo(4) },
  { id: 2, title: 'Report generated', message: 'Drift report available for the latest Orion Commerce Portal scan.', type: 'success', entity_type: 'report', entity_id: 3, is_read: false, created_at: isoHoursAgo(4) },
  { id: 3, title: 'Public exposure detected', message: 'Atlas Marketing Site exposed .git metadata during the deep crawl.', type: 'danger', entity_type: 'finding', entity_id: 5, is_read: true, created_at: isoDaysAgo(1) },
  { id: 4, title: 'Profile updated', message: 'Demo analyst profile and branding were refreshed for the session.', type: 'info', entity_type: 'system', entity_id: null, is_read: true, created_at: isoHoursAgo(12) },
];

const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value));
const severityOrder = ['critical', 'high', 'medium', 'low', 'info'] as const;

function average(numbers: number[]) {
  if (numbers.length === 0) return 0;
  return numbers.reduce((sum, value) => sum + value, 0) / numbers.length;
}

function createDemoArtifacts(scan: Scan, target: Target, profile: string) {
  const templatesByProfile: Record<string, Array<Omit<Finding, 'id' | 'scan_id' | 'target_id' | 'created_at'>>> = {
    'Passive Scan': [
      { title: 'Missing HSTS', severity: 'medium', category: 'Transport Security', affected_url: target.base_url, description: 'The application does not send an HSTS header on the landing page.', evidence: 'Strict-Transport-Security header missing from the response.', impact: 'Browsers may continue using insecure transport after the first visit.', remediation: 'Enable HSTS across all public entry points.', confidence: 'high', risk_score: 5.0 },
      { title: 'Leaky referrer policy', severity: 'low', category: 'Browser Defenses', affected_url: `${target.base_url}/account`, description: 'The referrer policy may disclose internal URLs to third parties.', evidence: 'Referrer-Policy header missing.', impact: 'Sensitive routes can be exposed through outgoing requests.', remediation: 'Use a restrictive referrer policy.', confidence: 'medium', risk_score: 2.8 },
    ],
    'Standard Safe Scan': [
      { title: 'Missing Content Security Policy', severity: 'high', category: 'Browser Defenses', affected_url: `${target.base_url}/dashboard`, description: 'The dashboard lacks a content security policy header.', evidence: 'Content-Security-Policy header missing.', impact: 'Injected scripts are more likely to run if an XSS bug exists.', remediation: 'Add a restrictive CSP for script and frame sources.', confidence: 'high', risk_score: 7.2 },
      { title: 'Weak session cookie flags', severity: 'critical', category: 'Session Safety', affected_url: `${target.base_url}/login`, description: 'The session cookie is missing at least one hardening attribute.', evidence: 'Set-Cookie header observed without Secure and HttpOnly.', impact: 'Session theft and cross-site request abuse become easier.', remediation: 'Set Secure, HttpOnly, and SameSite on session cookies.', confidence: 'high', risk_score: 8.7 },
      { title: 'Missing frame protection', severity: 'low', category: 'Browser Defenses', affected_url: target.base_url, description: 'No frame-busting header was observed during the scan.', evidence: 'X-Frame-Options and frame-ancestors were absent.', impact: 'The site could be embedded in a hostile frame.', remediation: 'Add X-Frame-Options or frame-ancestors.', confidence: 'medium', risk_score: 3.3 },
    ],
    'Full Safe Scan': [
      { title: 'Wildcard CORS on sensitive endpoint', severity: 'high', category: 'Auth Surface', affected_url: `${target.base_url}/api/session`, description: 'The endpoint responds with a wildcard origin policy.', evidence: 'Access-Control-Allow-Origin: *', impact: 'Cross-origin callers may access sensitive responses.', remediation: 'Restrict CORS to explicit trusted origins.', confidence: 'high', risk_score: 7.0 },
      { title: 'Password field missing autocomplete protection', severity: 'medium', category: 'Auth Surface', affected_url: `${target.base_url}/login`, description: 'The login form password field is missing a defensive autocomplete setting.', evidence: 'autocomplete attribute not set for password input.', impact: 'Shared-device credential handling becomes less predictable.', remediation: 'Set autocomplete="current-password" and related attributes.', confidence: 'medium', risk_score: 4.4 },
      { title: 'Exposed .git directory', severity: 'high', category: 'Public Exposure', affected_url: `${target.base_url}/.git/`, description: 'Repository metadata was reachable from the public site.', evidence: 'Directory listing included .git objects.', impact: 'Source code and secrets may be recoverable.', remediation: 'Block VCS metadata at the web server or CDN edge.', confidence: 'high', risk_score: 8.1 },
      { title: 'Missing HSTS', severity: 'medium', category: 'Transport Security', affected_url: target.base_url, description: 'The application does not send an HSTS header.', evidence: 'Strict-Transport-Security header missing.', impact: 'Initial requests can still be downgraded by an active network attacker.', remediation: 'Enable HSTS on all production entry points.', confidence: 'high', risk_score: 5.2 },
      { title: 'Leaky referrer policy', severity: 'low', category: 'Browser Defenses', affected_url: `${target.base_url}/account`, description: 'A permissive referrer policy could leak internal navigation paths.', evidence: 'Referrer-Policy header missing.', impact: 'External integrations may receive more URL detail than intended.', remediation: 'Set a restrictive referrer policy.', confidence: 'medium', risk_score: 2.6 },
    ],
  };

  const templates = templatesByProfile[profile] || templatesByProfile['Standard Safe Scan'];
  const createdFindings = templates.map((template, index) => ({
    id: nextFindingId++,
    scan_id: scan.id,
    target_id: target.id,
    created_at: isoMinutesAgo(index * 2),
    ...template,
  }));

  const nodeCount = profile === 'Passive Scan' ? 2 : profile === 'Full Safe Scan' ? 6 : 4;
  const createdNodes: CrawlNode[] = Array.from({ length: nodeCount }, (_, index) => {
    const isLoginPage = index === 1 || index === nodeCount - 1;
    return {
      id: nextCrawlNodeId++,
      scan_id: scan.id,
      target_id: target.id,
      url: isLoginPage ? `${target.base_url}/login` : `${target.base_url}${index === 0 ? '/' : `/page-${index + 1}`}`,
      path: isLoginPage ? '/login' : index === 0 ? '/' : `/page-${index + 1}`,
      status_code: 200,
      content_type: 'text/html',
      page_title: isLoginPage ? 'Sign in' : `Page ${index + 1}`,
      depth: index === 0 ? 0 : 1,
      parent_url: index === 0 ? null : `${target.base_url}/`,
      has_forms: index !== 0,
      has_password_field: isLoginPage,
      finding_count: index === 0 ? 1 : index === 1 ? 2 : 0,
      created_at: isoMinutesAgo(index * 2),
    };
  });

  const createdEvidence = createdFindings.slice(0, Math.min(2, createdFindings.length)).map((finding, index) => ({
    id: nextEvidenceId++,
    scan_id: scan.id,
    target_id: target.id,
    artifact_type: index === 0 ? 'header_snapshot' : 'html_snippet',
    title: `${finding.title} evidence`,
    file_path: null,
    redacted_text: index === 0
      ? `Evidence for ${finding.title}\nObserved on ${finding.affected_url}`
      : `<form action="/login">\n  <input type="password" name="password">\n</form>`,
    related_url: finding.affected_url,
    created_at: isoMinutesAgo(index * 2),
  }));

  const previousScan = [...demoScans].filter(item => item.target_id === target.id && item.id !== scan.id).sort((a, b) => b.started_at.localeCompare(a.started_at))[0];
  if (previousScan) {
    const previousCount = demoFindings.filter(finding => finding.scan_id === previousScan.id).length;
    demoDiffs.unshift({
      id: nextDiffId++,
      current_scan_id: scan.id,
      previous_scan_id: previousScan.id,
      target_id: target.id,
      new_findings_count: Math.max(createdFindings.length - previousCount, 0),
      resolved_findings_count: Math.max(previousCount - createdFindings.length, 0),
      unchanged_findings_count: Math.min(previousCount, createdFindings.length),
      risk_score_delta: Number((scan.risk_score - previousScan.risk_score).toFixed(1)),
      posture_score_delta: scan.overall_posture_score - previousScan.overall_posture_score,
      summary: scan.overall_posture_score >= previousScan.overall_posture_score
        ? 'Posture improved compared with the previous baseline.'
        : 'Posture regressed compared with the previous baseline.',
      created_at: scan.started_at,
    });
  }

  const createdReport: Report = {
    id: nextReportId++,
    scan_id: scan.id,
    target_id: target.id,
    title: `${target.name} - Demo Assessment`,
    executive_summary: `Demo report generated for ${profile.toLowerCase()} on ${target.name}.`,
    html_content: `<h1>${target.name}</h1><p>Demo report for scan #${scan.id}.</p>`,
    created_at: scan.completed_at || scan.started_at,
  };

  demoFindings.unshift(...createdFindings);
  demoCrawlNodes.unshift(...createdNodes);
  demoEvidence.unshift(...createdEvidence);
  demoReports.unshift(createdReport);
  demoNotifications.unshift(
    { id: nextNotificationId++, title: `Scan #${scan.id} completed`, message: `${target.name} completed with ${createdFindings.length} findings using the ${profile} profile.`, type: createdFindings.length > 3 ? 'warning' : 'success', entity_type: 'scan', entity_id: scan.id, is_read: false, created_at: scan.completed_at || scan.started_at },
    { id: nextNotificationId++, title: 'Demo report ready', message: `${target.name} now has a generated report and drift summary.`, type: 'info', entity_type: 'report', entity_id: createdReport.id, is_read: false, created_at: scan.completed_at || scan.started_at },
  );

  return { findings: createdFindings, crawlNodes: createdNodes, evidence: createdEvidence, report: createdReport };
}

export function getPolicies() {
  return clone(demoPolicies);
}

export function getTargets() {
  return clone(demoTargets);
}

export function createTarget(target: { name: string; base_url: string; environment: string; authorization_confirmed: boolean }) {
  const parsedDomain = target.base_url.replace(/^https?:\/\//, '').replace(/\/.*/, '');
  const createdTarget: Target = {
    id: nextTargetId++,
    name: target.name,
    base_url: target.base_url,
    domain: parsedDomain,
    environment: target.environment,
    authorization_confirmed: true,
    created_at: new Date().toISOString(),
  };
  demoTargets.unshift(createdTarget);
  demoNotifications.unshift({ id: nextNotificationId++, title: 'Target added', message: `${createdTarget.name} was added to the demo inventory.`, type: 'success', entity_type: 'target', entity_id: createdTarget.id, is_read: false, created_at: createdTarget.created_at });
  return clone(createdTarget);
}

export function deleteTarget(targetId: number) {
  demoTargets = demoTargets.filter(target => target.id !== targetId);
  demoScans = demoScans.filter(scan => scan.target_id !== targetId);
  demoFindings = demoFindings.filter(finding => finding.target_id !== targetId);
  demoCrawlNodes = demoCrawlNodes.filter(node => node.target_id !== targetId);
  demoEvidence = demoEvidence.filter(item => item.target_id !== targetId);
  demoDiffs = demoDiffs.filter(diff => diff.target_id !== targetId);
  demoReports = demoReports.filter(report => report.target_id !== targetId);
  demoNotifications = demoNotifications.filter(notification => notification.entity_id !== targetId || notification.entity_type !== 'target');
}

export function listScans() {
  return clone([...demoScans].sort((a, b) => b.started_at.localeCompare(a.started_at)));
}

export function listFindings(scanId: number) {
  return clone(demoFindings.filter(finding => finding.scan_id === scanId));
}

export function listCrawlNodes(scanId: number) {
  return clone(demoCrawlNodes.filter(node => node.scan_id === scanId));
}

export function listEvidence(scanId: number) {
  return clone(demoEvidence.filter(item => item.scan_id === scanId));
}

export function listReports() {
  return clone([...demoReports].sort((a, b) => b.created_at.localeCompare(a.created_at)));
}

export function getReportHtml(reportId: number) {
  return demoReports.find(report => report.id === reportId)?.html_content || '';
}

export function getPolicyResults(scanId: number) {
  const findings = demoFindings.filter(finding => finding.scan_id === scanId);
  return demoPolicies.map(policy => ({
    policy_id: policy.policy_id,
    title: policy.title,
    checks: policy.checks.map(check => {
      const relatedTitles = (check.related_finding_titles || []).map(title => title.toLowerCase());
      const violatingFindings = findings.filter(finding => relatedTitles.some(title => finding.title.toLowerCase().includes(title)));
      return {
        check_id: check.id,
        title: check.title,
        status: violatingFindings.length > 0 ? 'failed' : 'passed',
        violating_findings: violatingFindings.map(finding => finding.title),
      };
    }),
  }));
}

export function getPostureDiff(scanId: number) {
  return clone(demoDiffs.find(diff => diff.current_scan_id === scanId) || null);
}

export function getNotifications(limit = 100) {
  return clone(demoNotifications.slice(0, limit));
}

export function markNotificationRead(notificationId: number) {
  demoNotifications = demoNotifications.map(notification => notification.id === notificationId ? { ...notification, is_read: true } : notification);
}

export function markAllNotificationsRead() {
  demoNotifications = demoNotifications.map(notification => ({ ...notification, is_read: true }));
}

export function deleteNotification(notificationId: number) {
  demoNotifications = demoNotifications.filter(notification => notification.id !== notificationId);
}

export function getUnreadNotificationCount() {
  return demoNotifications.filter(notification => !notification.is_read).length;
}

export function getProfile() {
  return clone(demoProfile);
}

export function updateProfile(update: Partial<UserProfile>) {
  demoProfile = { ...demoProfile, ...update, updated_at: new Date().toISOString() };
  return clone(demoProfile);
}

export function getSettings() {
  return clone(demoSettings);
}

export function updateSettings(update: Partial<AppSettings>) {
  demoSettings = { ...demoSettings, ...update, updated_at: new Date().toISOString() };
  return clone(demoSettings);
}

export function resetSettings() {
  demoSettings = {
    ...demoSettings,
    theme: 'dark',
    default_scan_profile: 'Standard Safe Scan',
    request_timeout_seconds: 10,
    max_pages_standard: 25,
    max_pages_full: 50,
    max_depth_standard: 2,
    max_depth_full: 3,
    rate_limit_delay_ms: 500,
    report_company_name: 'VulnScope Demo Lab',
    report_footer_text: 'Generated by VulnScope - Authorized Testing Only',
    auto_generate_report: true,
    updated_at: new Date().toISOString(),
  };
  return clone(demoSettings);
}

export function startDemoScan(targetId: number, profile: string) {
  const target = demoTargets.find(item => item.id === targetId);
  if (!target) {
    throw new Error('Target not found');
  }

  if (!target.authorization_confirmed) {
    throw new Error('Target authorization not confirmed');
  }

  const profileConfig = profile === 'Passive Scan'
    ? { findings: 2, risk: 3.6, posture: 86 }
    : profile === 'Full Safe Scan'
      ? { findings: 5, risk: 6.8, posture: 65 }
      : { findings: 3, risk: 5.4, posture: 74 };

  const scan: Scan = {
    id: nextScanId++,
    target_id: target.id,
    profile,
    status: 'completed',
    started_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    total_findings: profileConfig.findings,
    risk_score: profileConfig.risk,
    overall_posture_score: profileConfig.posture,
    posture_transport_security: profile === 'Passive Scan' ? 88 : profile === 'Full Safe Scan' ? 71 : 79,
    posture_browser_defense: profile === 'Passive Scan' ? 90 : profile === 'Full Safe Scan' ? 66 : 76,
    posture_session_safety: profile === 'Passive Scan' ? 87 : profile === 'Full Safe Scan' ? 68 : 75,
    posture_exposure_hygiene: profile === 'Passive Scan' ? 85 : profile === 'Full Safe Scan' ? 62 : 72,
    posture_authentication_surface: profile === 'Passive Scan' ? 84 : profile === 'Full Safe Scan' ? 64 : 70,
    error_message: null,
  };

  demoScans.unshift(scan);
  createDemoArtifacts(scan, target, profile);
  return clone(scan);
}

export function getDashboardSummary(): DashboardSummary {
  const severityDistribution = severityOrder.reduce<Record<string, number>>((accumulator, severity) => {
    accumulator[severity] = demoFindings.filter(finding => finding.severity === severity).length;
    return accumulator;
  }, {});

  const riskByTarget = demoTargets.map(target => ({
    target,
    averageRisk: average(demoScans.filter(scan => scan.target_id === target.id).map(scan => scan.risk_score)),
  })).sort((a, b) => b.averageRisk - a.averageRisk);

  return {
    total_targets: demoTargets.length,
    total_scans: demoScans.length,
    total_findings: demoFindings.length,
    active_scans: demoScans.filter(scan => scan.status === 'queued' || scan.status === 'running').length,
    critical_findings: demoFindings.filter(finding => finding.severity === 'critical').length,
    high_findings: demoFindings.filter(finding => finding.severity === 'high').length,
    overall_risk_score: Number(average(demoScans.map(scan => scan.risk_score)).toFixed(1)),
    overall_posture_score: Math.round(average(demoScans.map(scan => scan.overall_posture_score))),
    severity_distribution: severityDistribution,
    recent_scans: clone([...demoScans].sort((a, b) => b.started_at.localeCompare(a.started_at)).slice(0, 5)),
    highest_risk_targets: clone(riskByTarget.slice(0, 3).map(entry => entry.target)),
  };
}

export function searchDemo(query: string): SearchResults {
  const normalized = query.toLowerCase();
  const matches = <T extends Record<string, any>>(items: T[], predicate: (item: T) => boolean) => items.filter(predicate);

  const targets = matches(demoTargets, item => [item.name, item.base_url, item.domain, item.environment].some(field => field.toLowerCase().includes(normalized)));
  const scans = matches(demoScans, item => [item.profile, item.status, `scan ${item.id}`, item.target_id.toString()].some(field => field.toLowerCase().includes(normalized)));
  const findings = matches(demoFindings, item => [item.title, item.category, item.affected_url, item.description].some(field => field.toLowerCase().includes(normalized)));
  const reports = matches(demoReports, item => [item.title, item.executive_summary, item.html_content].some(field => field.toLowerCase().includes(normalized)));

  return clone({ targets, scans, findings, reports });
}
