from datetime import datetime,timezone
from sqlalchemy import Boolean,Column,DateTime,Float,ForeignKey,Integer,String,Text,UniqueConstraint,Index
from sqlalchemy.orm import relationship
from app.database import Base
def utcnow():return datetime.now(timezone.utc)
class UnifiedEntity(Base):
 __tablename__="unified_entities";id=Column(Integer,primary_key=True);entity_type=Column(String(30),nullable=False,index=True);normalized_value=Column(String(2000),nullable=False);value_hash=Column(String(64),nullable=False,index=True);display_value_redacted=Column(String(2000),nullable=False);risk_score=Column(Float,default=0,index=True);severity=Column(String(16),default="info",index=True);confidence=Column(String(16),default="low");observation_count=Column(Integer,default=0);source_module_count=Column(Integer,default=0);first_seen_at=Column(DateTime,default=utcnow);last_seen_at=Column(DateTime,default=utcnow,index=True);watchlist_match=Column(Boolean,default=False);active=Column(Boolean,default=True,index=True);created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow);observations=relationship("EntityObservation",back_populates="entity",cascade="all, delete-orphan");__table_args__=(UniqueConstraint("entity_type","normalized_value",name="uq_unified_entity"),)
class EntityObservation(Base):
 __tablename__="entity_observations";id=Column(Integer,primary_key=True);entity_id=Column(Integer,ForeignKey("unified_entities.id",ondelete="CASCADE"),index=True);source_module=Column(String(30),nullable=False,index=True);source_record_type=Column(String(50),nullable=False);source_record_id=Column(Integer,nullable=False);source_internal_route=Column(String(500));title_snapshot=Column(String(500),nullable=False);evidence_snapshot=Column(Text,nullable=False);severity=Column(String(16),nullable=False);confidence=Column(String(16),nullable=False);observed_at=Column(DateTime,default=utcnow);observation_fingerprint=Column(String(64),unique=True,index=True);created_at=Column(DateTime,default=utcnow);entity=relationship("UnifiedEntity",back_populates="observations")
class CorrelationRule(Base):
 __tablename__="correlation_rules";id=Column(Integer,primary_key=True);code=Column(String(20),unique=True,index=True);title=Column(String(240));description=Column(Text);enabled=Column(Boolean,default=True);default_rule=Column(Boolean,default=True);severity=Column(String(16));confidence=Column(String(16));minimum_sources=Column(Integer,default=2);time_window_hours=Column(Integer);configuration_json=Column(Text,default="{}");created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow)
class CorrelationMatch(Base):
 __tablename__="correlation_matches";id=Column(Integer,primary_key=True);rule_code=Column(String(20),index=True);primary_entity_id=Column(Integer,ForeignKey("unified_entities.id"),index=True);match_key=Column(String(200));title=Column(String(240));explanation=Column(Text);source_modules_json=Column(Text);related_entity_ids_json=Column(Text,default="[]");observation_ids_json=Column(Text);match_score=Column(Float,index=True);severity=Column(String(16),index=True);confidence=Column(String(16));status=Column(String(24),default="new",index=True);analyst_notes=Column(Text);fingerprint=Column(String(64),unique=True,index=True);first_detected_at=Column(DateTime,default=utcnow);last_detected_at=Column(DateTime,default=utcnow);created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow)
class IncidentCase(Base):
 __tablename__="incident_cases";id=Column(Integer,primary_key=True);case_key=Column(String(40),unique=True,index=True);title=Column(String(240));summary=Column(Text);case_type=Column(String(40));severity=Column(String(16),index=True);priority=Column(String(5),index=True);confidence=Column(String(16));risk_score=Column(Float,index=True);status=Column(String(30),default="new",index=True);source_module_count=Column(Integer,default=0);evidence_count=Column(Integer,default=0);primary_entity_id=Column(Integer,ForeignKey("unified_entities.id"));assignee_name=Column(String(200));tags_json=Column(Text,default="[]");resolution_summary=Column(Text);created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow);closed_at=Column(DateTime);evidence=relationship("IncidentEvidence",cascade="all, delete-orphan");timeline=relationship("IncidentTimelineEvent",cascade="all, delete-orphan");notes=relationship("IncidentNote",cascade="all, delete-orphan");actions=relationship("IncidentActionItem",cascade="all, delete-orphan");reports=relationship("IncidentReport",cascade="all, delete-orphan")
class IncidentEvidence(Base):
 __tablename__="incident_evidence";id=Column(Integer,primary_key=True);case_id=Column(Integer,ForeignKey("incident_cases.id",ondelete="CASCADE"),index=True);source_module=Column(String(30));source_record_type=Column(String(50));source_record_id=Column(Integer);source_internal_route=Column(String(500));title_snapshot=Column(String(500));evidence_snapshot=Column(Text);severity=Column(String(16));confidence=Column(String(16));entity_id=Column(Integer,ForeignKey("unified_entities.id"));correlation_match_id=Column(Integer,ForeignKey("correlation_matches.id"));evidence_fingerprint=Column(String(64),unique=True,index=True);added_at=Column(DateTime,default=utcnow)
class IncidentTimelineEvent(Base):
 __tablename__="incident_timeline";id=Column(Integer,primary_key=True);case_id=Column(Integer,ForeignKey("incident_cases.id",ondelete="CASCADE"),index=True);event_type=Column(String(40));summary=Column(Text);old_value=Column(Text);new_value=Column(Text);actor_label=Column(String(100),default="Local analyst");created_at=Column(DateTime,default=utcnow)
class IncidentNote(Base):
 __tablename__="incident_notes";id=Column(Integer,primary_key=True);case_id=Column(Integer,ForeignKey("incident_cases.id",ondelete="CASCADE"),index=True);note_text=Column(Text);author_label=Column(String(100));created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow)
class IncidentActionItem(Base):
 __tablename__="incident_actions";id=Column(Integer,primary_key=True);case_id=Column(Integer,ForeignKey("incident_cases.id",ondelete="CASCADE"),index=True);title=Column(String(240));description=Column(Text);status=Column(String(20),default="open");priority=Column(String(16),default="medium");assignee_name=Column(String(200));due_at=Column(DateTime);created_at=Column(DateTime,default=utcnow);updated_at=Column(DateTime,default=utcnow,onupdate=utcnow);completed_at=Column(DateTime)
class IncidentReport(Base):
 __tablename__="incident_reports";id=Column(Integer,primary_key=True);case_id=Column(Integer,ForeignKey("incident_cases.id",ondelete="CASCADE"),index=True);title=Column(String(240));html_content=Column(Text);summary_json=Column(Text);created_at=Column(DateTime,default=utcnow)
