from sqlalchemy import Column, Integer, String, Boolean, Float, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.database import Base

def utcnow():
    return datetime.now(timezone.utc)

class Target(Base):
    __tablename__ = "targets"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    base_url = Column(String)
    domain = Column(String)
    authorization_confirmed = Column(Boolean, default=False)
    environment = Column(String)
    created_at = Column(DateTime, default=utcnow)

    scans = relationship("Scan", back_populates="target", cascade="all, delete-orphan")
    findings = relationship("Finding", back_populates="target", cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="target", cascade="all, delete-orphan")


class Scan(Base):
    __tablename__ = "scans"
    id = Column(Integer, primary_key=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id"))
    profile = Column(String) # Passive Scan, Standard Safe Scan, Full Safe Scan
    status = Column(String) # queued, running, completed, failed
    started_at = Column(DateTime, default=utcnow)
    completed_at = Column(DateTime, nullable=True)
    total_findings = Column(Integer, default=0)
    risk_score = Column(Float, default=0.0)
    error_message = Column(Text, nullable=True)

    target = relationship("Target", back_populates="scans")
    findings = relationship("Finding", back_populates="scan", cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="scan", cascade="all, delete-orphan")


class Finding(Base):
    __tablename__ = "findings"
    id = Column(Integer, primary_key=True, index=True)
    scan_id = Column(Integer, ForeignKey("scans.id"))
    target_id = Column(Integer, ForeignKey("targets.id"))
    title = Column(String)
    severity = Column(String) # info, low, medium, high, critical
    category = Column(String)
    affected_url = Column(String)
    description = Column(Text)
    evidence = Column(Text)
    impact = Column(Text)
    remediation = Column(Text)
    confidence = Column(String)
    risk_score = Column(Float, default=0.0)
    created_at = Column(DateTime, default=utcnow)

    scan = relationship("Scan", back_populates="findings")
    target = relationship("Target", back_populates="findings")


class Report(Base):
    __tablename__ = "reports"
    id = Column(Integer, primary_key=True, index=True)
    scan_id = Column(Integer, ForeignKey("scans.id"))
    target_id = Column(Integer, ForeignKey("targets.id"))
    title = Column(String)
    executive_summary = Column(Text)
    html_content = Column(Text)
    created_at = Column(DateTime, default=utcnow)

    scan = relationship("Scan", back_populates="reports")
    target = relationship("Target", back_populates="reports")

class Notification(Base):
    __tablename__ = "notifications"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    message = Column(Text)
    type = Column(String) # info, success, warning, danger
    entity_type = Column(String) # target, scan, finding, report, system
    entity_id = Column(Integer, nullable=True)
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=utcnow)

class UserProfile(Base):
    __tablename__ = "user_profiles"
    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String)
    email = Column(String)
    organization = Column(String)
    role = Column(String)
    avatar_initials = Column(String)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

class AppSettings(Base):
    __tablename__ = "app_settings"
    id = Column(Integer, primary_key=True, index=True)
    theme = Column(String, default="dark") # dark, light, system
    default_scan_profile = Column(String, default="Standard Safe Scan")
    request_timeout_seconds = Column(Integer, default=10)
    max_pages_standard = Column(Integer, default=25)
    max_pages_full = Column(Integer, default=50)
    max_depth_standard = Column(Integer, default=2)
    max_depth_full = Column(Integer, default=3)
    rate_limit_delay_ms = Column(Integer, default=500)
    report_company_name = Column(String, default="VulnScope Demo Lab")
    report_footer_text = Column(String, default="Generated by VulnScope - Authorized Testing Only")
    auto_generate_report = Column(Boolean, default=False)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)
