import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertTriangle, Archive, CheckCircle2, Database, Download, Play, RefreshCw, ShieldCheck } from 'lucide-react';
import { apiClient } from '../../api/client';
import { useAuth } from '../../auth/useAuth';

type Data = Record<string, unknown>;
const text = (value: unknown) => value == null ? '—' : typeof value === 'object' ? JSON.stringify(value) : String(value);
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString() : '—';
const bytes = (value: unknown) => `${(Number(value || 0) / 1024).toFixed(1)} KiB`;

function useEndpoint(path: string) {
  const [data, setData] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const refresh = useCallback(async () => { setLoading(true); setError(''); try { setData((await apiClient.get(path)).data); } catch (err) { setError(err instanceof Error ? err.message : 'Request failed'); } finally { setLoading(false); } }, [path]);
  useEffect(() => { void refresh(); }, [refresh]); return { data, loading, error, refresh, setData };
}

function Page({ title, description, children, loading, error, refresh }: { title: string; description: string; children: ReactNode; loading?: boolean; error?: string; refresh?: () => void }) {
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{refresh && <button onClick={refresh} className="rounded border border-border p-2" aria-label={`Refresh ${title}`}><RefreshCw className="h-4 w-4" /></button>}</div>{loading ? <div className="rounded-lg border border-border p-8 text-muted-foreground">Loading operational data…</div> : error ? <div role="alert" className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-200">{error}</div> : children}</div>;
}
function Card({ title, value, children }: { title: string; value?: unknown; children?: ReactNode }) { return <section className="min-w-0 rounded-lg border border-border bg-card p-4"><h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{title}</h2>{value !== undefined && <div className="mt-2 break-words text-xl font-semibold">{text(value)}</div>}{children}</section>; }
function Action({ children, onClick, disabled }: { children: ReactNode; onClick: () => void; disabled?: boolean }) { return <button disabled={disabled} onClick={onClick} className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{children}</button>; }

export function HealthStatusBadge({ status }: { status: unknown }) { const value=String(status||'unknown'); const tone=value==='healthy'||value==='ready'||value==='valid'?'bg-emerald-500/15 text-emerald-300':value==='unhealthy'||value==='invalid'?'bg-red-500/15 text-red-300':'bg-amber-500/15 text-amber-200'; return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-medium ${tone}`}>{value}</span>; }
export function JobStatusBadge({ status }: { status: unknown }) { return <HealthStatusBadge status={status} />; }
export function BackupIntegrityBadge({ status }: { status: unknown }) { return <HealthStatusBadge status={status} />; }
export function ChecksumDisplay({ value }: { value: unknown }) { return <code className="block max-w-full break-all rounded bg-muted px-2 py-1 text-xs">{text(value)}</code>; }
export function JobProgress({ value }: { value: unknown }) { const amount=Math.max(0,Math.min(100,Number(value||0))); return <div className="h-2 overflow-hidden rounded bg-muted" aria-label={`${amount}% complete`}><div className="h-full bg-primary" style={{width:`${amount}%`}} /></div>; }
export function DiagnosticCard({ title, value }: { title: string; value: unknown }) { return <Card title={title}><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs text-muted-foreground">{JSON.stringify(value,null,2)}</pre></Card>; }
export function ConfigurationIssueCard({ issue }: { issue: Data }) { return <Card title={text(issue.setting)}><div className="mt-2"><HealthStatusBadge status={issue.status} /></div><p className="mt-3 text-sm">{text(issue.summary)}</p><p className="mt-2 text-xs text-muted-foreground">{text(issue.recommended_action)}</p></Card>; }
export function HealthCheckTable({ checks }: { checks: Data[] }) { return <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[720px] text-sm"><thead className="bg-muted/40 text-left"><tr><th className="p-3">Check</th><th>Category</th><th>Status</th><th>Summary</th><th>Duration</th></tr></thead><tbody>{checks.map((item,index)=><tr key={text(item.check_key)||index} className="border-t border-border"><td className="p-3 font-medium">{text(item.check_key)}</td><td>{text(item.category)}</td><td><HealthStatusBadge status={item.status}/></td><td className="max-w-lg py-3 pr-3">{text(item.summary)}</td><td>{text(item.duration_ms)} ms</td></tr>)}</tbody></table></div>; }
export function BackupTable({ items }: { items: Data[] }) { return <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/40 text-left"><tr><th className="p-3">Backup</th><th>Created</th><th>Size</th><th>Encrypted</th><th>Integrity</th></tr></thead><tbody>{items.map(item=><tr key={text(item.id)} className="border-t border-border"><td className="p-3"><Link className="text-primary hover:underline" to={`/operations/backups/${item.id}`}>{text(item.backup_key)}</Link></td><td>{date(item.created_at)}</td><td>{bytes(item.size_bytes)}</td><td>{text(item.encrypted)}</td><td><BackupIntegrityBadge status={item.verification_status}/></td></tr>)}</tbody></table></div>; }
export function ExportPackageTable({ items }: { items: Data[] }) { return <div className="space-y-2">{items.map(item=><Link key={text(item.id)} to={`/operations/exports/${item.id}`} className="block rounded border border-border p-3 hover:bg-muted/30"><b>{text(item.package_key)}</b><span className="ml-3 text-xs text-muted-foreground">{date(item.created_at)} · {bytes(item.size_bytes)}</span></Link>)}</div>; }
export function RetentionPreviewTable({ run }: { run: Data | null }) { return run ? <Card title="Latest preview"><div className="mt-3 grid gap-2 text-sm"><div>Candidates: {text(run.candidate_count)}</div><div>Preserved: {text(run.preserved_count)}</div><JobStatusBadge status={run.status}/></div></Card> : <div className="text-sm text-muted-foreground">No retention preview has been run.</div>; }
export function InventoryTable({ items }: { items: Data[] }) { return <div className="max-h-[36rem] overflow-auto rounded border border-border"><table className="w-full min-w-[680px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Component</th><th>Version</th><th>Ecosystem</th><th>Classification</th></tr></thead><tbody>{items.map((item,index)=><tr key={`${item.ecosystem}-${item.name}-${index}`} className="border-t"><td className="p-3">{text(item.name)}</td><td>{text(item.version)}</td><td>{text(item.ecosystem)}</td><td>{text(item.classification)}</td></tr>)}</tbody></table></div>; }
export function ReleaseArtifactTable({ items }: { items: Data[] }) { return <div className="space-y-2">{items.map(item=><Link key={text(item.id)} to={`/operations/releases/${item.id}`} className="block rounded border border-border p-3 hover:bg-muted/30"><b>{text(item.release_key)}</b><span className="ml-3 text-xs text-muted-foreground">{text(item.version)} · {bytes(item.size_bytes)}</span></Link>)}</div>; }
export function DemoModeBanner() { return <div className="flex items-center gap-2 rounded-lg border border-amber-400/40 bg-amber-400/10 p-3 text-sm text-amber-100"><AlertTriangle className="h-4 w-4"/>Demo Environment — all seeded records are synthetic and local-only.</div>; }
export function RestoreValidationPanel({ restore }: { restore: Data }) { return <Card title="Validation"><div className="mt-3"><HealthStatusBadge status={restore.status}/></div><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(restore.validation_summary,null,2)}</pre></Card>; }
export function RestoreConfirmationDialog({ onConfirm, busy }: { onConfirm: (password:string, phrase:string, mfa:string)=>void; busy:boolean }) { const [password,setPassword]=useState('');const [phrase,setPhrase]=useState('');const [mfa,setMfa]=useState('');return <Card title="Stage controlled restore"><div className="mt-3 space-y-3"><p className="text-sm text-amber-200">A protected pre-restore backup is created. All sessions are revoked only after offline replacement succeeds.</p><input type="password" aria-label="Current password" placeholder="Current password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded border bg-background p-2"/><input aria-label="MFA code" placeholder="MFA code when enabled" value={mfa} onChange={e=>setMfa(e.target.value)} className="w-full rounded border bg-background p-2"/><input aria-label="Restore confirmation phrase" placeholder="Type RESTORE THREATSCOPE DATA" value={phrase} onChange={e=>setPhrase(e.target.value)} className="w-full rounded border bg-background p-2"/><Action disabled={busy||phrase!=='RESTORE THREATSCOPE DATA'||!password} onClick={()=>onConfirm(password,phrase,mfa)}><Play className="h-4 w-4"/>Stage restore</Action></div></Card>; }

export function OperationsOverviewPage(){const q=useEndpoint('/operations');const d=(q.data||{}) as Data;return <Page title="Operations" description="Local health, recovery, retention, demo, inventory, and release readiness." loading={q.loading} error={q.error} refresh={q.refresh}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="Readiness" value={(d.readiness as Data)?.status}/><Card title="Version" value={(d.version as Data)?.version}/><Card title="Failed jobs" value={d.recent_failed_jobs}/><Card title="Pending restores" value={d.pending_restore_count}/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Health','/operations/health'],['Backups','/operations/backups'],['Exports','/operations/exports'],['Releases','/operations/releases']].map(([n,p])=><Link key={p} to={p} className="rounded border border-border p-4 hover:bg-muted/30">{n}</Link>)}</div></Page>}
export function HealthPage(){const q=useEndpoint('/operations/health/details');const d=(q.data||{}) as Data;return <Page title="Health" description="Authenticated detailed checks with safe metadata only." loading={q.loading} error={q.error} refresh={q.refresh}><HealthCheckTable checks={(d.checks||[]) as Data[]}/></Page>}
export function DiagnosticsPage(){const q=useEndpoint('/operations/diagnostics');return <Page title="Diagnostics" description="Bounded aggregate runtime diagnostics; no credentials, environment values, or full paths." loading={q.loading} error={q.error} refresh={q.refresh}><div className="grid gap-4 lg:grid-cols-2">{Object.entries((q.data||{}) as Data).map(([k,v])=><DiagnosticCard key={k} title={k} value={v}/>)}</div></Page>}
export function ConfigurationStatusPage(){const q=useEndpoint('/operations/configuration/status');const d=(q.data||{}) as Data;const validate=async()=>{await apiClient.post('/operations/configuration/validate');await q.refresh()};return <Page title="Configuration" description="Read-only security configuration validation; setting values are never returned." loading={q.loading} error={q.error} refresh={q.refresh}><div className="mb-4"><Action onClick={validate}><ShieldCheck className="h-4 w-4"/>Validate configuration</Action></div><div className="grid gap-4 lg:grid-cols-2">{((d.settings||[]) as Data[]).map((x,i)=><ConfigurationIssueCard key={`${x.setting}-${i}`} issue={x}/>)}</div></Page>}
export function JobsPage(){const q=useEndpoint('/operations/jobs');return <Page title="Operational jobs" description="Bounded history for maintenance and artifact operations." loading={q.loading} error={q.error} refresh={q.refresh}><div className="space-y-2">{((q.data||[]) as Data[]).map(x=><Link key={text(x.id)} to={`/operations/jobs/${x.id}`} className="block rounded border p-3"><JobStatusBadge status={x.status}/> <b className="ml-2">{text(x.job_type)}</b><JobProgress value={x.progress_percent}/></Link>)}</div></Page>}
export function JobDetailsPage(){const {jobId}=useParams();const q=useEndpoint(`/operations/jobs/${jobId}`);const d=(q.data||{}) as Data;return <Page title={`Job ${text(d.job_key)}`} description="Operational job progress and safe result metadata." loading={q.loading} error={q.error} refresh={q.refresh}><JobStatusBadge status={d.status}/><div className="mt-4"><JobProgress value={d.progress_percent}/></div><DiagnosticCard title="Result" value={d}/></Page>}
export function BackupsPage(){const {can}=useAuth();const q=useEndpoint('/operations/backups');const create=async()=>{await apiClient.post('/operations/backups/database',{backup_type:'database'});await q.refresh()};return <Page title="Database backups" description="Sensitive administrative recovery artifacts. Store securely; production requires encryption." loading={q.loading} error={q.error} refresh={q.refresh}>{can('operations:backup')&&<div className="mb-4"><Action onClick={create}><Database className="h-4 w-4"/>Create backup</Action></div>}<BackupTable items={(q.data||[]) as Data[]}/></Page>}
export function BackupDetailsPage(){const {backupId}=useParams();const q=useEndpoint(`/operations/backups/${backupId}`);const d=(q.data||{}) as Data;const verify=async()=>{await apiClient.post(`/operations/backups/${backupId}/verify`);await q.refresh()};const download=async()=>{const r=await apiClient.get(`/operations/backups/${backupId}/download`,{responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download=text(d.filename);a.click();URL.revokeObjectURL(u)};return <Page title={`Backup ${text(d.backup_key)}`} description="Managed local backup details; local filesystem paths are never exposed." loading={q.loading} error={q.error} refresh={q.refresh}><div className="flex flex-wrap gap-2"><Action onClick={verify}><CheckCircle2 className="h-4 w-4"/>Verify</Action><Action onClick={download}><Download className="h-4 w-4"/>Authorized download</Action></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><DiagnosticCard title="Metadata" value={d}/><Card title="Checksum"><div className="mt-3"><ChecksumDisplay value={d.sha256}/></div></Card></div></Page>}
export function RestoresPage(){const b=useEndpoint('/operations/backups');const r=useEndpoint('/operations/restores');const validate=async(id:unknown)=>{await apiClient.post('/operations/restores/validate',{backup_id:id});await r.refresh()};return <Page title="Restore validation" description="Validation is non-mutating. Execution is staged for a controlled service-stop replacement." loading={b.loading||r.loading} error={b.error||r.error} refresh={()=>{void b.refresh();void r.refresh()}}><div className="space-y-2">{((b.data||[]) as Data[]).map(x=><div key={text(x.id)} className="flex items-center justify-between rounded border p-3"><span>{text(x.backup_key)}</span><Action onClick={()=>validate(x.id)}>Validate</Action></div>)}</div><div className="mt-6 space-y-2">{((r.data||[]) as Data[]).map(x=><Link key={text(x.id)} to={`/operations/restores/${x.id}`} className="block rounded border p-3">{text(x.restore_key)} · <HealthStatusBadge status={x.status}/></Link>)}</div></Page>}
export function RestoreDetailsPage(){const {restoreId}=useParams();const q=useEndpoint(`/operations/restores/${restoreId}`);const [busy,setBusy]=useState(false);const execute=async(password:string,phrase:string,mfa:string)=>{setBusy(true);try{await apiClient.post(`/operations/restores/${restoreId}/execute`,{current_password:password,confirmation_phrase:phrase,mfa_code:mfa||null});await q.refresh()}finally{setBusy(false)}};const d=(q.data||{}) as Data;return <Page title={`Restore ${text(d.restore_key)}`} description="Validated restore details and explicit staged execution." loading={q.loading} error={q.error} refresh={q.refresh}><RestoreValidationPanel restore={d}/>{d.status==='validated'&&<div className="mt-4"><RestoreConfirmationDialog onConfirm={execute} busy={busy}/></div>}</Page>}
export function ExportsPage(){const q=useEndpoint('/operations/exports');const {can}=useAuth();const choices=[['web_exposure','Web Exposure','web:read'],['api_security','API Security','api:read'],['soc_summaries','SOC summaries','soc:read'],['document_threat_summaries','Document Threat summaries','document:read'],['phishing_summaries','Phishing summaries','phishing:read'],['correlation','Correlation','correlation:read'],['incident_cases','Incident Cases','cases:read'],['governance','Governance','governance:read'],['reports_metadata','Reports metadata','reports:read_all'],['security_audit_metadata','Security Audit metadata','audit:read']].filter(([, , permission])=>can(permission));const [selected,setSelected]=useState<string[]>(()=>choices.map(([key])=>key));const create=async()=>{await apiClient.post('/operations/exports',{modules:selected});await q.refresh()};return <Page title="Safe exports" description="Analyst-readable JSON summaries; authentication data and original files are excluded." loading={q.loading} error={q.error} refresh={q.refresh}><fieldset className="mb-4 rounded border border-border p-4"><legend className="px-2 text-sm font-medium">Readable modules</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{choices.map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(key)} onChange={event=>setSelected(current=>event.target.checked?[...current,key]:current.filter(x=>x!==key))}/>{label}</label>)}</div><div className="mt-4"><Action disabled={!selected.length} onClick={create}><Archive className="h-4 w-4"/>Create readable export</Action></div></fieldset><ExportPackageTable items={(q.data||[]) as Data[]}/></Page>}
export function ExportDetailsPage(){const {exportId}=useParams();const q=useEndpoint(`/operations/exports/${exportId}`);const d=(q.data||{}) as Data;const verify=async()=>{await apiClient.post(`/operations/exports/${exportId}/verify`);await q.refresh()};return <Page title={`Export ${text(d.package_key)}`} description="Verified local export package metadata." loading={q.loading} error={q.error} refresh={q.refresh}><Action onClick={verify}>Verify package</Action><div className="mt-4"><DiagnosticCard title="Export" value={d}/></div></Page>}
export function RetentionPage(){const p=useEndpoint('/operations/retention/policies');const [run,setRun]=useState<Data|null>(null);const preview=async(id:unknown)=>setRun((await apiClient.post('/operations/retention/preview',{policy_id:id})).data);const apply=async()=>{if(!run)return;await apiClient.post('/operations/retention/apply',{run_id:run.id,confirmation_phrase:'APPLY RETENTION PREVIEW'});setRun(null);await p.refresh()};return <Page title="Data retention" description="Dry-run first. Apply removes only the exact, unexpired preview set; audit events are never candidates." loading={p.loading} error={p.error} refresh={p.refresh}><RetentionPreviewTable run={run}/><div className="mt-4 space-y-2">{((p.data||[]) as Data[]).map(x=><div key={text(x.id)} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><span><b>{text(x.name)}</b><small className="ml-2 text-muted-foreground">{text(x.retention_days)} days · keep {text(x.minimum_keep_count)}</small></span><Action onClick={()=>preview(x.id)}>Preview</Action></div>)}</div>{run&&<div className="mt-4"><Action onClick={apply}>Apply exact preview</Action></div>}</Page>}
export function DemoEnvironmentPage(){const q=useEndpoint('/operations/demo/status');const seed=async()=>{await apiClient.post('/operations/demo/seed');await q.refresh()};const reset=async()=>{if(window.confirm('Reset only deterministic demo-owned records?')){await apiClient.post('/operations/demo/reset',{confirmation_phrase:'RESET DEMO DATA'});await q.refresh()}};const d=(q.data||{}) as Data;return <Page title="Demo environment" description="Explicit, deterministic synthetic data management; authentication and RBAC remain enforced." loading={q.loading} error={q.error} refresh={q.refresh}><DemoModeBanner/><div className="mt-4 flex gap-2"><Action onClick={seed}>Seed</Action><Action onClick={reset}>Reset demo-owned data</Action></div><div className="mt-4"><DiagnosticCard title="Demo status" value={d}/></div></Page>}
export function SoftwareInventoryPage(){const q=useEndpoint('/operations/inventory');const generate=async()=>{await apiClient.post('/operations/inventory/generate');await q.refresh()};const d=(q.data||{}) as Data;return <Page title="Software inventory" description="Locally generated from manifests and installed metadata; not a vulnerability assessment." loading={q.loading} error={q.error} refresh={q.refresh}><div className="mb-4"><Action onClick={generate}>Generate inventory</Action></div><InventoryTable items={(d.components||[]) as Data[]}/></Page>}
export function ReleasesPage(){const q=useEndpoint('/operations/releases');const build=async()=>{await apiClient.post('/operations/releases/build',{allow_dirty:true});await q.refresh()};return <Page title="Release candidates" description="Bounded local candidate bundles; no publishing, tagging, deployment, or certification claim." loading={q.loading} error={q.error} refresh={q.refresh}><div className="mb-4"><Action onClick={build}>Build marked local candidate</Action></div><ReleaseArtifactTable items={(q.data||[]) as Data[]}/></Page>}
export function ReleaseDetailsPage(){const {releaseId}=useParams();const q=useEndpoint(`/operations/releases/${releaseId}`);const d=(q.data||{}) as Data;return <Page title={`Release ${text(d.release_key)}`} description="Release-candidate checksum and deterministic metadata." loading={q.loading} error={q.error} refresh={q.refresh}><DiagnosticCard title="Release metadata" value={d}/><Card title="SHA-256"><div className="mt-3"><ChecksumDisplay value={d.sha256}/></div></Card></Page>}
