import { useEffect, useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { Shield } from 'lucide-react';
import { accessApi, type AuthProviderConfig, type SafeAccount } from '../../api/access';
import { PasswordField } from './components/PasswordField';
import { AuthPrivacyNotice } from './components/AuthPrivacyNotice';
import { useAuth } from '../../auth/useAuth';

export function LoginPage(){
  const {user,login}=useAuth();const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [providers,setProviders]=useState<AuthProviderConfig|null>(null);const navigate=useNavigate();const location=useLocation();
  useEffect(()=>{void accessApi.providers().then(setProviders).catch(()=>setError('Local sign-in configuration could not be loaded.'));},[]);
  if(user)return <Navigate to={user.must_change_password?'/change-password':'/dashboard'} replace/>;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(loading)return;setLoading(true);setError('');try{const result=await login(identifier,password);const destination=(location.state as {from?:string}|null)?.from||'/dashboard';if(result.account_status&&result.next_route){navigate(result.next_route,{replace:true,state:{account:result.account as SafeAccount}});return;}if(result.requires_mfa&&result.challenge_token)navigate('/mfa-challenge',{replace:true,state:{challengeToken:result.challenge_token,from:destination}});else navigate(destination,{replace:true});}catch{setError('Sign-in failed. Check your credentials or try again later.');}finally{setLoading(false);}};
  return <main className="grid min-h-screen place-items-center bg-background p-5"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-xl border border-border bg-card p-7 shadow-2xl"><div><Shield className="h-9 w-9 text-primary"/><h1 className="mt-4 text-2xl font-semibold">Sign in to ThreatScope XDR</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Use your email address or username and the password created specifically for ThreatScope XDR.</p></div>{error&&<p role="alert" className="rounded-md bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<label className="block text-sm font-medium">Email or username<input autoFocus autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)} required maxLength={254} className="mt-2 block w-full rounded-md border border-input bg-background px-3 py-2 outline-none focus:ring-2 focus:ring-primary"/></label><PasswordField label="ThreatScope password" value={password} onChange={setPassword}/><button disabled={loading||providers?.local_login_enabled===false} className="w-full rounded-md bg-primary px-4 py-2.5 font-semibold text-primary-foreground disabled:opacity-50">{loading?'Signing in...':'Sign In'}</button>{providers?.self_registration_enabled&&<p className="text-center text-sm">Need a local account? <Link className="text-primary hover:underline" to="/signup">Create Account</Link></p>}<AuthPrivacyNotice compact/><Link to="/" className="block text-center text-sm text-muted-foreground hover:text-foreground">Return to public landing page</Link></form></main>;
}
