import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { Shield,ArrowRight } from 'lucide-react';
import { accessApi,type AuthProviderConfig } from '../../api/access';
import { useAuth } from '../../auth/useAuth';
import { AuthPrivacyNotice } from './components/AuthPrivacyNotice';

const modules=['Web Exposure','API Security','SOC Monitoring','Document Threat Analysis','Phishing Defense','Correlation and Incident Cases','Governance','Operations'];
export function PublicLandingPage(){const {user}=useAuth();const [providers,setProviders]=useState<AuthProviderConfig|null>(null);useEffect(()=>{void accessApi.providers().then(setProviders).catch(()=>setProviders(null));},[]);return <div className="min-h-screen bg-background text-foreground"><header className="flex min-h-16 items-center justify-between border-b px-5 sm:px-8"><div className="flex items-center gap-3"><Shield className="h-7 w-7 text-primary"/><span className="text-lg font-bold">ThreatScope XDR</span></div><nav className="flex gap-2">{user?<Link to="/dashboard" className="rounded bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Open Dashboard</Link>:<><Link to="/login" className="rounded border px-4 py-2 text-sm font-semibold">Sign In</Link>{providers?.self_registration_enabled&&<Link to="/signup" className="rounded bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Create Account</Link>}</>}</nav></header><main><section className="mx-auto max-w-6xl px-5 py-20 sm:py-28"><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Local security operations platform</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-tight sm:text-6xl">Understand exposure, investigate threats, and govern risk from one local workspace.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">ThreatScope XDR combines offline-first analysis and authorized security workflows without requiring an external identity provider.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="inline-flex items-center gap-2 rounded bg-primary px-5 py-3 font-semibold text-primary-foreground">Sign In <ArrowRight className="h-4 w-4"/></Link>{providers?.self_registration_enabled&&<Link to="/signup" className="rounded border px-5 py-3 font-semibold">Create Account</Link>}</div></section><section className="border-y bg-card/40"><div className="mx-auto grid max-w-6xl gap-4 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4">{modules.map(name=><article key={name} className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Permission-controlled local workflows with bounded evidence and safe operational defaults.</p></article>)}</div></section><section className="mx-auto max-w-3xl px-5 py-14"><AuthPrivacyNotice/></section></main><footer className="flex flex-wrap justify-between gap-3 border-t px-5 py-6 text-xs text-muted-foreground sm:px-8"><span>Local deployment; no external identity provider is required.</span><span><Link className="hover:text-foreground" to="/known-limitations">Known limitations</Link> · Release 1.0.0-rc1</span></footer></div>}

export function KnownLimitationsPage(){return <main className="grid min-h-screen place-items-center bg-background p-5"><div className="max-w-2xl rounded-xl border bg-card p-8"><h1 className="text-2xl font-semibold">Known local-account limitations</h1><ul className="mt-5 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>Email ownership is not verified because outbound email is not implemented.</li><li>Password recovery is performed by a local administrator; no reset email is sent.</li><li>ThreatScope supports local accounts only and does not connect to external identity providers or mailboxes.</li></ul><Link to="/" className="mt-6 inline-block text-primary">Return to ThreatScope XDR</Link></div></main>}
